### ISSUE TITLE
API reports Celsius temps without the decimal (10x real number)

### ISSUE THREAD

**Issue by philhzss** [tuya/tuya-home-assistant#11]
My sensor indicates 21.3 C in the SmartLife app, but this API is report 213C in home assistant. This is not a very big deal and I'm sure there's a simple way I could find to divide reported values by 10, but just wanted to let you guys know!

Thank you

![image](https://user-images.githubusercontent.com/41757256/121751469-32dea500-cadc-11eb-888d-d381d78b01e4.png)

**Comment by guigashm** [comment]
I have the  same issue.

**Comment by tsutsuku** [comment]
The issue fixed in V1.2.
You can update to check.

**Comment by philhzss** [comment]
> The issue fixed in V1.2.
> You can update to check.

Hi! Thanks a lot. I'm not sure if I updated properly, but it doesn't seem fixed on my side:


![image](https://user-images.githubusercontent.com/41757256/122507721-b281dd80-cfce-11eb-90a3-c0839a2975d8.png)

To update, I updated in HACS (it told me I could update to 1.2), I restarted Home Assistant. No difference, so I removed the integration completely and re-added it, restart Home Assistant, still no difference. Did a skip a step / am I updating right? Thank you!

**Comment by tsutsuku** [comment]
@philhzss 
Can you provide your device's specifications for terminal log, like this:
[tuya-openapi] Request: method = GET, url = https://openapi.tuyacn.com/v1.0/devices/vdevo162372586962985/specifications, params = None, body = None, headers = {'client_id': 'xxxxxxxxx', 'sign': '8CAE7BB56BCB387542497366C4D84BCD02F588FE2D3F5F351C20EA1A17981A68', 'sign_method': 'HMAC-SHA256', 'access_token': 'xxxxxxxxxxx', 't': '1624071158713', 'lang': 'en'}
[tuya-openapi] Response: {
  "result": {
    "category": "wsdcg",
    "functions": [],
    "status": [
      {
        "code": "va_temperature",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-1000,\"max\":6000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "va_humidity",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":1000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "battery_percentage",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1624071158836
}

**Comment by philhzss** [comment]
> @philhzss
> Can you provide your device's specifications for terminal log, like this:
> [tuya-openapi] Request: method = GET, url = https://openapi.tuyacn.com/v1.0/devices/vdevo162372586962985/specifications, params = None, body = None, headers = {'client_id': 'xxxxxxxxx', 'sign': '8CAE7BB56BCB387542497366C4D84BCD02F588FE2D3F5F351C20EA1A17981A68', 'sign_method': 'HMAC-SHA256', 'access_token': 'xxxxxxxxxxx', 't': '1624071158713', 'lang': 'en'}


I'm getting 400 bad request, I copied what you wrote, replacing the client ID and the access  token with my own (i didnt change the other values).. also tried changing time. Am I supposed to replace the sign too?

Thank you!

**Comment by tsutsuku** [comment]
@philhzss  Don't replace your clientID and the access token.
Just install integration, and setup with your credential.
![image](https://user-images.githubusercontent.com/18442047/122629800-43050e80-d0f2-11eb-8176-db65cecd579f.png)

After hass started from terminal like this:
![image](https://user-images.githubusercontent.com/18442047/122629812-5a43fc00-d0f2-11eb-9c8b-5fa3bee55ede.png)

Found your device info log from terminal.

**Comment by philhzss** [comment]
@tsutsuku Ah ok!! Thank you, I got it. Here are the logs. Something is wrong for sure, do you know what this means?

```
[tuya-openapi] Request: method = GET, url = https://openapi.tuyaus.com/v1.0/devices/ebea6cccdbdc98b235vri4/functions, params = None, body = None, headers = {'client_id': 'xxxxxxxxxxxxx', 'sign': 'xxxxxxxxxxxxx', 'sign_method': 'HMAC-SHA256', 'access_token': 'xxxxxxxxxxxxx', 't': '1623458639263', 'lang': 'en'}
[tuya-openapi] Response: {
  "code": 2009,
  "msg": "不支持此設備",
  "success": false,
  "t": 1623458639338
}
```


I also found this in the log, so even though there is an error its still getting some data?:
```
[tuya-openapi] Request: method = GET, url = https://openapi.tuyaus.com/v1.0/users/xxxxxxxxxxxxx/devices, params = None, body = None, headers = {'client_id': 'sign': 'sign_method': 'HMAC-SHA256', 'access_token': 't': '1623992694924', 'lang': 'en'}
[tuya-openapi] Response: {
  "result": [
    {
      "active_time": 1623457548,
      "biz_type": 18,
      "category": "wsdcg",
      "create_time": 1623457548,
      "icon": "smart/icon/ay1558597489826VMjh1/c78381c006bd14beaa408dca2ef9bb7d.png",
      "name": "Garage temp 2",
      "online": true,
      "owner_id": "xxxxxxxxxxxxxxxx",
      "product_id": "vvldcafpaiwnh3t3",
      "product_name": "Temperature Humidity Sensor",
      "status": [
        {
          "code": "va_temperature",
          "value": 236
        },
        {
          "code": "va_humidity",
          "value": 46
        },
        {
          "code": "battery_state",
          "value": "high"
        }
      ],
      "sub": false,
      "update_time": 1623991720,
    },
```

**Comment by tsutsuku** [comment]
It looks like your integration not updated correctly.
Can you check your integration local file. Like sensor.py in tuya_v2.
The last version should has this code:
`
   @property
    def state(self):
        """Return the state of the sensor."""
        __value = self.tuya_device.status.get(self._code)
        print(self.tuya_device.status_range.get(self._code).values)
        if self.tuya_device.status_range.get(self._code).type == 'Integer':
            __value_range = json.loads(self.tuya_device.status_range.get(self._code).values)
            __state = (__value) * 1.0 / (10 ** __value_range.get('scale'))
            if __value_range.get('scale') == 0:
                return int(__state)
            else:
                return f"%.{__value_range.get('scale')}f" % __state
        return ''
`

**Comment by philhzss** [comment]
> It looks like your integration not updated correctly.
> Can you check your integration local file. Like sensor.py in tuya_v2.
> The last version should has this code:
> `@property def state(self): """Return the state of the sensor.""" __value = self.tuya_device.status.get(self._code) print(self.tuya_device.status_range.get(self._code).values) if self.tuya_device.status_range.get(self._code).type == 'Integer': __value_range = json.loads(self.tuya_device.status_range.get(self._code).values) __state = (__value) * 1.0 / (10 ** __value_range.get('scale')) if __value_range.get('scale') == 0: return int(__state) else: return f"%.{__value_range.get('scale')}f" % __state return ''`

@tsutsuku 

Indeed it seems like something is wrong here, mine only seems to have this:

![image](https://user-images.githubusercontent.com/41757256/122657150-deb47000-d12e-11eb-85b0-d29b875493f8.png)

Thanks a lot for your help, I will try to update the integration again!

**Comment by philhzss** [comment]
I reinstalled it completely and it's fixed!! Thank you!!
