### ISSUE TITLE
Contact/Temperature/Humidity/Luminance sensors not updating values in HA

### ISSUE THREAD

**Issue by escobarin3** [tuya/tuya-home-assistant#110]
**Describe the bug**
I have a Temperature/Humidity/Luminance sensor installed. HA recognizes the device and its initial state values, but they do not refresh or update, so the information cannot be used for automation or information. 

**Expected behavior**
Temperature/Humidity/Luminance value changes should be shown in real time and accurately. 

**Screenshots**

**Home Assistant Version**
Home Assistant 2021.6.6

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**

"active_time": 1625155064,
"biz_type": 18,
"category": "wsdcg",
"create_time": 1625155064,
"icon": "smart/icon/ay1503986080106Gppjy/04b538bf5c86c8394ed187d0941ae8af.png",
"id": "eb4f18af23046ad23bzhbd",
"ip": "",
"lat": "4.6578628",
"local_key": "0b41a35230b5a4d2",
"lon": "-74.1133391",
"name": "Sensor Estudio",
"node_id": "b4e3f9fffe0c4a50",
"online": true,
"owner_id": "13892437",
"product_id": "qaaysllp",
"product_name": "Temperature Humidity Sensor",
"status": [
{
"code": "va_temperature",
"value": 234
},
{
"code": "va_humidity",
"value": 528
},
{
"code": "battery_percentage",
"value": 20
},
{
"code": "temp_unit_convert",
"value": "c"
},
{
"code": "maxtemp_set",
"value": 40
},
{
"code": "minitemp_set",
"value": 10
},
{
"code": "maxhum_set",
"value": 90
},
{
"code": "minihum_set",
"value": 20
},
{
"code": "temp_alarm",
"value": "cancel"
},
{
"code": "hum_alarm",
"value": "cancel"
},
{
"code": "bright_value",
"value": 42
}
],
"sub": true,
"time_zone": "+08:00",
"uid": "az1580355797792RnGLw",
"update_time": 1625222008,
"uuid": "eb4f18af23046ad23bzhbd"
},

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
}
2021-07-07 19:40:43 DEBUG (SyncWorker_5) [tuya iot] Request: method = GET, url = https://openapi.tuyaus.com/v1.0/devices/eb4f18af23046ad23bzhbd/specifications, params = None, body = None, headers = {'client_id': 'cyaqesnvaqg46x4g1ekm', 'sign': '54702BEC2D003038F303DCF4783A9E9154AA3D9B3DBD1755BD9813F959D45C15', 'sign_method': 'HMAC-SHA256', 'access_token': 'XXX---XXXX', 't': '1625704843895', 'lang': 'en'}
2021-07-07 19:40:44 DEBUG (SyncWorker_5) [tuya iot] Response: {
"result": {
"category": "wsdcg",
"functions": [
{
"code": "temp_unit_convert",
"type": "Enum",
"values": "{\"range\":[\"c\",\"f\"]}"
},
{
"code": "maxtemp_set",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":-10,\"max\":60,\"scale\":0,\"step\":1}"
},
{
"code": "minitemp_set",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":-10,\"max\":60,\"scale\":0,\"step\":1}"
},
{
"code": "maxhum_set",
"type": "Integer",
"values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
},
{
"code": "minihum_set",
"type": "Integer",
"values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
}
],
"status": [
{
"code": "va_temperature",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":-100,\"max\":600,\"scale\":1,\"step\":1}"
},
{
"code": "va_humidity",
"type": "Integer",
"values": "{\"unit\":\"%\",\"min\":0,\"max\":1000,\"scale\":1,\"step\":1}"
},
{
"code": "battery_percentage",
"type": "Integer",
"values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
},
{
"code": "temp_unit_convert",
"type": "Enum",
"values": "{\"range\":[\"c\",\"f\"]}"
},
{
"code": "maxtemp_set",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":-10,\"max\":60,\"scale\":0,\"step\":1}"
},
{
"code": "minitemp_set",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":-10,\"max\":60,\"scale\":0,\"step\":1}"
},
{
"code": "maxhum_set",
"type": "Integer",
"values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
},
{
"code": "minihum_set",
"type": "Integer",
"values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
},
{
"code": "temp_alarm",
"type": "Enum",
"values": "{\"range\":[\"loweralarm\",\"upperalarm\",\"cancel\"]}"
},
{
"code": "hum_alarm",
"type": "Enum",
"values": "{\"range\":[\"loweralarm\",\"upperalarm\",\"cancel\"]}"
},
{
"code": "bright_value",
"type": "Integer",
"values": "{\"unit\":\"lux\",\"min\":0,\"max\":1000000,\"scale\":0,\"step\":1}"
}
]
},
"success": true,
"t": 1625704843996
}

**Additional context**
Add any other context or logs about the problem here.

**Comment by escobarin3** [comment]
I forgot to mention that the device is connected through a Zigbee Gaeteway. Does this affect?

**Comment by akkaria** [comment]
> I forgot to mention that the device is connected through a Zigbee Gaeteway. Does this affect?

Do your devices show as offline in the Tuya IoT Platform? I've got a similar issue to you and i feel like it has something to do with the fact that the devices show offline until they go online for a split second, talk back to the hub and then the hub does the updating, then they go back offline again.

**Comment by escobarin3** [comment]
> > I forgot to mention that the device is connected through a Zigbee Gaeteway. Does this affect?
> 
> Do your devices show as offline in the Tuya IoT Platform? I've got a similar issue to you and i feel like it has something to do with the fact that the devices show offline until they go online for a split second, talk back to the hub and then the hub does the updating, then they go back offline again.

Hello. No, they show online. The original TUYA integration didn't recognize the device, so I couldn't use it for automations. 
With Tuya 2 integration I was happy because the devices are now supported... bad luck they do not update. 

All I want is for HA to turn on the lights automatically when lux levels are low... :(

**Comment by escobarin3** [comment]
I just noticed that my Tuya Contact/Door sensors are not updating automatically. Checking other issues posted... I think is a generalized problem with sensors.

**Comment by tsutsuku** [comment]
@sanshengshui https://github.com/tuya/tuya-home-assistant/discussions/113

**Comment by escobarin3** [comment]
Digging a little deeper... I also noticed that all my status devices do not update. I can control them, but the device/entity status always remain the same. So right now, according to HA, my door is always closed, my robot is always cleaning, my curtains are always closed... and my luminance level is always 100 lux.. I guess the issue is not only with sensors states.

**Comment by escobarin3** [comment]
> @sanshengshui #113

Perfect. That was it. Thanks for the heads tip.
