### ISSUE TITLE
Bulbs that lost power need HA Restart to reconnect

### ISSUE THREAD

**Issue by seayworld** [tuya/tuya-home-assistant#115]
**Describe the bug**
I have two GU10 5W bulbs (gjoql8b394g4jkt8) connected to Tuya Smart and Home Assistant.  Wall switch was turned off and bulbs dropped off WiFi.  When power restored, bulbs reconnected and were available in Tuya Smart App, and Original HA Tuya integration.  But V2 Tuya Integration would not show the bulbs available until HA was restarted.

**Expected behavior**
Tuya V2 Integration would make devices available in HA after a power loss without having to restart HA.

**Home Assistant Version**
Home Assistant 2021.7.1

**Tuya Integration**
V2 1.3.1

**Comment by tsutsuku** [comment]
@seayworld Get it.

**Comment by seayworld** [comment]
Adding 'Device Status Notification' resolved the issue.
