### ISSUE TITLE
Add support for RF PIR sensor

### ISSUE THREAD

**Issue by carlosvroque** [tuya/tuya-home-assistant#119]
**Device normal info**
- Positivo
- RF PIR Sensor

It's connected to an RF Alarm/gateway, the contact sensors are supported and work normally, but the PIR sensor is not displayed. Judging by the category "pir" it should be supported since 1.2 and I'm on 1.3.1.

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
like this:
    {
      "active_time": 1586305177,
      "biz_type": 18,
      "category": "pir",
      "create_time": 1570544355,
      "icon": "smart/icon/ay1546425778531nm5KI/15632216406f5196bcc71.jpg",
      "id": "ebc39feafb620ad33e9avq",
      "ip": "",
      "lat": "",
      "local_key": "adb344307a0a012b",
      "lon": "",
      "model": "PSM RF",
      "name": "Presence Sensor",
      "node_id": "020019F7",
      "online": true,
      "owner_id": "14917182",
      "product_id": "1vicgrxatm6rfn3h",
      "product_name": "Sensor de Presença",
      "status": [],
      "sub": true,
      "time_zone": "+08:00",
      "uid": "az15833471924845B1Pk",
      "update_time": 1625833268,
      "uuid": "ebc39feafb620ad33e9avq"
    },

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
Same device's id, like this:
2021-07-09 15:35:21 DEBUG (SyncWorker_3) [tuya iot] Request: method = GET, url = https://openapi.tuyaus.com/v1.0/devices/ebc39feafb620ad33e9avq/specifications, params = None, body = None, headers = {'client_id': 'fkcphfxdaqioiqlwsrw4', 'sign': 'A7FC36C4F2B82B6F2BA2139FA1BF9B71748F3CF03EA52999362A819E875E71EE', 'sign_method': 'HMAC-SHA256', 'access_token': 'c6602ea989271d99fa81a96d8f4685dd', 't': '1625855721373', 'lang': 'en'}
2021-07-09 15:35:21 DEBUG (Thread-3) [tuya iot] _on_log: Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=b'cloud_676a7f36aa2abd8efa5fc1a1fa4c240c'
2021-07-09 15:35:21 DEBUG (SyncWorker_3) [tuya iot] Response: {
  "code": 2009,
  "msg": "not support this device",
  "success": false,
  "t": 1625855721533

**Comment by carlosvroque** [comment]
I really couldn't find the "device specifications" in log, so I went and checked the order of devices and found the log entry that "matched". If I did anything wrong or more info is needed, please let me know.

**Comment by tsutsuku** [comment]
@carlosvroque Your device is standradized. Try again.

**Comment by carlosvroque** [comment]
Thanks a lot for the reply! 
Now the device shows up in HA but it does **not** update. 

![image](https://user-images.githubusercontent.com/65680394/125790815-e2648847-90b8-47dc-992d-06b1db1919f6.png)

It looks like the same issue as #57, so I guess I'll wait until the next update and try again.

In case it's helpful here are the new logs:

> 2021-07-15 08:59:48 DEBUG (SyncWorker_4) [tuya iot] Response: {
> "result": [
> {
> "active_time": 1586305177,
> "biz_type": 18,
> "category": "pir",
> "create_time": 1570544355,
> "icon": "smart/icon/ay1546425778531nm5KI/15632216406f5196bcc71.jpg",
> "id": "ebc39feafb620ad33e9avq",
> "ip": "",
> "lat": "",
> "local_key": "adb344307a0a012b",
> "lon": "",
> "model": "PSM RF",
> "name": "Presence Sensor",
> "node_id": "020019F7",
> "online": true,
> "owner_id": "14917182",
> "product_id": "1vicgrxatm6rfn3h",
> "product_name": "Sensor de Presença",
> "status": [
> {
> "code": "pir",
> "value": "none"
> },
> {
> "code": "battery_state",
> "value": "high"
> }
> ],
> "sub": true,
> "time_zone": "+08:00",
> "uid": "az15833471924845B1Pk",
> "update_time": 1626013542,
> "uuid": "ebc39feafb620ad33e9avq"
> },

> 2021-07-15 08:59:48 DEBUG (SyncWorker_4) [tuya iot] Response: {
> "result": {
> "category": "pir",
> "functions": [],
> "status": [
> {
> "code": "pir",
> "type": "Enum",
> "values": "{\"range\":[\"pir\",\"none\"]}"
> },
> {
> "code": "battery_state",
> "type": "Enum",
> "values": "{\"range\":[\"low\",\"high\"]}"
> }
> ]
> },
> "success": true,
> "t": 1626350388580
> }

**Comment by carlosvroque** [comment]
After @tsutsuku changes and updating to version v1.3.2 the sensor is now working as intended! 

Thanks a lot

**Comment by iotinkognito** [comment]
Same issues as #140 #57 #119 #57 #144 #271 #262
