### ISSUE TITLE
Entity reverting to previous state

### ISSUE THREAD

**Issue by StevenDavidWillimas** [tuya/tuya-home-assistant#121]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Home Assistant Version**
- e.g. 2021.5.1

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
like this:
{
      "active_time": 1623229189,
      "biz_type": 18,
      "category": "cz",
      "create_time": 1560491945,
      "icon": "smart/product_icon/cz.png",
      "id": "aaaaaaaaaaa",
      "ip": "xxxxxxxxxxxxxxxx",
      "lat": "30.30286857361191",
      "local_key": "xxxxxxxxxxxxx",
      "lon": "120.0639743842656",
      "model": "",
      "name": "Living Room Socket",
      "online": false,
      "owner_id": "34794909",
      "product_id": "yfemiswbgjhddhcf",
      "product_name": "Switch Product",
      "status": [
        {
          "code": "switch",
          "value": false
        },
        {
          "code": "countdown_1",
          "value": 0
        },
        {
          "code": "cur_current",
          "value": 0
        },
        {
          "code": "cur_power",
          "value": 0
        },
        {
          "code": "cur_voltage",
          "value": 2343
        }
      ],
      "sub": false,
      "time_zone": "+08:00",
      "uid": "xxxxxxxxxxxxxxxxxxx",
      "update_time": 1625101929,
      "uuid": "xxxxxxxxxxxxxxxxxx"
    }

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
Same device's id, like this:
[2021-07-01 10:18:01,351] [tuya-openapi] Request: method = GET, url = https://openapi.tuyacn.com/v1.0/devices/aaaaaaaaaaa/specifications, params = None, body = None, headers = {'client_id': 'xxxxxxxxxxxx', 'sign': 'xxxxxxxxxxxx', 'sign_method': 'HMAC-SHA256', 'access_token': '213e2d4af5e8d217abc0b104462a9f72', 't': '1625105881351', 'lang': 'en'}
2021-07-01 10:18:01 DEBUG (SyncWorker_1) [tuya iot] Response: {
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "cur_voltage",
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":2500,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_current",
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "cur_power",
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":50000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1625105881348
}

**Additional context**
Add any other context or logs about the problem here.
I recently installed Tuya v2, when trying to set up switches, they revert to their previous state, almost instantly. ie, switch is ON, switch off in HA,    reverts to ON, and vice versa.

**Comment by petethumped** [comment]
OK with the caveat that I don't really know what I'm talking about, up to about an hour ago I had what I _think_ was the same problem with a Zigbee light switch connected via an Aldi Zigbee Gateway.

I've no idea how it got fixed, but immediately before it started working I did two things - I tried adding some additional Tuya APIs to my project and i did a full reboot of my HA server. 

The APIs I added were:

- Beta APIs	
- Device Log Query	
- Device status notification

I suspect one or more of these might be specified as a requirement somewhere in some documentation I didn't read - I had a tuya dev project set up already from trying to extract device info for a Local Tuya setup, so i just reused that for the v2 integration. This may have been a mistake.

Anyway after a week of switches not responding through the HA interface (or rather turning on then back off again, with nothing happening on the physical switch) it just started working... Previously I'd been seeing what I assumed were successful API calls in the debug log, but now that it's _actually_ working i can see tons more activity.

**Comment by petethumped** [comment]
hahaaaa oops always RTFM I guess....

https://developer.tuya.com/en/docs/iot/Platform_Configuration_smarthome?id=Kamcgamwoevrx

**Comment by kbarendrecht** [comment]
@petethumped I was one of the first trying this integration, before that guide existed. thanks to your post I found out I need to register that API. Thanks 😄 
@StevenDavidWillimas configuring the device status notifcation api solved this problem for me, can you verify it works for you too and close this?

**Comment by StevenDavidWillimas** [comment]
Tried adding device notification Aliexpress, now none of the v2 devices are visible.

**Comment by VNRARA** [comment]
When I make a new project that API doesn't even show...

**Comment by StevenDavidWillimas** [comment]
I'm now having trouble with one of my lights in LOCAL TUYA reverting to previous state.

**Comment by VNRARA** [comment]
Found it: You have to specifically look for the API and subscribe to it and enable it for the projects you want

**Comment by iotinkognito** [comment]
> I'm now having trouble with one of my lights in LOCAL TUYA reverting to previous state.

Getting a similar issue. Except its triggering the same state at random intervals. E.g. I have a switch with a automation to occur when it is turned off. I am getting multiple 'off's without ever touching the switch.

**Comment by StevenDavidWillimas** [comment]
I've now updated to 1.4, to see if this would work, and removed integration from HA, now getting "Invalid Authentication", when I try to integrate tuya V2. Wondering if I should even bother with this beta version!

**Comment by VNRARA** [comment]
Maybe you should be more accurate when setting it up.. It's tricky but when it's set up, it works great. Delete the whole thing and start over. Make sure you follow the youtube video of Mark Watt Tech

**Comment by StevenDavidWillimas** [comment]
I've tried doing it from scratch, and was extra careful, followed to the letter. The problem is the config that worked when I  originally installed it does not now work. Used same ID and secret, all other parameters as before but get "Invald Authentication".

**Comment by StevenDavidWillimas** [comment]
Now working.

**Comment by iotinkognito** [comment]
Not working for Bluetooth pir arlec.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
