### ISSUE TITLE
Using Smart Life AND Tuya Smart Apps - Both Linked to same Cloud Project

### ISSUE THREAD

**Issue by JGrantman** [tuya/tuya-home-assistant#130]
I have devices in both Smart Life and Tuya Smart Android app.  This is only method to limit which devices are available in Google Home because everyone that is attached to a home in the Google Home app has access to every device.

Using Home Assistant custom Tuya integration I am able to add any devices in my cloud project whether they come from Smart Life or Tuya Smart app.  When setting up Tuya V2 integration it appears you are limited to one configuration Smart Life or Tuya Smart.

Is there a work around to allow devices from both Smart Life AND Tuya Smart apps that are linked to same cloud project to show up in Home Assistant?  If not is that something that can be added?

**Comment by JGrantman** [comment]
I have a color rope light devices category "dd" product id "e2zw3ra5sd3vfx7r" that does not show option for scene_data in Home Assistant when added via Tuya V2 integration.  However, the same device when added via custom integration does show scene data selection option for device.  I have several other color lights and none are added with scene_data using Tuya V2 integration.

Is this a bug or unsupported?  If unsupported can support for scene_data be added to Tuya V2 integration for color lights supporting scene data?

**Comment by tsutsuku** [comment]
@JGrantman 
1. You can fork tuya v2 integration and create your custom integration, then you can login tuya v2 with Smart Life and login your custom integration with Tuya Smart app.
2. scene_data is unsupported now, we will consider it.

**Comment by JGrantman** [comment]
That is an excellent idea.  Had not thought about 2nd integration which may be better option than two cloud app/accounts tied to a single integration.
