### ISSUE TITLE
Door Window Sensor not added to device list in Integration

### ISSUE THREAD

**Issue by petebdeblois** [tuya/tuya-home-assistant#14]
According to the post on [HA forums](https://community.home-assistant.io/t/tuya-official-home-assistant-integration-on-github-now/316026/8), _"mcs",  # Door Window Sensor_ are supported in v2. 
My device(50017 - V2) is added to my Tuya app and I can see it in the device list in Dev-Tuya.
Still, I cant see the device in Home Assistant Integration

**Comment by tsutsuku** [comment]
@petebdeblois Can you provide your device (50017 - V2) 's device info from HA log, like this : 
`
    {
      "active_time": 1623293246,
      "biz_type": 0,
      "category": "wsdcg",
      "create_time": 1622269942,
      "icon": "smart/icon/15248170831ukrdpumicrje4hs8qgl9885mi_0.png",
      "id": "xxxxxxxxx",
      "ip": "",
      "lat": "0",
      "local_key": "xxxxxxxx",
      "lon": "0",
      "name": "Temperature and humidity sev",
      "node_id": "ccccccfffe3e4046",
      "online": true,
      "owner_id": "xxxxxx",
      "product_id": "vtA4pDd6PLUZzXgZ",
      "product_name": "Temperature and humidity sensor",
      "status": [
        {
          "code": "va_humidity",
          "value": 65
        },
        {
          "code": "va_battery",
          "value": 100
        },
        {
          "code": "va_temperature",
          "value": 27
        }
      ],
      "sub": true,
      "time_zone": "+08:00",
      "uid": "xxxxxxxxxxxxxxx",
      "update_time": 1623823855,
      "uuid": "6cac4d973c757cb0988ql3"
    }
`

**Comment by petebdeblois** [comment]
There is none of that in my HA log, though this is accessible on the API Explorer on tuya platform 
`{
  "result": {
    "active_time": 1623973628,
    "biz_type": 0,
    "category": "mc",
    "create_time": 1623953276,
    "icon": "smart/icon/ay15281362075689iOHb/c3f3735f733873187ec08fed84ec5ac9.png",
    "id": "xxxxxx",
    "ip": "xxxx",
    "lat": "46",
    "local_key": "xxxx",
    "lon": "-71",
    "name": "Door - Freezer",
    "online": true,
    "owner_id": "xxxx",
    "product_id": "gjahtjddlex4uaqf",
    "product_name": "50017 - V2",
    "status": [],
    "sub": false,
    "time_zone": "-05:00",
    "uid": "xxxxxx",
    "update_time": 1623978960,
    "uuid": "82667230a4cf12e50f50"
  },
  "success": true,
  "t": 1623984441526
}`

Weird thing is, status seems always empty. Could that be it?

**Comment by tsutsuku** [comment]
You device's category is "mc" , which means "Door and Window Controller (mc)". 
It not support by integration now. 
We will consider support it in next release.

**Comment by petebdeblois** [comment]
So you are saying its possible and `may` be added in next release. 
I bought it yesterday so this will help in the decision to keep it or not.

**Comment by bmorgan99** [comment]
I have a "PIR Light" that wasn't discovered.  Same issue?

**Comment by tsutsuku** [comment]
@bmorgan99  

> I have a PIR Light, category: gyd, that registered in the Device List, but wasn't added to HA. Same issue?

Yes, this category not supported now.

**Comment by strasharo** [comment]
My contact sensor shows up as "mcs" instead of the mentioned "mc" in the API explorer.
"category": "mcs"
Is that one unsupported as well currently?

**Comment by tsutsuku** [comment]
@strasharo mcs is supported.

**Comment by strasharo** [comment]
Okay, in that case something is wrong. What information can I provide you, so we can troubleshoot it further?

**Comment by strasharo** [comment]
@petebdeblois mcs just got resolved for me in v1.3.1. Try it, it should be fixed for you as well.

**Comment by petebdeblois** [comment]
@strasharo Thx for the info,  I got a refund for mine since I didn't have a approx ETA and it was basically a brick with the original app. It was a `category: mc` not a `mcs`. This is not added yet, though there is a [pull request](https://github.com/tuya/tuya-home-assistant/pull/75) open. Lets see

**Comment by atv2016** [comment]
I have a mcs door sensor, i'm not seeing it show up either. How did this get resolved?

**Comment by strasharo** [comment]
Sensors showed up after updating to core-2021.11.0

**Comment by iMrLopez** [comment]
@strasharo sensors now show up, but they show as unsupported and no entities are created for them

**Comment by strasharo** [comment]
They work fine for me.

**Comment by iMrLopez** [comment]
@MartinHjelmare I see you just approved a PR for this that got merged to dev, is this planned to go on the next release then?

**Comment by MartinHjelmare** [comment]
The March release, yes.
