### ISSUE TITLE
All Devices Show incorrect state.

### ISSUE THREAD

**Issue by iotinkognito** [tuya/tuya-home-assistant#141]
I have removed original Tuya Integration and only use v2. When I click a device to switch it on it toggles back to the original state. I.e if it's showing as off in the device/entity detail screen and then I "turn it on" it reverts back to off. This is all lights.

**Comment by petethumped** [comment]
you are not alone

https://github.com/tuya/tuya-home-assistant/issues/121#issuecomment-877495753

**Comment by nscorpiok** [comment]
Same issue here with my light switch

**Comment by petethumped** [comment]
> Same issue here with my light switch

Try the fix in the link above.

**Comment by nscorpiok** [comment]
> > Same issue here with my light switch
> 
> Try the fix in the link above.

This finally works! Thank you so much :)

**Comment by iotinkognito** [comment]
I am also getting lots of triggers from state to state. I.E Switch off to off. This is mighty annoying on automations for device button presses.

**Comment by iotinkognito** [comment]
1.4.2 working.
