### ISSUE TITLE
Door and Window sensor WIFI does not changing status in HA (open/closed)

### ISSUE THREAD

**Issue by alexreddy78** [tuya/tuya-home-assistant#143]
{
  "result": {
    "active_time": 1624267199,
    "biz_type": 18,
    "category": "mcs",
    "create_time": 1600710779,
    "icon": "smart/product_icon/qt.png",
    "id": "",
    "ip": "",
    "lat": "",
    "local_key": "",
    "lon": "",
    "name": "Дверь Тайная комната",
    "online": true,
    "owner_id": "16305239",
    "product_id": "7by9ERqg60JA8wxA",
    "product_name": "Door Sensor",
    "status": [
      {
        "code": "doorcontact_state",
        "value": true
      },
      {
        "code": "battery_value",
        "value": 88
      }
    ],
    "sub": false,
    "time_zone": "+03:00",
    "uid": "eu1600250372644kZmGd",
    "update_time": 1626253582,
    "uuid": "120030125002916beca2"
  },
  "success": true,
  "t": 1626253843579
}

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
Get device specification attributes

{
  "result": {
    "category": "mcs",
    "functions": [],
    "status": [
      {
        "code": "doorcontact_state",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "battery_value",
        "type": "Integer",
        "values": "{\"unit\":\"v\",\"min\":0,\"max\":1000,\"scale\":-2,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1626254856830
}

**Comment by tsutsuku** [comment]
@alexreddy78 https://github.com/tuya/tuya-home-assistant/discussions/113

**Comment by alexreddy78** [comment]
Thx! Working now 👍🏻

**Comment by alexreddy78** [comment]
Noop! Still doesn’t work, changed to closed after HA reboot, but stuck the same status after…

**Comment by alexreddy78** [comment]
Pardon! Batteries…Confirm working
