### ISSUE TITLE
My devices Breaker does not appear 

### ISSUE THREAD

**Issue by jeneansantos** [tuya/tuya-home-assistant#147]
Hello, I installed version 1.3.1 of Tuya V2, but my devices Breaker do not appear,  any solution?
https://i.ibb.co/DY9w3FF/Screenshot-3.jpg

**Comment by tsutsuku** [comment]
@jeneansantos Can you provide your device specification from the log?

**Comment by jeneansantos** [comment]
@tsutsuku 
Device Information
Product Name
Latched hidden Switch Single pro
Device ID
eb96bca70878fa6e6fjiqx
Product Category
tdq
Device Status
Online
Activated At
2021-07-08 20:20:09

**Comment by patrik-malina** [comment]
Here is mine info:

{
"active_time": 1617294289,
"biz_type": 18,
"category": "tdq",
"create_time": 1617294289,
"icon": "smart/icon/ay1543221103243UgKoi/d8b0e95a865addc4fa431854beb549cd.png",
"id": "bf59ce4eb1d4f7b3b0gc2t",
"ip": "46.17.124.38",
"lat": "45.4122106",
"local_key": "3120ba6ed7e060cb",
"lon": "19.3027781",
"model": "Latched hidden Switch Single pro",
"name": "Living Room Lamp",
"online": true,
"owner_id": "17222907",
"product_id": "ogupymaavjyzigvr",
"product_name": "Latched hidden Switch Single",
"status": [
{
"code": "switch_1",
"value": false
},
{
"code": "countdown_1",
"value": 0
},
{
"code": "relay_status",
"value": "2"
},
{
"code": "random_time",
"value": ""
}

**Comment by patrik-malina** [comment]
I would make new pull, but idk how.
adding this line in TUYA_SUPPORT_TYPE in switch.py finds mine:
"tdq",    # Breaker

**Comment by jeneansantos** [comment]
@patrik-malina Excellent, I added this line and appear all my devices. Thank you very much
