### ISSUE TITLE
Tuya WIFI Thermostat, appear in HA integration, but no entity exist to control it

### ISSUE THREAD

**Issue by alexreddy78** [tuya/tuya-home-assistant#149]
{
  "result": {
    "active_time": 1604220841,
    "biz_type": 18,
    "category": "wk",
    "create_time": 1604220841,
    "icon": "smart/icon/15264583415nnlzwfs1qd2wqz6i937op3nmi_0.png",
    "id": "",
    "ip": "",
    "lat": "",
    "local_key": "",
    "lon": "",
    "name": "Тёплые полы",
    "online": true,
    "owner_id": "16105612",
    "product_id": "IAYz2WK1th0cMLmL",
    "product_name": "thermostat",
    "status": [
      {
        "code": "switch",
        "value": false
      },
      {
        "code": "temp_set",
        "value": 42
      },
      {
        "code": "upper_temp",
        "value": 60
      },
      {
        "code": "eco",
        "value": false
      },
      {
        "code": "child_lock",
        "value": false
      }
    ],
    "sub": false,
    "time_zone": "+03:00",
    "uid": "eu1600250372644kZmGd",
    "update_time": 1626133905,
    "uuid": "31571686cc50e3f542d2"
  },
  "success": true,
  "t": 1626337127208
}
    }

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
Same device's id, like this:
{
  "result": {
    "category": "wk",
    "functions": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "child_lock",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":10,\"max\":70,\"scale\":1,\"step\":5}"
      },
      {
        "code": "eco",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "upper_temp",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":5}"
      }
    ],
    "status": [
      {
        "code": "eco",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":10,\"max\":70,\"scale\":1,\"step\":5}"
      },
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "child_lock",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "upper_temp",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":5}"
      }
    ]
  },
  "success": true,
  "t": 1626337719647
}

**Comment by patrik-malina** [comment]
Same here:

{
"active_time": 1605952059,
"biz_type": 18,
"category": "qn",
"create_time": 1605952059,
"icon": "smart/icon/ay1539244260287RY0l6/15591841423ee64e9437b.png",
"id": "bf40b9e3bb5c1f2e01wxjf",
"ip": "46.17.124.38",
"lat": "45.4122106",
"local_key": "8b7187c5959db9ef",
"lon": "19.3027781",
"model": "ETOP-HT",
"name": "Thermostat",
"online": true,
"owner_id": "17222907",
"product_id": "0yj3dopm2hu61ntu",
"product_name": "HeatingThermostat",
"status": [
{
"code": "switch",
"value": true
},
{
"code": "temp_set",
"value": 215
},
{
"code": "temp_current",
"value": 290
},
{
"code": "lock",
"value": false
}
],
"sub": false,
"time_zone": "+01:00",
"uid": "eu1602628501573H9rx2",
"update_time": 1626352354,
"uuid": "555f2588c1709952"
},

**Comment by michalpulda** [comment]
I have the same problem.

**Comment by tombenetin** [comment]
Same problem..i see devices but here is no entity to control it.

**Comment by BlendMind** [comment]
I have the same problem.

**Comment by alexreddy78** [comment]
@tsutsuku Dear Tsutsuku,

Kindly advise if any updates regarding above mentioned.
LOG from HA attached.

Logger: homeassistant
Source: custom_components/tuya_v2/climate.py:353
Integration: Tuya v2 (documentation)
First occurred: 28 июля 2021 г., 21:29:55 (3692 occurrences)
Last logged: 11:34:09

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 406, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 450, in _async_write_ha_state
    attr = self.capability_attributes
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 219, in capability_attributes
    ATTR_HVAC_MODES: self.hvac_modes,
  File "/config/custom_components/tuya_v2/climate.py", line 353, in hvac_modes
    modes = json.loads(self.tuya_device.function.get(DPCODE_MODE, {}).values).get(
  File "/usr/local/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not builtin_function_or_method

**Comment by alexreddy78** [comment]
@tsutsuku Dear Tsutsuku,

Did you have a little chance and time to see LOGs above and advise if there’s any updates on issue?

REGARDS and hope hear you soon

**Comment by alexreddy78** [comment]
@tsutsuku Thanks! Working now.

REGARDS

**Comment by alexreddy78** [comment]
@tsutsuku Dear Tsutsuku,

Have to reopen issue :( same as in issues #360 and #357 

Regads

**Comment by alexreddy78** [comment]
@tsutsuku Dear Tsutsuku,

Kindly advise if there is any updates on the bug mentioned above. Thermostat still didnt work on proper way

Regards!

**Comment by alexreddy78** [comment]
@tsutsuku Dear Tsutsuku,

Pls advise if any updates planed? :) no new releases from 1.5 for such long period :)))
