### ISSUE TITLE
Tuya Wifi Smoke Detector, no entity in HA, only battery status and shown as unavailable 

### ISSUE THREAD

**Issue by alexreddy78** [tuya/tuya-home-assistant#151]
{
  "result": {
    "active_time": 1611949452,
    "biz_type": 18,
    "category": "ywbj",
    "create_time": 1603378663,
    "icon": "smart/icon/ay1537847617560vAgbw/98dd275e7b0720f5b691906080b7651b.png",
    "id": "52551750483fda5b5585",
    "ip": "31.173.87.22",
    "lat": "55.58741721721499",
    "local_key": "423351a9fcc6088f",
    "lon": "37.65151949393897",
    "name": "Детектор дыма",
    "online": true,
    "owner_id": "16105612",
    "product_id": "4w4a6noxfgk0yktc",
    "product_name": "Smoke Alarm",
    "status": [
      {
        "code": "smoke_sensor_status",
        "value": "normal"
      },
      {
        "code": "temper_alarm",
        "value": false
      },
      {
        "code": "battery_state",
        "value": "high"
      }
    ],
    "sub": false,
    "time_zone": "+03:00",
    "uid": "eu1600250372644kZmGd",
    "update_time": 1611949454,
    "uuid": "52551750483fda5b5585"
  },
  "success": true,
  "t": 1626338296622
}

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
Same device's id, like this:
{
  "result": {
    "category": "ywbj",
    "functions": [],
    "status": [
      {
        "code": "smoke_sensor_status",
        "type": "Enum",
        "values": "{\"range\":[\"alarm\",\"normal\"]}"
      },
      {
        "code": "temper_alarm",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "battery_state",
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"middle\",\"high\"]}"
      }
    ]
  },
  "success": true,
  "t": 1626338386374
}

**Comment by patrik-malina** [comment]
Smoke detector works now, only battery info is missing for me.

**Comment by alexreddy78** [comment]
Confirm, working now
