### ISSUE TITLE
V2 version doens show on integration

### ISSUE THREAD

**Issue by cylonr** [tuya/tuya-home-assistant#159]
**Expected behavior**
After installl the V2 version, it only show Tuya on integrations... not the V2 version
![11s](https://user-images.githubusercontent.com/34467765/126032598-498fe318-4aa8-4ebc-b9a4-5bf093822171.jpg)

**Home Assistant Version**
2021.7.3

**Comment by nmisha** [comment]
+1 Ididn't see it in HACS and add ons

**Comment by tbratfisch** [comment]
Did you add this repository to HACS?
see
https://github.com/tuya/tuya-home-assistant/wiki/Install-Tuya-v2

**Comment by escobarin3** [comment]
> **Expected behavior**
> After installl the V2 version, it only show Tuya on integrations... not the V2 version
> ![11s](https://user-images.githubusercontent.com/34467765/126032598-498fe318-4aa8-4ebc-b9a4-5bf093822171.jpg)
> 
> **Home Assistant Version**
> 2021.7.3

Happened the same to me... had to wait restart HA, wait a while and restart HA again. After that it appeared in HA.

**Comment by Gubbfittan** [comment]
Home Assistant blue. same issue. Followed all steps, restarted HA several times, only "Tuya" and "LocalTuya integration" showing up in list

**Comment by tsutsuku** [comment]
Sorry, there is something wrong with the Wiki install. We fix it. Follow this and try again:
https://github.com/tuya/tuya-home-assistant/wiki/Install-Tuya-v2#22-install-by-hacs

**Comment by alexmehlhorn** [comment]
Same issue here. No waiting or clearing cache is resolving it. Tried installing older version first. No luck. Not sure.

**Comment by JerryCih** [comment]
Same here, its in HACS but not in integrations, only original Tuya

**Comment by UraniumDonut** [comment]
Same issue here

**Comment by UraniumDonut** [comment]
Addition: installing it manually (not HACS) also doesn't work

**Comment by frenck** [comment]
Since the V2 integration has been removed (and  the new integration is now part of  the Home Assistant Core), I'll go ahead and close up this issue.
