### ISSUE TITLE
position not valid cover (always 100)

### ISSUE THREAD

**Issue by rickroetenberg** [tuya/tuya-home-assistant#169]
old: DPCODE_PERCENT_STATE = "percent_state" -> new: DPCODE_PERCENT_STATE = "percent_control"

also row 95 should be without 100 -

**Comment by redlegoman** [comment]
This bug was closed but I can't see if a fix was put in place. I have the same problem. I have a cover that will open and close but the position always shows "100" and the status is always "open".  Has it been fixed, or added to a backlog?
