### ISSUE TITLE
Switch(cz) doesn't get current/voltage info

### ISSUE THREAD

**Issue by petebdeblois** [tuya/tuya-home-assistant#17]
I own a switch which is supposed to get current/voltage/kw. It does work on Tuya App, but I only have "friendly name" in HA
`{
  "result": {
    "active_time": 1624047917,
    "biz_type": 0,
    "category": "cz",
    "create_time": 1624047917,
    "icon": "smart/icon/1472009231_0.png",
    "id": "xxxxxxx",
    "ip": "xxxxxx",
    "lat": "46.",
    "local_key": "xxxx",
    "lon": "-71.",
    "name": "Office - Screens",
    "online": true,
    "owner_id": "xxxx",
    "product_id": "cET7nrXx83igNwGF",
    "product_name": "BW-SHP12",
    "status": [
      {
        "code": "switch",
        "value": true
      },
      {
        "code": "countdown_1",
        "value": 0
      },
      {
        "code": "cur_current",
        "value": 0
      },
      {
        "code": "cur_power",
        "value": 0
      },
      {
        "code": "cur_voltage",
        "value": 0
      }
    ],
    "sub": false,
    "time_zone": "-04:00",
    "uid": "az1620507524733rqtWu",
    "update_time": 1624048387,
    "uuid": "012007585ccf7f6bf519"
  },
  "success": true,
  "t": 1624146860466
}`
Is this feature supported?

**Comment by tsutsuku** [comment]
@petebdeblois This feature is not supported now.

**Comment by tsutsuku** [comment]
@petebdeblois  current/voltage/kw supported in v1.3

**Comment by petebdeblois** [comment]
Thank you @tsutsuku 
I can see the current, power and voltage as a separate sensor.
