### ISSUE TITLE
Temp. and Hum. Sensor mixing Humidity and Temperature values

### ISSUE THREAD

**Issue by pauloantoniassi** [tuya/tuya-home-assistant#171]
**Describe the bug**
Te sensor is reporting temperature and humidity on the same entity

**Expected behavior**
I expect temperature and humidity on different entity or, at least, different attributes.

**Screenshots**
N/A

**Home Assistant Version**
2021.7.1
Integration v1.3.2

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
``` 
{
"active_time": 1626577287,
"biz_type": 0,
"category": "wsdcg",
"create_time": 1620258740,
"icon": "smart/icon/ay1534490862266NApJD/1561791651f212a0ff759.jpg",
"id": "---",
"ip": "",
"lat": "",
"local_key": "---",
"lon": "",
"model": "ZXZTH-02",
"name": "Temp. e Umidade",
"node_id": "---",
"online": true,
"owner_id": "---",
"product_id": "jigsujrv",
"product_name": "Temperature and humidity sensor",
"status": [
{
"code": "va_temperature",
"value": 3024
},
{
"code": "battery_value",
"value": 87
},
{
"code": "va_temperature",
"value": 2158
}
],
"sub": true,
"time_zone": "+08:00",
"uid": "---",
"update_time": 1626641161,
"uuid": "---"
} 
```

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
Same device's id, like this:
```
[tuya iot] Request: method = GET, url = https://openapi.tuyaus.com/v1.0/devices/ebde98afa72c4bd160xlga/specifications, params = None, body = None, headers = {'client_id': '---', 'sign': '---', 'sign_method': 'HMAC-SHA256', 'access_token': '---', 't': '1626651096701', 'lang': 'en'}
2021-07-18 20:31:36 DEBUG (SyncWorker_0) [tuya iot] Response: {
"result": {
"category": "wsdcg",
"functions": [],
"status": [
{
"code": "va_temperature",
"type": "Integer",
"values": "{\"unit\":\"\",\"min\":-2000,\"max\":10000,\"scale\":2,\"step\":1}"
},
{
"code": "va_temperature",
"type": "Integer",
"values": "{\"unit\":\"% RH\",\"min\":0,\"max\":10000,\"scale\":2,\"step\":1}"
},
{
"code": "battery_value",
"type": "Integer",
"values": "{\"unit\":\"\",\"min\":0,\"max\":500,\"scale\":0,\"step\":1}"
}
]
},
"success": true,
"t": 1626651096848
}
```

**Additional context**
I've noticed that the device (API) are returning 2 atributes/status as `va_temperature`.

**Comment by antoniassiph** [comment]
I'm pretty sure it's an Tuya API issue, I don't know if there's anything we can do.

**Comment by tsutsuku** [comment]
@antoniassiph  Can you provide your device Screenshots?

**Comment by antoniassiph** [comment]
Sure, first HA history. Later Tuya App.

![image](https://user-images.githubusercontent.com/8649042/126098722-b4e24d77-7228-4524-9977-d103519a74f5.png)
![photo5163933914530687469](https://user-images.githubusercontent.com/8649042/126098933-e6a720b8-7899-4591-a8f3-8190e611cb8f.jpg)

**Comment by schmurrie** [comment]
Are you sure the temps in ha are not in Fahrenheit?

**Comment by antoniassiph** [comment]
@schmurrie it might be if you consider only values above 32, but no way it's 9F outside, it would be -12C, impossible where i live.
The sensor is reporting a 32C and 15C in less then 15 minutes interval. Even if it was Fahrenheit makes no sense such change in just 15min.

I noticed that Tuya API is reporting va_temperature 2 times with distinct values. From logs:
```
2021-07-19 19:05:32 DEBUG (Thread-4) [tuya iot] on_message: {'data': {'dataId': '---', 'devId': '---', 'productKey': '---', 'status': [{'code': 'va_temperature', '103': 1789, 't': '1626732331', 'value': 1789}]}, 'protocol': 4, 'pv': '2.0', 'sign': '---', 't': 1626732331}
[....]
2021-07-19 19:05:32 DEBUG (Thread-4) [tuya iot] on_message: {'data': {'dataId': '---', 'devId': '---', 'productKey': '---', 'status': [{'101': 3964, 'code': 'va_temperature', 't': '1626732331', 'value': 3964}]}, 'protocol': 4, 'pv': '2.0', 'sign': '---', 't': 1626732331}
```
2 messagens. 2 temperature updates. More then 20C diff.
