### ISSUE TITLE
Tuya entity status isn't updating in Home Assistant after value change

### ISSUE THREAD

**Issue by dudenell** [tuya/tuya-home-assistant#172]
**Describe the bug**
Attempting to turn on or off a smart plug causes the device to change states (turning it on turns the device on, or turning it on turns the device off), however, the status of the entity (sensor?) isn't updating in home assistant.

**Expected behavior**
Expect the entity values to update in Home Assistant after a entity status change

**Screenshots**
https://imgur.com/ONcv39S

**Home Assistant Version**
2021.7.3

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**

    {
      "active_time": 1596057740,
      "biz_type": 0,
      "category": "cz",
      "create_time": 1596057740,
      "icon": "smart/icon/1472027848_0.png",
      "id": "463503204c11ae18befb",
      "ip": "99.140.240.81",
      "lat": "35.7173054",
      "local_key": "94e6fa506d71dddc",
      "lon": "-78.8945779",
      "model": "",
      "name": "String Lights",
      "online": true,
      "owner_id": "8640663",
      "product_id": "JhM6hwy3OlyY2dNE",
      "product_name": "Geeni OW101 Plug",
      "status": [
        {
          "code": "switch",
          "value": true
        },
        {
          "code": "countdown_1",
          "value": 0
        }
      ],
      "sub": false,
      "time_zone": "-05:00",
      "uid": "az1567136851929HMQBS",
      "update_time": 1625199423,
      "uuid": "463503204c11ae18befb"
    }

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**

2021-07-18 23:01:23 DEBUG (SyncWorker_0) [tuya iot] Request: method = GET, url = https://openapi.tuyaus.com/v1.0/devices/463503204c11ae18befb/specifications, params = None, body = None, headers = {'client_id': 'wchsded4aq4g2r4ly1bu', 'sign': 'E74F8885171C8D3A2A30FB7B5221B97512F0B24C987FC6B16BC12C3C03641461', 'sign_method': 'HMAC-SHA256', 'access_token': 'b3a5db9e9e06fb54855f3982da5d8808', 't': '1626663683391', 'lang': 'en'}
2021-07-18 23:01:23 DEBUG (SyncWorker_0) [tuya iot] Response: {
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1626663683453
}

**Additional context**

2021-07-18 23:06:24 DEBUG (SyncWorker_0) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/devices/463503204c11ae18befb/commands, params = None, body = {'commands': [{'code': 'switch', 'value': False}]}, headers = {'client_id': 'wchsded4aq4g2r4ly1bu', 'sign': '404FAEEE7E3C98CE9C89ACA4D6B714A0C3E8614CB308D6879D37B02CDC3DEACA', 'sign_method': 'HMAC-SHA256', 'access_token': 'b3a5db9e9e06fb54855f3982da5d8808', 't': '1626663984441', 'lang': 'en'}
2021-07-18 23:06:24 DEBUG (SyncWorker_0) [tuya iot] Response: {
  "result": true,
  "success": true,
  "t": 1626663984747
}

Currently running v1.3.2

**Comment by tsutsuku** [comment]
https://github.com/tuya/tuya-home-assistant/discussions/113

**Comment by iotinkognito** [comment]
I have subscribed to that API as mentioned in #113 but the issue has reappeared, it was fixed temporarily until I updated to 1.3.1

**Comment by hung2kgithub** [comment]
newer install 1.3.2, my smart plug on/off status is up-to-date in home assistant but all the power comsumption function doesn't.
It work only if i stay opening smartlife app's electric tab

**Comment by dudenell** [comment]
> #113

@tsutsuku Could you please provide either a URL let me know how I can access that page from the Tuya menus on the https://iot.tuya.com/ website?

Thank you

**Comment by dudenell** [comment]
I got it to work after subscribing to device status notifications. I believe I had to go to cloud -> cloud products -> search for device status notification and then checkout.

Then I had to development clicked on my project name, clicked on API up top. Then clicked on "go to authorize"

**Comment by iotinkognito** [comment]
I have subscribed to that API as mentioned in #113 but the issue has reappeared, it was fixed temporarily until I updated to 1.3.2

**Comment by philhzss** [comment]
> I have subscribed to that API as mentioned in #113 but the issue has reappeared, it was fixed temporarily until I updated to 1.3.2

Same here

**Comment by iotinkognito** [comment]
@tsutsuku I know this is closed, should we open another?

**Comment by philhzss** [comment]
@tsutsuku  if it helps, I noticed that clicking on the integrations page on tuya v2 and clicking "reload integration" seems to update all the sensors. So it really is an issue with the integration it seems?
