### ISSUE TITLE
Bluetooth Tracker [Smart Finder L110]

### ISSUE THREAD

**Issue by Sthopeless** [tuya/tuya-home-assistant#179]
<img src="https://user-images.githubusercontent.com/6695214/126331427-fa0d02c7-8530-4837-9d6f-a0ababec5e29.jpg" width="50%" height="50%">

**Device normal info**

- [Smart Finder (bought it here on Aliexpress)](https://bit.ly/2UZnxXW)
- L110

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
```
  "result": {
    "devices": [
      {
        "active_time": 1626782465,
        "biz_type": 18,
        "category": "fdq",
        "create_time": 1626782465,
        "icon": "smart/icon/ay1559644257945KhRCD/d8e1aa628957a07a5540bd6a57dc435b.png",
        "id": "bf9d5cm0wfmpbxe8",
        "ip": "",
        "lat": "",
        "local_key": "",
        "lon": "6.1874407",
        "name": "Smart Finder",
        "online": false,
        "owner_id": "",
        "product_id": "vubjhhhk",
        "product_name": "蓝牙防丢器",
        "status": [],
        "sub": false,
        "time_zone": "+02:00",
        "uid": "xxxxxx",
        "update_time": 1626782465,
        "uuid": ""
      }
    ],
    "last_id": "1626782465",
    "total": 1
  },
  "success": true,
  "t": 1626782466555
}
```

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
```
2021-07-20 14:01:06 DEBUG (Thread-5) [tuya iot] Response: {
  "code": 2009,
  "msg": "not support this device",
  "success": false,
  "t": 1626782466595
}
```

Possible to add support for these bluetooth trackers?

**Comment by tsutsuku** [comment]
You can create a ticket in the Tuya service console with your device specifications.
https://service.console.tuya.com/8/2/create?step=3&id=01030503&source=content_feedback.

**Comment by Sthopeless** [comment]
@tsutsuku asking for support though ticket is for all new integrations or only specific to this device? 

so i know how to processed in the future, thanks

**Comment by tsutsuku** [comment]
Asking for standardized your device.
