### ISSUE TITLE
The device TH06WB3S doesn't appear in the integration list

### ISSUE THREAD

**Issue by ppmt** [tuya/tuya-home-assistant#180]
The device doesn't appear in the integration list

**Device normal info**
- Brand: Unknown
- Device : TH06WB3S

**Device info :
{
"active_time": 1626265437,
"biz_type": 0,
"category": "wsdcg",
"create_time": 1626264871,
"icon": "smart/icon/ay1525749833414yotNt/60d869bb20b0e1b0f0347a9fd8781a3c.png",
"id": "aaaaaaaaaaaaaaaaaaa",
"ip": "x.x.x.x",
"lat": "52.9122209",
"local_key": "xxxxxxxxxxxxxxxxxxxx",
"lon": "-2.5112325",
"name": "T & H Sensor",
"online": true,
"owner_id": "20072370",
"product_id": "7akwzwfwhukkdsib",
"product_name": "T & H Sensor",
"status": [],
"sub": false,
"time_zone": "+01:00",
"uid": "eu160665988157967ebe",
"update_time": 1626777622,
"uuid": "e5983878b64128f6"
},

**Device specifications : 
[tuya iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/devices/aaaaaaaaaaaaaaaaaaa/specifications, params = None, body = None, headers = {'client_id': 'xxxxxxxxxxxxxxx', 'sign': 'xxxxxxxxxxxxxxxxxxxxxxx', 'sign_method': 'HMAC-SHA256', 'access_token': '6f72514f51e78c8984f1cc2bb5e8207e', 't': '1626787675689', 'lang': 'en'}
2021-07-20 14:27:55 DEBUG (SyncWorker_5) [tuya iot] Response: {
"code": 2009,
"msg": "not support this device",
"success": false,
"t": 1626787675728
}

**Comment by tsutsuku** [comment]
You can create a ticket in the Tuya service console with your device specifications.
https://service.console.tuya.com/8/2/create?step=3&id=01030503&source=content_feedback.

**Comment by ppmt** [comment]
Ok will do that. 
I am sorry I thought I was meant to do it in the github page.

**Comment by ppmt** [comment]
Ok after writing a ticket with Tuya as asked they have now asked me to ask you :)
But something change. After deleting and reinstalling the integration I can now see the device in the list but it doesn't update.
If I restart HA it will get the value but will not update it after that.
Should I close this ticket and write another or should I modify this one?

**Comment by tsutsuku** [comment]
https://github.com/tuya/tuya-home-assistant/discussions/113

**Comment by ppmt** [comment]
Thanks a lot @tsutsuku . That fixed my problem
