### ISSUE TITLE
Category cz double gpo power sockets don't expose their energy monitoring. 

### ISSUE THREAD

**Issue by iotinkognito** [tuya/tuya-home-assistant#188]
CZ category double gpo power sockets don't expose their energy monitoring. 

![image](https://user-images.githubusercontent.com/82223761/126645196-0f66979a-43bd-44ea-9867-3068d132e99d.png)

**Comment by tsutsuku** [comment]
Can you provide your device specifications?

**Comment by iotinkognito** [comment]
This is from the API
    "biz_type": 18,
    "category": "cz",
    "model": "双色LED Double Power Point",
    "product_id": "nma7ep8nzegzwyjh",
    "product_name": "Double Power Point",

Also similar to which also needs to be resolved. 
    "biz_type": 18,
    "category": "kg",
    "product_id": "5pyb1usxij5kzs47",
    "product_name": "Brilliant Smart Glass Wall Switch 2 Gang",

**Comment by iotinkognito** [comment]
Similar/Same as #250

**Comment by iotinkognito** [comment]
@tsutsuku is there an update on these?

**Comment by iotinkognito** [comment]
They are working 1.5.0
