### ISSUE TITLE
Tuya v2 v1.4.0 not work

### ISSUE THREAD

**Issue by Gferretta** [tuya/tuya-home-assistant#196]
Hi
After update received this error

All worked fine with previous version 

![Screenshot_20210723-092152_Home Assistant.jpg](https://user-images.githubusercontent.com/65413059/126782298-1862602a-acb4-4aef-a905-0eb793ad783a.jpg)

I was to modify something for this version?

EDIT:
I'm reinstall previous version v1.3.2 and work again. 🤷‍♂️
Is not a problem with my tuya account.

**Comment by FelipeMartini** [comment]
Just reinstall the tuyav2 again and relogin you must set the login credentials again

**Comment by Gferretta** [comment]
> Just reinstall the tuyav2 again and relogin you must set the login credentials again 

Relogin where? In HA or in tuya?

Thanks

**Comment by strasharo** [comment]
Same here after upgrade:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/tuya_v2/__init__.py:81
Integration: Tuya v2 (documentation)
First occurred: 15:22:02 (1 occurrences)
Last logged: 15:22:02

Error setting up entry <scrubbed>@gmail.com for tuya_v2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/tuya_v2/__init__.py", line 290, in async_setup_entry
    success = await _init_tuya_sdk(hass, entry)
  File "/config/custom_components/tuya_v2/__init__.py", line 118, in _init_tuya_sdk
    entry_data = entry_decrypt(hass, entry, init_entry_data)
  File "/config/custom_components/tuya_v2/__init__.py", line 81, in entry_decrypt
    if init_entry_data[XOR_KEY]:
KeyError: '00oo00'

**Comment by strasharo** [comment]
> > Just reinstall the tuyav2 again and relogin you must set the login credentials again
> 
> Relogin where? In HA or in tuya?
> 
> Thanks

Delete the integration from integrations (not HACS) and configure it again, that fixed it for me.

**Comment by Gferretta** [comment]
> > > Just reinstall the tuyav2 again and relogin you must set the login credentials again
> > 
> > 
> > Relogin where? In HA or in tuya?
> > Thanks
> 
> Delete the integration from Integrations (not HACS) and configure it again, that fixed it for me.

Worked.
Thank you.
Regards

**Comment by strasharo** [comment]
I guess it makes sense to keep it open, unless that was expected behavior. :)
