### ISSUE TITLE
Thermostat with 1 device but no entity linked

### ISSUE THREAD

**Issue by flayy73** [tuya/tuya-home-assistant#197]
**Describe the bug**
Thermostat discovered as device but no entity linked

**Expected behavior**
If I connect the thermostat with the Tuya V1  I have 1 device and 1 entity while with the Tuya V2 I only have 1 device.

**Screenshots**
![Immagine 2021-07-23 175404](https://user-images.githubusercontent.com/86019626/126808750-0aa242eb-d45d-40af-a10e-0d7678db2c3a.jpg)

**Home Assistant Version**
- Home Assistant 2021.7.3

**Device info 
2021-07-23 18:00:15 ERROR (Thread-4) [tuya iot] error while get mqtt config
2021-07-23 18:00:15 DEBUG (SyncWorker_4) [tuya iot] Response: {
  "result": [
    {
      "active_time": 1627054271,
      "biz_type": 18,
      "category": "wk",
      "create_time": 1622049142,
      "icon": "smart/icon/15264583415nnlzwfs1qd2wqz6i937op3nmi_0.png",
      "id": "878608518caab5e502f5",
      "ip": "93.57.247.25",
      "lat": "44.29031100581927",
      "local_key": "8fead701da5caa95",
      "lon": "11.86798677812269",
      "model": "",
      "name": "thermostat",
      "online": true,
      "owner_id": "31398235",
      "product_id": "IAYz2WK1th0cMLmL",
      "product_name": "thermostat",
      "status": [
        {
          "code": "switch",
          "value": true
        },
        {
          "code": "temp_set",
          "value": 38
        },
        {
          "code": "upper_temp",
          "value": 51
        },
        {
          "code": "eco",
          "value": false
        },
        {
          "code": "child_lock",
          "value": false
        }
      ],
      "sub": false,
      "time_zone": "+01:00",
      "uid": "eu1622048325139MI5IB",
      "update_time": 1627054277,
      "uuid": "878608518caab5e502f5"
    }
  ],
  "success": true,
  "t": 1627056015457

**Device specifications 
2021-07-23 18:00:15 DEBUG (SyncWorker_4) [tuya iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/devices/878608518caab5e502f5/specifications, params = None, body = None, headers = {'client_id': 'xxxxxxxxxx', 'sign': 'xxxxxxxxx', 'sign_method': 'HMAC-SHA256', 'access_token': 'xxxxxxxxxxx', 't': 'xxxxxxxxxxx', 'lang': 'en'}
2021-07-23 18:00:15 DEBUG (SyncWorker_4) [tuya iot] Response: {
  "result": {
    "category": "wk",
    "functions": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "child_lock",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":10,\"max\":70,\"scale\":1,\"step\":5}"
      },
      {
        "code": "eco",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "upper_temp",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":5}"
      }
    ],
    "status": [
      {
        "code": "eco",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":10,\"max\":70,\"scale\":1,\"step\":5}"
      },
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "child_lock",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "upper_temp",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":5}"
      }
    ]
  },
  "success": true,
  "t": 1627056015521
}

**Comment by tannisroot** [comment]
Your access token and secret are displayed to everyone
