### ISSUE TITLE
Integration unable to start after install of V1.4

### ISSUE THREAD

**Issue by johnjoemorgan** [tuya/tuya-home-assistant#202]
**Describe the bug**
Integration unable to start after install of V1.4

**Expected behavior**
Integration should start as in previous versions

**Error Log**
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/tuya_v2/__init__.py:81
Integration: Tuya v2 (documentation)
First occurred: 11:13:39 (1 occurrences)
Last logged: 11:13:39

Error setting up entry XXX@YYY.COM for tuya_v2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/tuya_v2/__init__.py", line 290, in async_setup_entry
    success = await _init_tuya_sdk(hass, entry)
  File "/config/custom_components/tuya_v2/__init__.py", line 118, in _init_tuya_sdk
    entry_data = entry_decrypt(hass, entry, init_entry_data)
  File "/config/custom_components/tuya_v2/__init__.py", line 81, in entry_decrypt
    if init_entry_data[XOR_KEY]:
KeyError: '00oo00'

**Home Assistant Version**
2021.7.4

**Comment by escobarin3** [comment]
Same issue... Had to update... then delete from the integrations... then add integratrion and add login details again... working now.

**Comment by johnjoemorgan** [comment]
@escobarin3 Thanks - I have reverted back to get control of the devices (light switches and extension cable w/ USB).  I'll wait on the uninstall/reinstall in case the guys need me to retry the upgrade

**Comment by fahimi73** [comment]
I'm facing the same issue. Have to delete and configure all over again.

**Comment by motisht** [comment]
Same issue for me - See this message in the log :
Logger: libav.tcp
Source: components/stream/worker.py:213
First occurred: 9:47:26 AM (16 occurrences)
Last logged: 10:07:28 AM

Connection to tcp://xxxxxx.duckdns.org:554?timeout=5000000 failed: Connection refused

**Comment by kond111** [comment]
How I know that My integration is Upgraded to 1.4 version?

**Comment by johnjoemorgan** [comment]
@kond111 If HACS is not giving you an update message then you are at 1.4

**Comment by Zeunas** [comment]
Same issue here, had to revert back to previous version.

**Comment by thetastate1** [comment]
Same issue for 1.4. Rolled back to 1.3.2 which worked fine. I'm not keen on deleting and reinstalling as I had random authentication issues when installing.

**Comment by johnjoemorgan** [comment]
Seems some people are having problems reverting to 1.3.2 

https://github.com/tuya/tuya-home-assistant/issues/219

**Comment by tsutsuku** [comment]
Try v1.4.1.

**Comment by johnjoemorgan** [comment]
@tsutsuku Thanks will do as soon as the rollout hits my device.  Thank you

**Comment by johnjoemorgan** [comment]
@tsutsuku Update appeared a while back and update pushed through.  On restart I get the "Failed to start" error and this from the logs:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/tuya_v2/__init__.py:102
Integration: Tuya v2 (documentation)
First occurred: 13:01:38 (1 occurrences)
Last logged: 13:01:38

Error setting up entry aws@castelnuovo.io for tuya_v2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/tuya_v2/__init__.py", line 290, in async_setup_entry
    success = await _init_tuya_sdk(hass, entry)
  File "/config/custom_components/tuya_v2/__init__.py", line 118, in _init_tuya_sdk
    entry_data = entry_decrypt(hass, entry, init_entry_data)
  File "/config/custom_components/tuya_v2/__init__.py", line 102, in entry_decrypt
    user_input_encrpt = aes.cbc_encrypt(cbc_key, cbc_iv, json.dumps(init_entry_data))
  File "/usr/local/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type mappingproxy is not JSON serializable

**Comment by johnjoemorgan** [comment]
@tsutsuku Uninstalled and reinstalled V1.4.1 - no problems after restart.  All devices were discovered as before.  No reconfiguration necessary.

Would be interested to know what broke the upgrade for future reference but I'd say that this ticket is closed.

**Comment by johnjoemorgan** [comment]
Resolved with resolution of 1) make full back up of HA. 2) uninstall and reinstall Tuyu V2
