### ISSUE TITLE
Still Internet is used For Local Tuya V2

### ISSUE THREAD

**Issue by kond111** [tuya/tuya-home-assistant#204]
**Describe the bug**
When I Shut Down the internet at home, Still I cannot Manage my Local Tuya v2 devices from HA.

**Expected behavior**
Expected that I should be able to turn off and on My lights Normally even if the internet is down.

**Screenshots**
Logger: tuyaha.tuyaapi
Source: /usr/local/lib/python3.9/site-packages/tuyaha/tuyaapi.py:251
First occurred: 11:42:27 AM (1 occurrences)
Last logged: 11:42:27 AM

request error, error code is HTTPSConnectionPool(host='px1.tuyaeu.com', port=443): Max retries exceeded with url: /homeassistant/skill (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xacc7cad8>: Failed to establish a new connection: [Errno -3] Try again')), device 5480608010521c491772

**Home Assistant Version**
- Home Assistant 2021.7.3

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
like this:
{
  "result": {
    "active_time": 1621252019,
    "biz_type": 18,
    "category": "dj",
    "create_time": 1602786464,
    "icon": "smart/icon/ay1519551146071pEnBd/1590981157da68e109ecd.png",
    "id": "5060001024a160016788",
    "ip": "156.213.98.29",
    "lat": "30.03587864508801",
    "local_key": "0eb956a91195aec3",
    "lon": "31.515388446502",
    "model": "costdown，8285",
    "name": "Office-3",
    "online": true,
    "owner_id": "27781434",
    "product_id": "mki13ie507rlry4r",
    "product_name": "WB4-D",
    "status": [
      {
        "code": "switch_led",
        "value": true
      },
      {
        "code": "work_mode",
        "value": "colour"
      },
      {
        "code": "bright_value_v2",
        "value": 1000
      },
      {
        "code": "colour_data_v2",
        "value": "{\"h\":120,\"s\":1000,\"v\":1000}"
      },
      {
        "code": "scene_data_v2",
        "value": "{\"scene_num\":4,\"scene_units\":[{\"bright\":500,\"h\":0,\"s\":0,\"temperature\":1000,\"unit_change_mode\":\"static\",\"unit_gradient_duration\":13,\"unit_switch_duration\":14,\"v\":0}]}"
      },
      {
        "code": "countdown_1",
        "value": 0
      },
      {
        "code": "music_data",
        "value": ""
      },
      {
        "code": "control_data",
        "value": ""
      }
    ],
    "sub": false,
    "time_zone": "+02:00",
    "uid": "eu1616156182124EoieM",
    "update_time": 1626968618,
    "uuid": "5060001024a160016788"
  },
  "success": true,
  "t": 1627119569364

**Additional context**
Add any other context or logs about the problem here.

**Comment by tungmeister** [comment]
I don't believe the integration supports local control yet but It has been stated that it'll be implemented at some point.

**Comment by kond111** [comment]
@tungmeister so what is the benefit for stating local Tuya v1 and v2 then if i don't have real local integration?

**Comment by tungmeister** [comment]
This is officially developed and maintained by Tuya Devs and will be bringing local support eventually - it's still early days.

**Comment by DavidFFerreira** [comment]
YOU SHOULD READ! this is a web api based solution....off course its not locally! dumbass
