### ISSUE TITLE
Don't print sensitive info in the log

### ISSUE THREAD

**Issue by tannisroot** [tuya/tuya-home-assistant#207]
Almost every issue with the log provided contains user's access token and secret, as well as user's IP and exact latitude/longitude, potentially allowing anyone access to the user's devices.
This is VERY dangerous and should not be the default behavior for the logger.
I suggest that Tuya immediately releases an update that removes all personal information from the logs and removes all issues that have contain this info, since Github saves revisions when you edit issues.

**Comment by tannisroot** [comment]
Some of the info isn't even sanitized in your own issue template, pointing to some building in Hangzhou.

**Comment by tsutsuku** [comment]
You are welcome to create a PR.

**Comment by tsutsuku** [comment]
We will fix this in next main release.

**Comment by tsutsuku** [comment]
Fixed in v1.5.0.
