### ISSUE TITLE
No entity for the BHT-002 thermostat

### ISSUE THREAD

**Issue by tannisroot** [tuya/tuya-home-assistant#208]
**Describe the bug**
Despise the thermostat showing up in the devices, there is no associated entity for it.

**Expected behavior**
I expect the device to have an associated thermostat entity for it

**Home Assistant Version**
2021.7.4

**Device info

{
"active_time": 1627130661,
"biz_type": 18,
"category": "wk",
"create_time": 1627130661,
"icon": "smart/icon/15264583415nnlzwfs1qd2wqz6i937op3nmi_0.png",
"id": "SANITIZED",
"ip": "SANITIZED",
"lat": "",
"local_key": "SANITIZED",
"lon": "",
"name": "thermostat",
"online": true,
"owner_id": "20702531",
"product_id": "IAYz2WK1th0cMLmL",
"product_name": "thermostat",
"status": [
{
"code": "switch",
"value": true
},
{
"code": "temp_set",
"value": 53
},
{
"code": "upper_temp",
"value": 57
},
{
"code": "eco",
"value": false
},
{
"code": "child_lock",
"value": false
}
],
"sub": false,
"time_zone": "+03:00",
"uid": "SANITIZED",
"update_time": 1627138051,
"uuid": "SANITIZED"
}
],
"success": true,
"t": 1627143756628
}

**Device specifications

2021-07-24 19:22:36 DEBUG (SyncWorker_4) [tuya iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/devices/SANITIZED/specifications, params = None, body = None, headers = {'client_id': 'SANITIZED', 'sign': 'SANITIZED', 'sign_method': 'HMAC-SHA256', 'access_token': 'SANITIZED', 't': '1627143756673', 'lang': 'en'}
2021-07-24 19:22:36 DEBUG (SyncWorker_4) [tuya iot] Response: {
"result": {
"category": "wk",
"functions": [
{
""statuscode": "switch",
"type": "Boolean",
"values": "{}"
},
{
"code": "child_lock",
"type": "Boolean",
"values": "{}"
},
{
"code": "temp_set",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":10,\"max\":70,\"scale\":1,\"step\":5}"
},
{
"code": "eco",
"type": "Boolean",
"values": "{}"
},
{
"code": "upper_temp",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":5}"
}
],
"status": [
{
"code": "eco",
"type": "Boolean",
"values": "{}"
},
{
"code": "temp_set",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":10,\"max\":70,\"scale\":1,\"step\":5}"
},
{
"code": "switch",
"type": "Boolean",
"values": "{}"
},
{
"code": "child_lock",
"type": "Boolean",
"values": "{}"
},
{
"code": "upper_temp",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":5}"
}
]
},
"success": true,
"t": 1627143756814
}

**Comment by lammy666** [comment]
I have the exactly the same symptoms on my BHT-002's.  let me know if you want any further info in the future.

**Comment by lgmim** [comment]
Home Assistant Version
2021.8.7

Tuya V2
1.5.0

Product ID: IAYz2WK1th0cMLmL

Same behavior here - devices recognized from account and added as thermostat, but no controls in the thermostat entities.
Only one temperature and its wrong.

![изображение](https://user-images.githubusercontent.com/16715721/130079203-63436603-cccd-4736-9b9c-43452e6ba4dd.png)
