### ISSUE TITLE
Model：BW-SPF1 WiFi Pet Fountain Led Version/UV Version

### ISSUE THREAD

**Issue by robertbigk** [tuya/tuya-home-assistant#23]
Hi i try add this Fountain 

By Smart Life detect switch on/off 
but no uv/light

Is possible to add this to a home assistant?

Codes from IOT

{
  "result": [
    {
      "code": "switch",
      "value": true
    },
    {
      "code": "uv",
      "value": false
    }
  ],
  "success": true,
  "t": 1624557282603
}

{
  "result": {
    "active_time": 1624532307,
    "biz_type": 18,
    "category": "cwysj",
    "create_time": 1624532307,
    "icon": "smart/icon/ay1506337792739cXrIR/53d4d09e6737c1fc9926e1dfbeb555ef.jpg",
    "id": "4737134140f5203638ab",
    "ip": 
    "lat": "52.0794936",
    "local_key": 
    "lon": "21.0107744",
    "name": "BW-SPF1",
    "online": true,
    "owner_id": "18127768",
    "product_id": "1x7uxzc0itrepcrb",
    "product_name": "BW-SPF1 UV Version",
    "status": [
      {
        "code": "switch",
        "value": true
      },
      {
        "code": "uv",
        "value": false
      }
    ],
    "sub": false,
    "time_zone": "+01:00",
    "uid": "eu1604020388098rm3hC",
    "update_time": 1624556702,
    "uuid": "4737134140f5203638ab"
  },
  "success": true,
  "t": 1624557319962
}

Is any chance for integration?

**Comment by tsutsuku** [comment]
@robertbigk 
We will consider it in the next release.

**Comment by tsutsuku** [comment]
@robertbigk The pet water feeder is supported in v1.3.

**Comment by robertbigk** [comment]
Hi can You explane me what is 1.3? how and what I need update?

**Comment by robertbigk** [comment]
Work thx allot!!!

**Comment by gijsje** [comment]
Can we also have a low water level warning?

**Comment by robertbigk** [comment]
Superb if possible sure:)

**Comment by robertbigk** [comment]
Or You ask me? yes i got this kind warning in original app

**Comment by gijsje** [comment]
No i was wondering if we could also get the low level sensor in to ha

**Comment by gonzasmts** [comment]
Is it possible to have the low level sensor available in HA?
