### ISSUE TITLE
Blitzwolf BW-CLT1 ceiling light

### ISSUE THREAD

**Issue by mezzomazzo** [tuya/tuya-home-assistant#238]
**Device normal info**
- Blitzwolf
- BW-CLT1

with localtuya i can turn on the mainlight or the color-ledring.
This ceiling light has two lights integrated,

{
"active_time": 1625909301,
"biz_type": 0,
"category": "xdd",
"create_time": 1625909301,
"icon": "smart/icon/ay1530625888062OnLeq/f32d529926d6ab62ec8fea68431be6df.png",
      "id": "aaaaaaaaaaa",
      "ip": "xxxxxxxxxxxxxxxx",
      "lat": "xxxxxxxxxxxxxxxx",
      "local_key": "xxxxxxxxxxxxx",
      "lon": "xxxxxxxxxxxxxxx",
"name": "Ceiling lighting 2",
"online": false,
"owner_id": "12564235",
"product_id": "ngmwvkmhsplwuasr",
"product_name": "Ceiling lighting",
"status": [
{
"code": "switch_led",
"value": true
},
{
"code": "work_mode",
"value": "white"
},
{
"code": "bright_value",
"value": 120
},
{
"code": "temp_value",
"value": 250
},
{
"code": "colour_data",
"value": "{\"h\":229,\"s\":259,\"v\":1000}"
},
{
"code": "countdown",
"value": 0
}
],
"sub": false,
"time_zone": "+02:00",
"uid": "xxxxxxxxxxxxxxxxxx",
"update_time": 1627252323,
"uuid": "xxxxxxxxxxxxxxxx"
},

2021-07-26 15:32:55 DEBUG (SyncWorker_3) [tuya iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/devices/bf6cc4d42f7505a9d91cqu/specifications, params = None, body = None, headers = {'client_id': 'xxxxxxxxxxxxxxxxx', 'sign': 'xxxxxxxxxxxxxx', 'sign_method': 'HMAC-SHA256', 'access_token': '8d02c157fdf643d2f4f915978b106ca0', 't': '1627306375860', 'lang': 'en'}
2021-07-26 15:32:55 DEBUG (SyncWorker_3) [tuya iot] Response: {
"result": {
"category": "xdd",
"functions": [
{
"code": "switch_led",
"type": "Boolean",
"values": "{}"
},
{
"code": "work_mode",
"type": "Enum",
"values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"
},
{
"code": "bright_value",
"type": "Integer",
"values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
},
{
"code": "temp_value",
"type": "Integer",
"values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
},
{
"code": "colour_data",
"type": "Json",
"values": "{}"
},
{
"code": "countdown",
"type": "Integer",
"values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
},
{
"code": "music_data",
"type": "String",
"values": "{\"maxlen\":255}"
},
{
"code": "control_data",
"type": "String",
"values": "{\"maxlen\":255}"
}
],
"status": [
{
"code": "switch_led",
"type": "Boolean",
"values": "{}"
},
{
"code": "work_mode",
"type": "Enum",
"values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"
},
{
"code": "bright_value",
"type": "Integer",
"values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
},
{
"code": "temp_value",
"type": "Integer",
"values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
},
{
"code": "colour_data",
"type": "Json",
"values": "{}"
},
{
"code": "countdown",
"type": "Integer",
"values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
}
]
},
"success": true,
"t": 1627306375805
}

**Comment by mezzomazzo** [comment]
was already requested

**Comment by djsnho** [comment]
Mind sharing your localtuya config for the BW-CLT1 ?

**Comment by djsnho** [comment]
@mezzomazzo A little bit offtopic, but do you mind sharing  your localtuya config for the BW-CLT1 ?
