### ISSUE TITLE
New device Smart Energy Meter support

### ISSUE THREAD

**Issue by skynetua** [tuya/tuya-home-assistant#257]
**Device normal info**
- Zemismart 
- ZMAi-90

**Device info**
  "result": [
    {
      "active_time": 1622728475,
      "biz_type": 0,
      "category": "zndb",
      "create_time": 1617444785,
      "icon": "smart/icon/ay1536897190133VVeLx/b9439bd86d7954663fe187f367c5a54b.jpg",
      "id": "xxxxx",
      "ip": "xxxxx",
      "lat": "xxxxx",
      "local_key": "xxxxxx",
      "lon": "xxxxxx",
      "model": "ZM-wi-Fi -电表",
      "name": "WiFi Smart Meter",
      "online": true,
      "owner_id": "xxxxxx",
      "product_id": "nzexeqam9qulajbf",
      "product_name": "",
      "status": [
        {
          "code": "forward_energy_total",
          "value": 58155
        },
        {
          "code": "phase_a",
          "value": "{\"electricCurrent\":0.786,\"power\":0.165,\"voltage\":233.0}"
        },
        {
          "code": "switch",
          "value": true
        },
        {
          "code": "alarm_set_2",
          "value": "[{\"alarmCode\":\"overcurrent\",\"doAction\":false,\"threshold\":\"60\"},{\"alarmCode\":\"ammeter_overvoltage\",\"doAction\":false,\"threshold\":\"264\"},{\"alarmCode\":\"under_voltage\",\"doAction\":false,\"threshold\":\"150\"}]"
        },
        {
          "code": "meter_id",
          "value": "111111111111"
        }

**Device specifications **
  "result": {
    "category": "zndb",
    "functions": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "alarm_set_2",
        "type": "Json",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "forward_energy_total",
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "phase_a",
        "type": "Json",
        "values": "{}"
      },
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "alarm_set_2",
        "type": "Json",
        "values": "{}"
      },
      {
        "code": "meter_id",
        "type": "String",
        "values": "{\"maxlen\":255}"
      }
    ]
  },

**Comment by skynetua** [comment]
I'm working on contributing this and almost everything is done. I need suggestion for the following thing - device reports current, power and voltage as a single json string for each phase, like: "value": "{"electricCurrent":0.786,"power":0.165,"voltage":233.0}"

Is it better to parse values and split them for each separate sensor or leave it as is in single one?

**Comment by tsutsuku** [comment]
I think it is better to split them for each separate sensor.
