### ISSUE TITLE
Pir sensor not updating

### ISSUE THREAD

**Issue by cassidy-gidall** [tuya/tuya-home-assistant#271]
HA will only say 'detected' constantly and won't update, whether there is motion or not. I have already authorised the API for device status notification.

It's also strange that in the tuya developers pages, the device is showing as a qt device but in the HA logs it shows up as a pir type device

**Device normal info**
- Mirabella genio
- Motion sensor

**Device info

{
"active_time": 1627454636,
"biz_type": 18,
"category": "pir",
"create_time": 1627454636,
"icon": "smart/icon/1531813512w71nvvv9wkm_0.jpg",
"id": "**",
"ip": "**",
"lat": "**",
"local_key": "**",
"lon": "153.3060885",
"name": "Garage motion sensor",
"online": true,
"owner_id": "10881494",
"product_id": "p0y7ucexietpcqlq",
"product_name": "",
"status": [
{
"code": "pir",
"value": "none"
},
{
"code": "battery_percentage",
"value": 0
},
{
"code": "temper_alarm",
"value": true
}
],
"sub": false,
"time_zone": "+10:00",
"uid": "eu1583293755009s4rt0",
"update_time": 1627457962,
"uuid": "**"
},

**Device specifications

2021-07-30 10:11:31 DEBUG (SyncWorker_2) [tuya iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/devices/**/specifications, params = None, body = None, headers = {'client_id': '**', sign:'**', 'sign_method': 'HMAC-SHA256', 'access_token': '**', 't': '1627603891806', 'lang': 'en'}
2021-07-30 10:11:32 DEBUG (SyncWorker_2) [tuya iot] Response: {
"result": {
"category": "pir",
"functions": [],
"status": [
{
"code": "battery_percentage",
"type": "Integer",
"values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":10}"
},
{
"code": "pir",
"type": "Enum",
"values": "{\"range\":[\"pir\",\"none\"]}"
},
{
"code": "temper_alarm",
"type": "Boolean",
"values": "{}"
}
]

**Comment by alexreddy78** [comment]
Still same issue for 2 weeks already #144 and #57 :(

**Comment by iotinkognito** [comment]
Same issues as #140 #57 #119 #57 #144 #271 #262

**Comment by balouken** [comment]
Same problem here. Sensor says always: "detected".
I think the sensor never send a "not detected" state.

    {
      "active_time": 1572281072,
      "biz_type": 18,
      "category": "pir",
      "create_time": 1572281072,
      "icon": "smart/icon/1552636253kn1yhumf49q_0.png",
      "id": "21020567bcddc240b216",
      "ip": "81.247.35.50",
      "lat": "50.99019201294315",
      "local_key": "58090aec7c9a177c",
      "lon": "3.926078192254227",
      "model": "SW81",
      "name": "Inkomhal",
      "online": true,
      "owner_id": "6683215",
      "product_id": "mokkxfsfgsgkahao",
      "product_name": "Smart motion sensor",
      "status": [
        {
          "code": "pir",
          "value": "pir"
        },
        {
          "code": "battery_state",
          "value": "high"
        }
      ],
      "sub": false,
      "time_zone": "+01:00",
      "uid": "eu1571870843514GcoiG",
      "update_time": 1627842226,
      "uuid": "21020567bcddc240b216"
    },

**Comment by cassidy-gidall** [comment]
Works correctly since v1.5
