### ISSUE TITLE
I cant get integration working in Australia?

### ISSUE THREAD

**Issue by tsutsuku** [tuya/tuya-home-assistant#290]
### Discussed in https://github.com/tuya/tuya-home-assistant/discussions/289

<div type='discussions-op-text'>

<sup>Originally posted by **jay-oswald** August  2, 2021</sup>
I cant get the integration working in Australia, its installed, and I can "Add Integration" in HA. but it wont accept my details.

I'm thinking its because my zone is Australia, and on the Tuya IoT Platform there's no availability zone for Australia or anything close. I've selected every zone, but its not working. Not sure if there's anything I've missed.

My Username/password works properly for the v1 integration, and I'm defiantly copying and pasting the Client ID and Secret properly from the IoT platform, not sure what else I could be missing.</div>

**Comment by xbmcnut** [comment]
See here https://github.com/tuya/tuya-home-assistant/issues/272#issuecomment-890659429
