### ISSUE TITLE
Light bulbs turn on or off but then HA status shows old state

### ISSUE THREAD

**Issue by mikesellt** [tuya/tuya-home-assistant#300]
I have several bulbs that I use in the Smart Life app.  They are all Merkury-branded bulbs.  Some of them are dimmable, some of them are just on/off, and some of them are rgbw.  When I change the state from on to off (or vice versa), the bulb responds, but then about a second later, the state in HA shows the old state (if the bulb was off, and I turned it on, it will show off again - and vice versa).  If I try and turn the bulb back off, I have to switch it back to on and then of again quickly for it to work.

**Comment by mikesellt** [comment]
I discovered that it appears Paul Hibbert may also be having this issue, though he didn't mention it on his video).  I noticed in the video below that after he turns on the light, the indicator in Home Assistant (on his phone) turns off even though the light stays on.  This is at about 6:12 in the video. https://youtu.be/cd4aUJJl_s0

**Comment by tsutsuku** [comment]
Tried https://github.com/tuya/tuya-home-assistant/discussions/113

**Comment by mikesellt** [comment]
> Tried https://github.com/tuya/tuya-home-assistant/discussions/113?

I did.  At least, I think I did.  I tried to enable it.  I went to my store and purchased the free trial of that feature, and it says it was added, but it never showed up in the list under services.  If I try and enable/install it again, I end up with two in the purchased list, but still none in the master service list as pictured in #113.  Thanks for the reply.  I am sure I am missing a step somewhere if that isn't showing up.

**Comment by mikesellt** [comment]
Looks like adding the notification service fixed it.

**Comment by sc0rp10n101** [comment]
Same issue since latest update to home assistant. Prior to that it all worked fine apartt from one ZigBee bulb. Now all the bulbs are doing it.

**Comment by tsutsuku** [comment]
So issue solved? I will close the issue.

**Comment by sc0rp10n101** [comment]
I reinstalled Tuya V2 in HACS following the upgrade of home assistant and this seems to have corrected the problem incase anyone comes across this problem with the notifications already turned on.
