### ISSUE TITLE
Can't turn on/off smart curtain switch backlight

### ISSUE THREAD

**Issue by jlavazquez** [tuya/tuya-home-assistant#306]
**Describe the bug**
I can't turn on/off the backlight of my tuya "curtain smart switch". I don't find any entity to control this. 

**Expected behavior**
I would like control this backlight to, for example, shutdown automatically every night at 10pm

**Screenshots**
Backlight on/off smartlife

![image](https://user-images.githubusercontent.com/87710103/128248807-4df126bd-9ee7-48f1-9f49-31d46152b034.png)

**Home Assistant Version**
core-2021.7.4
supervisor-2021.06.8
Home Assistant OS 6.1

**Device info
like this:
{
"active_time": 1599479916,
"biz_type": 18,
"category": "clkg",
"create_time": 1598973307,
"icon": "smart/icon/ay1535193862006vs1if/ed36c56ce51ad2c4cfc82728ad57d049.png",
"id": "xxxxxxxxxxxxxx",
"ip": "xxxxxxxxxxxxxx",
"lat": "41.4558465",
"local_key": "xxxxxxxxxxxxxx",
"lon": "2.2584015",
"name": "Persiana PC",
"online": true,
"owner_id": "6497291",
"product_id": "3rpavvenp7rsxjsb",
"product_name": "Smart Curtain Switch",
"status": [
{
"code": "control",
"value": "stop"
}
],
"sub": false,
"time_zone": "+01:00",
"uid": "eu1571086020532FrKpF",
"update_time": 1627216110,
"uuid": "xxxxxxxxxxxxxx"
},

**Device specifications
}
2021-07-27 23:19:21 DEBUG (SyncWorker_1) [tuya iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/devices/15546007500291b968ac/specifications, params = None, body = None, headers = {'client_id': 'xxxxxxxxxxxxxx', 'sign': 'xxxxxxxxxxxxxx', 'sign_method': 'HMAC-SHA256', 'access_token': 'a7a17b1b3add5ab9bd830328f212652d', 't': '1627420761326', 'lang': 'en'}
2021-07-27 23:19:21 DEBUG (SyncWorker_1) [tuya iot] Response: {
"result": {
"category": "clkg",
"functions": [
{
"code": "control",
"type": "Enum",
"values": "{"range":["open","stop","close"]}"
}
],
"status": [
{
"code": "control",
"type": "Enum",
"values": "{"range":["open","stop","close"]}"
}
]
},
"success": true,
"t": 1627420761404
}

**Comment by tsutsuku** [comment]
First, DP code "light" is not in your device specification, so you need to create a ticket to standardize your device.
https://service.console.tuya.com/8/2/create?step=3&id=01030503&source=content_feedback.

Then, we can develop a driver to support this.

**Comment by jlavazquez** [comment]
Done. ticket ID T20210807000008

**Comment by jlavazquez** [comment]
Hello. I have response from Tuya's service support. 

"Hello, I have applied for standardized processing for you, and it is expected that the processing will be completed in one working day"

![image](https://user-images.githubusercontent.com/87710103/129729553-c8f82f8a-badd-48da-9d44-01c58b228706.png)

**Comment by jlavazquez** [comment]
@tsutsuku How did this issue end? Was it possible to develop a controller to support it?

**Comment by frenck** [comment]
This has been developed and is part of the Home Assistant core integration.

![image](https://user-images.githubusercontent.com/195327/151136999-8174a904-2da6-421e-bd0f-8ac3065a2297.png)

**Comment by jlavazquez** [comment]
Doesn't the code you are talking about refer to the position of the blind?

In this thread I am talking about the light emitted by the switch itself (also called backlight). From Smart Life it can be turned on/off but from Home Assistant it cannot be turned on/off.

**Comment by frenck** [comment]
> Doesn't the code you are talking about refer to the position of the blind?

There is no such thing, and currently there isn't a possibility to implement such a thing either.

**Comment by frenck** [comment]
Upstream PR to add support for it: <https://github.com/home-assistant/core/pull/64961>

**Comment by jlavazquez** [comment]
O.K. Thank you for the feedback. Tell me if you need to check or do something I can help.

**Comment by frenck** [comment]
> Tell me if you need to check or do something I can help.

Upstream change has been approved, it will be part of Home Assistant Core 2022.2. For which the beta starts today and the final release is next Wednesday.

**Comment by jlavazquez** [comment]
Ok! ty again! I just changed to beta channel

**Comment by frenck** [comment]
And, did it work? If so, we can close this issue :)

**Comment by jlavazquez** [comment]
Yes!!! Works perfect. Four new entities have appeared, one for each blind. And if I activate them, the back light turns on or off instantly!!!  Thank you and good job.  

![image](https://user-images.githubusercontent.com/87710103/151450392-7ae0866e-70a3-416c-8106-3612b70a109d.png)

**Comment by frenck** [comment]
Nice! Thanks for letting me know :) I'll close up the issue at this end in that case 👍
