### ISSUE TITLE
Temperature Sensor Not Showing Up

### ISSUE THREAD

**Issue by gumasanahome** [tuya/tuya-home-assistant#312]
**Device normal info**
- WF96D THERMOSTAT
- WF96D

**Device info 
{
  "result": {
    "active_time": 1628174506,
    "biz_type": 0,
    "category": "rs",
    "create_time": 1628161739,
    "icon": "smart/icon/ay1524831691838LKBMs/1599190391c86f5bf313c.jpg",
    "id": "1165088394b97e06a8e7",
    "ip": "",
    "lat": "",
    "local_key": "",
    "lon": "",
    "model": "WF96D",
    "name": "Boiler Thermostat",
    "online": true,
    "owner_id": "10955909",
    "product_id": "2j4zgjwtzm7ztytp",
    "product_name": "WF96D THERMOSTAT",
    "status": [
      {
        "code": "switch",
        "value": false
      },
      {
        "code": "temp_set",
        "value": 650
      },
      {
        "code": "temp_current",
        "value": 269
      }
    ],
    "sub": false,
    "time_zone": "+03:00",
    "uid": "eu1583592384817jGULJ",
    "update_time": 1628177921,
    "uuid": "1165088394b97e06a8e7"
  },
  "success": true,
  "t": 1628179388254
}

Description:
this is a mains powered din rail attachable thermostat with a temperature probe. it has the following functons
1. displays real time temperature readings
2. has a relay which truns on and off depending on the min and max temperature range settings
3. has an input range of min and max to send the user notifications which once reached alerts you

**Comment by nerdbenn** [comment]
dude remove your lot, lat, localkey, ip details

**Comment by gumasanahome** [comment]
thanks for bringing it to my attention
