### ISSUE TITLE
Lovelace control for "Curtain Switch" has the "open" control always disabled

### ISSUE THREAD

**Issue by LSDancer** [tuya/tuya-home-assistant#313]
**Describe the bug**
Curtain switch (category clkg) is added using discovery to tuya_2. "product_id": "237mvcniwsrjgqhl". "close" and "stop" controls can be activated from Lovelace UI. But "open" button is always disabled. The "open" control can still be activated from a script directly.

**Expected behavior**
All three controls of the curtain swtich can be activated from the Lovelace UI.

**Screenshots**
the "up" button is always disabled, on all pages where the control is added to
![image](https://user-images.githubusercontent.com/12732814/128384841-7099fa60-4347-4bc9-9455-30113c40fef4.png)

**Home Assistant Version**
- 2021.8.0

**Device info** 

 {
      "active_time": 1626198247,
      "biz_type": 18,
      "category": "clkg",
      "create_time": 1626198247,
      "icon": "smart/icon/ay1496289297888GkNKB/4d93d2723eff19b097faf1702612e760.png",
      "id": "xxxxxxxxxx",
      "ip": "xxxxxxxxxxxx",
      "lat": "xxxxxxxxxxxx",
      "local_key": "xxxxxxxxxxxxx",
      "lon": "xxxxxxxxxxxxxx",
      "name": "Curtain switch",
      "online": true,
      "owner_id": "xxxxxxxxxxxxxxxx",
      "product_id": "237mvcniwsrjgqhl",
      "product_name": "Curtain switch",
      "status": [
        {
          "code": "control",
          "value": "stop"
        }
      ],
      "sub": false,
      "time_zone": "+01:00",
      "uid": "xxxxxxxxxxxx",
      "update_time": 1628115922,
      "uuid": "xxxxxxxxxxxxxxxxx"
    }

**Device specifications** 

[tuya iot] Response: {
  "result": {
    "category": "clkg",
    "functions": [
      {
        "code": "control",
        "type": "Enum",
        "values": "{\"range\":[\"open\",\"stop\",\"close\"]}"
      }
    ],
    "status": [
      {
        "code": "control",
        "type": "Enum",
        "values": "{\"range\":[\"open\",\"stop\",\"close\"]}"
      }
    ]
  },
  "success": true,
  "t": 1628178720088
}

**Additional context**

The switch is fully operational from the "Smart Life" app

**Comment by Steve2017** [comment]
In the integration configuration, is there an option to reverse the percentage opening? (a tickbox - 0-100). It might be misreporting its position and think it is fully open and so only offers a "close" command.

**Comment by dondi101** [comment]
Same here, but , if I create automation for opening shutter.
Then the shutter is opening after running the automation.

**Comment by patrik-malina** [comment]
same with me. i think @Steve2017 is right about invert option. Smart Life app has invert option, also localtuya has it.

**Comment by LSDancer** [comment]
i dont have an invert option and my device does not support percentage control, it is a simple open/close/stop device. And there is no "invert" options neither in the Smart Life app  nor in the Home Assistant...

**Comment by Steve2017** [comment]
> same with me. i think @Steve2017 is right about invert option. Smart Life app has invert option, also localtuya has it.

The invert in the app (Tuya or SmartLife) reverses the direction of motor travel. This is to allow the blind to open and close using the correct button. 

In TuyaLocal, the invert is just the way it reports its current position in the software. This has an effect on which direction arrow it makes active. If it thinks it is closed, it will only offer the open arrow, even though it might actually be open. That’s where the invert in HA makes a difference. 

It also effects where the blind stops when you order it to open to say 60%. Is it 60% closed or 60% open?

**Comment by tsutsuku** [comment]
Try v1.5.0.

**Comment by patrik-malina** [comment]
It's now fixed. Both buttons works as should, BUT positioning always stated on 100%. It works tho, but showing bad position.
Nice work anyway.
![Screenshot (128)](https://user-images.githubusercontent.com/73561855/129039284-81c96109-f483-461d-810d-d726a12edf4f.png)

**Comment by LSDancer** [comment]
it works with 1.5 for me, too (both up and down are active).
my device does not support positioning, thus i cannot comment on this.

thank you for fixing this!
