### ISSUE TITLE
i got Invalid authentication

### ISSUE THREAD

**Issue by yakovte** [tuya/tuya-home-assistant#32]
I do all the Install and when I go to my HA and add the Integration
![ss](https://user-images.githubusercontent.com/79398545/123979438-6456dc00-d9c9-11eb-84f1-5d25ec4e0061.png)
 i got Invalid authentication

**Comment by milandzuris** [comment]
me to

**Comment by novisys** [comment]
ME TO

**Comment by sthorley** [comment]
Same here. Europe availability Zone, region Australia.

**Comment by Nick-Adams-AU** [comment]
Could this have something to do with the signature changes required after 30 June? It seems to have broken pretty much all third-party API integrations.

https://developer.tuya.com/en/docs/iot/singnature?id=Ka43a5mtx1gsc

**Comment by tsutsuku** [comment]
@Nick-Adams-AU 
Tuya Integration v1.3 has updated the signing algorithm.
For move information, you can read the https://github.com/tuya/tuya-home-assistant/wiki/Tuya-Home-Assistant-Integration-Release-Notes

**Comment by Nick-Adams-AU** [comment]
Thanks @tsutsuku! That now works for me with this update.

**Comment by sthorley** [comment]
@tsutsuku I'm running v1.3 and I still get the invalid Authentication error.

**Comment by tsutsuku** [comment]
@sanshengshui According to the error code 2406, it seems your project is created before May 25.

**Comment by tsutsuku** [comment]
You need to create a new project on the tuya IoT platform.

**Comment by sthorley** [comment]
> According to the error code 2406, it seems your project is created before May 25.
This is 100% not possible. I signed up for Tuya IOT only earlier today after seeing he announcement on HomeAssistant Reddit.

>You need to create a new project on the tuya IoT platform.
I will attempt this and let you know how it goes.

**Comment by sthorley** [comment]
I have created a new project. Same 2406 error.

`2021-07-01 16:35:40 INFO (MainThread) [custom_components.tuya_v2.config_flow] TuyaConfigFlow.async_step_user start, is_import= None
2021-07-01 16:36:06 INFO (MainThread) [custom_components.tuya_v2.config_flow] TuyaConfigFlow.async_step_user start, is_import= {'password': 'PASSWORD', 'endpoint': 'https://openapi.tuyaeu.com', 'access_id': 'p4qXXXXXXXXXXdnt', 'access_secret': 'dffacdd97c0XXXXXXXXXX15b07c86', 'tuya_app_type': 'tuyaSmart', 'country_code': '61', 'username': 'xxx@sxxxy.xom'}
2021-07-01 16:36:06 INFO (SyncWorker_4) [custom_components.tuya_v2.config_flow] TuyaConfigFlow._try_login start, user_input: {'password': 'PASSWORD', 'endpoint': 'https://openapi.tuyaeu.com', 'access_id': 'p4qXXXXXXXXXXdnt', 'access_secret': 'dffacdd97c0XXXXXXXXXX15b07c86', 'tuya_app_type': 'tuyaSmart', 'country_code': '61', 'username': 'xxx@sxxxy.xom', 'tuya_project_type': 0}
2021-07-01 16:36:08 INFO (SyncWorker_4) [custom_components.tuya_v2.config_flow] TuyaConfigFlow._try_login finish, response:, {'code': 2406, 'msg': 'skill id invalid', 'success': False, 't': 16251XXXXX19}`

Could this issue be related to using the same email to login to TuyaIOT and Tuya Smart App?

**Comment by redlegoman** [comment]
> I have created a new project. Same 2406 error.

> Could this issue be related to using the same email to login to TuyaIOT and Tuya Smart App?

I wouldn't have thought so, I'm having the same issue and I have different IOT and App emails

**Comment by yakovte** [comment]
> @Nick-Adams-AU
> Tuya Integration v1.3 has updated the signing algorithm.
> For move information, you can read the https://github.com/tuya/tuya-home-assistant/wiki/Tuya-Home-Assistant-Integration-Release-Notes

After I update to V1.3 is work good tnx

**Comment by redlegoman** [comment]
> > @Nick-Adams-AU
> > Tuya Integration v1.3 has updated the signing algorithm.
> > For move information, you can read the https://github.com/tuya/tuya-home-assistant/wiki/Tuya-Home-Assistant-Integration-Release-Notes
> 
> After I update to V1.3 is work good tnx

This I think, was a report about the Beta V2 of the product, widely trumpeted by the Home Assistant team. I can't upgrade the Beta to V1.3 as I downloaded the custom_component this very day and installed it into Home Assistant.

**Comment by yakovte** [comment]
> > > @Nick-Adams-AU
> > > Tuya Integration v1.3 has updated the signing algorithm.
> > > For move information, you can read the https://github.com/tuya/tuya-home-assistant/wiki/Tuya-Home-Assistant-Integration-Release-Notes
> > 
> > 
> > After I update to V1.3 is work good tnx
> 
> This I think, was a report about the Beta V2 of the product, widely trumpeted by the Home Assistant team. I can't upgrade the Beta to V1.3 as I downloaded the custom_component this very day and installed it into Home Assistant.

uninstall and install again
and do a restart for HA

**Comment by redlegoman** [comment]
> uninstall and install again
> and do a restart for HA

did a git pull and restart, no change
did a remove and git clone, no change
