### ISSUE TITLE
Door/Windows Sensor (mcs) without data from battery  ** Solved **

### ISSUE THREAD

**Issue by Gferretta** [tuya/tuya-home-assistant#322]
Hi

What can be this problem?
Firmware?
Model?
Tuya driver?

Only appear the status (open/close)

Any way to fix it to view in HA?

Thanks

**Comment by Zeunas** [comment]
I bet that's because the sensor you have reports the battery level status as battery_value which is in voltage, whereas at the moment only sensors that report battery status as battery_percentage seem to work. I have two door sensors, one reports in percentage and shows it in HA and the other in voltage, which doesn't appear in HA.

I have tried to add it to sensors.py with no luck, can't make it work... Just hoping someone more knowledgeable will be able to.

**Comment by Gferretta** [comment]
> I bet that's because the sensor you have reports the battery level status as battery_value which is in voltage, whereas at the moment only sensors that report battery status as battery_percentage seem to work. I have two door sensors, one reports in percentage and shows it in HA and the other in voltage, which doesn't appear in HA.
> 
> I have tried to add it to sensors.py with no luck, can't make it work... Just hoping someone more knowledgeable will be able to.

The error is another

NO "battery" returned by Tuya

View this link where I'm posted returning message
 [](https://github.com/tuya/tuya-home-assistant/issues/37#issuecomment-872433712)

**Comment by Zeunas** [comment]
That's weird...Have you checked the tuya debug logs? Are you sure it's a mcs device? Forgot to mention that the one that shows the battery is a mcs device and the other one even thou it shows mcs device on the logs if I go to the tuya developer cloud it shows as "qt".

**Comment by Gferretta** [comment]
> That's weird...Have you checked the tuya debug logs? Are you sure it's a mcs device? Forgot to mention that the one that shows the battery is a mcs device and the other one even thou it shows mcs device on the logs if I go to the tuya developer cloud it shows as "qt".

This is result of API Explorer on tuya platform for "Door Window Sensor device":

{
"result": {
"active_time": 1625156459,
"biz_type": 0,
"category": "mcs",
"create_time": 1625147323,
"icon": "smart/icon/ay1525749833414yotNt/92722d1b64636ed1dfe3107187643324.jpg",
"id": ".....................1a8.......",
"ip": "181.0.XX.YYY",
"lat": "",
"local_key": ".........18...........",
"lon": "",
"name": "Puerta",
"online": true,
"owner_id": "..............7",
"product_id": ".....................54b9.....",
"product_name": "Contact Sensor",
"status": [
{
"code": "doorcontact_state",
"value": false
}
],
"sub": false,
"time_zone": "-03:00",
"uid": "...............",
"update_time": 1625156835,
"uuid": ".....................1a8......."
},
"success": true,
"t": 1625158456875
}

View that category is "mcs"

**Comment by tsutsuku** [comment]
Can you provide your product_id?

**Comment by Gferretta** [comment]
> Can you provide your product_id?

    "category": "mcs",
    "product_id": "ikfjwqdbpnh154b9",
    "product_name": "Contact Sensor",

**Comment by tsutsuku** [comment]
You can create a ticket in the Tuya service console with your device specifications.
https://service.console.tuya.com/8/2/create?step=3&id=01030503&source=content_feedback.

**Comment by Gferretta** [comment]
> You can create a ticket in the Tuya service console with your device specifications.
> https://service.console.tuya.com/8/2/create?step=3&id=01030503&source=content_feedback.

Ticket created
Thanks

**Comment by Gferretta** [comment]
> You can create a ticket in the Tuya service console with your device specifications.
> https://service.console.tuya.com/8/2/create?step=3&id=01030503&source=content_feedback.

Ready!    Thanks a lot.

{
  "result": {
    "category": "mcs",
    "functions": [],
    "status": [
      {
        "code": "doorcontact_state",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "battery_state",
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"middle\",\"high\"]}"
      }
    ]
  },
  "success": true,
  "t": 1628797946634
}
