### ISSUE TITLE
Pir motion sensor won’t update status

### ISSUE THREAD

**Issue by pbvdven** [tuya/tuya-home-assistant#324]
Bug LSC motion sensor won’t update from detected to not detected.
The device state in home assistant is always detected even when the sensor is offline.

expected behavior that the state is detected when motion is detected en when there is no motion the device state is not detected and when its offline the device state is not available.
{
      "active_time": 1607725325,
      "biz_type": 0,
      "category": "pir",
      "create_time": 1600852413,
      "icon": "smart/device_icon/eu1580835339988EOIFT/1600852976.846712.png",
      "id": "20401777500291cf9b2b",
      "ip": 
      "lat": 
      "local_key": "",
      "lon": "6.778513477809701",
      "name": "Portiek sensor",
      "online": true,
      "owner_id": "",
      "product_id": "wqz93nrdomectyoz",
      "product_name": "Smart PIR sensor",
      "status": [
        {
          "code": "pir",
          "value": "pir"
        },
        {
          "code": "battery_state",
          "value": "high"
        }
      ],
      "sub": false,
      "time_zone": "+01:00",
      "uid": "eu1580835339988EOIFT",
      "update_time": 1628370155,
      "uuid": "20401777500291cf9b2b"
    },

**Comment by iotinkognito** [comment]
Many similar issues open. #140 #144
