### ISSUE TITLE
Fan shows up without working speed settings and dummy entities

### ISSUE THREAD

**Issue by gvssr** [tuya/tuya-home-assistant#340]
**Describe the bug**
Tuya Fan entity (Duux Whisper Flex Ultimate) shows up in HA, however it shows up as three separate entities:

1. switch.xxx: a power on/off switch which is capable of turning the fan on and of (works)
2. fan.xxx: a fan entity which can turn the fan on/off, however the speed slider doesn’t do anything and isn’t correctly mapped. Speed can be adjusted using service calls, however.
3. light.xxx: light entity, no idea what this does

**Expected behavior**
A single fan entity would suffice, with at minimum: turn on/off, and correctly mapped and working speed slider (0-30). Even better would be the inclusion of additional features which are available in the Tuya app: modes (sleep, nature, normal), horizontal oscillation, vertical oscillation, set temperature, timer

**Screenshots**
Fan device with the three entities
![9885FC1B-AEED-41E4-A79B-D2053540A3AE](https://user-images.githubusercontent.com/61377476/129164170-a6a39fe3-dc86-4d41-8c91-b0fe7fe82bb0.jpeg)

Fan entity with incorrect and non-functioning speed slider
![4CBA1937-2FEE-4B52-BFA9-40510845B24B](https://user-images.githubusercontent.com/61377476/129164181-db9989a5-1bd0-4614-a94f-6b27060eabcc.jpeg)

Fan device in the Tuya app
![44286AB5-2DEB-4872-BE6A-49A3A3D640B9](https://user-images.githubusercontent.com/61377476/129164176-091221c0-af59-40c9-babe-65ecbf60502a.jpeg)

**Home Assistant Version**
2021.8.5

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
like this:

```
{
"active_time": 1628696958,
"biz_type": 0,
"category": "fs",
"create_time": 1628696958,
"icon": "smart/icon/001441070657466AAETE/a3de89a299843127e4d716cd35e5fd4e.png",
"id": "ebbc7c0bf2c73d0e33d7xp",
"ip": "***",
"lat": "***",
"local_key": "***",
"lon": "***",
"model": "DXCF14/15",
"name": "Whisper Flex Ultimate",
"online": true,
"owner_id": "34993017",
"product_id": "cjsa4k7tqbpuyq3l",
"product_name": "",
"status": [
{
"code": "switch",
"value": false
},
{
"code": "fan_speed_percent",
"value": 4
},
{
"code": "temp",
"value": 17
}
],
"sub": false,
"time_zone": "+02:00",
"uid": "***",
"update_time": 1628756444,
"uuid": "00588b1fb206c170"
}
```

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**

```
2021-08-12 10:31:12 DEBUG (SyncWorker_1) [tuya iot] Request: method = GET, url = https://openapi.tuyaus.com/v1.0/devices/ebbc7c0bf2c73d0e33d7xp/specifications, params = None, body = None, t = 1628757072250
2021-08-12 10:31:12 DEBUG (SyncWorker_1) [tuya iot] Response: {
"result": {
"category": "fs",
"functions": [
{
"code": "switch",
"type": "Boolean",
"values": "{}"
},
{
"code": "fan_speed_percent",
"type": "Integer",
"values": "{\"min\":\"1\",\"max\":\"30\",\"scale\":\"0\",\"step\":\"1\"}"
},
{
"code": "temp",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":\"17\",\"max\":\"28\",\"scale\":\"0\",\"step\":\"1\"}"
}
],
"status": [
{
"code": "switch",
"type": "Boolean",
"values": "{}"
},
{
"code": "fan_speed_percent",
"type": "Integer",
"values": "{\"min\":\"1\",\"max\":\"30\",\"scale\":\"0\",\"step\":\"1\"}"
},
{
"code": "temp",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":\"17\",\"max\":\"28\",\"scale\":\"0\",\"step\":\"1\"}"
}
]
},
"success": true,
"t": 1628757072417
}
```

**Additional context**
The cheaper version of this fan (Duux Whisper Flex Smart) showed up in the v1 version of tuya, this more expensive fan doesn’t work in v1 at all

**Comment by barrymossel** [comment]
Any news on this?

**Comment by gvssr** [comment]
Closing this at this repo is no longer maintained and it's been fixed in HA core
