### ISSUE TITLE
Tuya v2 1.5.0 devices offline

### ISSUE THREAD

**Issue by Docas09** [tuya/tuya-home-assistant#344]
As my apologies.
I need help.
Yesterday I upgraded to Tuya v2 1.5.0 and everything was working fine before the upgrade.
After update, all motion sensors and door are not recognized and go offline in the home assistant.
Some switches have also gone offline and those that are still online are extremely slow to respond.
Someone had this problem and how they solved it.
Thanks a lot for the help.

**Comment by CyberGrim** [comment]
I second this. I have two door sensors that previously worked and now the original "door" sensor is unavailable, and the new "doorcontact_state" sensor is extremely slow to respond (I haven't actually seen it change yet).

Cheers,

**Comment by Gferretta** [comment]
In my case, door sensor changed his name in HA after upgrade and appears New ones

Check this first

**Comment by CyberGrim** [comment]
Unfortunately, I did just that, the original sensor was called "room_door" and the new one, which was auto-created after the update, is called "room_doorcontact_state". The first is now unavailable and the second is always reporting as "closed", even when that's not the case.

**Comment by tsutsuku** [comment]
First Sorry for that happen.
In v1.4.2 binaray sensor unique_id is f"{super().unique_id}{self._type}". "self._type" is HA Device Class. But this will cause error "same unique_id" when two DP Code are the same "self._type", like DPCODE_TEMPER_ALRAM and DPCODE_PIR are the same HA Device Class which is DEVICE_CLASS_MOTION.
So we change unique_id to f"{super().unique_id}{self._code}" in v1.5.0 to solve this problem. But this will cause old entities are not recognized.

**Comment by Docas09** [comment]
> Primeiro, desculpe por isso acontecer.
> Na v1.4.2, o sensor binaray unique_id é f "{super (). Unique_id} {self._type}". "self._type" é uma classe de dispositivo HA. Mas isso causará o erro "mesmo unique_id" quando dois códigos DP são o mesmo "self._type", como DPCODE_TEMPER_ALRAM e DPCODE_PIR são a mesma classe de dispositivo HA que é DEVICE_CLASS_MOTION.
> Portanto, alteramos unique_id para f "{super (). Unique_id} {self._code}" na v1.5.0 para resolver este problema. Mas isso fará com que as entidades antigas não sejam reconhecidas.
> 
> O novo status do dispositivo de entidade de sensor não é atualizado é outro problema que não deveria acontecer. Você pode fornecer mais registros?

Thank you for the answer. After updating all IDs everything works fine.
I no longer have delay and lack of status.
Congratulations on the excellent work.
Thanks

**Comment by Docas09** [comment]
Thank you for the answer. After updating all IDs everything works fine.
I no longer have delay and lack of status.
Congratulations on the excellent work.
Thanks
