### ISSUE TITLE
BHT-002-GBLW thermostat cannot be operated and reports wrong data

### ISSUE THREAD

**Issue by michalpulda** [tuya/tuya-home-assistant#361]
**Describe the bug**
A thermostat is loaded to HA (device and entity), but is reporting completely wrong data (current and desired temperature) and cannot be operated -- desired temperature cannot be set; operation modes cannot be set.

I have two equal thermostats (one has the floor temperature sensor connected).

**Expected behavior**
A thermostat reports correct data and can be set using HA.

**Screenshots**
![image](https://user-images.githubusercontent.com/5116915/129492513-0adda3dd-048e-4d34-b9e3-f6000fd23d5e.png)
![image](https://user-images.githubusercontent.com/5116915/129492529-342ff890-02db-4a07-ac23-119f95df3623.png)

**Home Assistant Version**
- 2021.8.6, Home Assistant OS

**Device info**

**Thermostat 1**
`{
"active_time": 1585509754,
"biz_type": 0,
"category": "wk",
"create_time": 1584574572,
"icon": "smart/icon/15264583415nnlzwfs1qd2wqz6i937op3nmi_0.png",
"id": "40041254bcddc2403e8e",
"ip": "***",
"lat": "***",
"local_key": "***",
"lon": "***",
"model": "",
"name": "Termostat koupelna",
"online": true,
"owner_id": "11178045",
"product_id": "IAYz2WK1th0cMLmL",
"product_name": "thermostat",
"status": [
{
"code": "switch",
"value": false
},
{
"code": "temp_set",
"value": 30
},
{
"code": "upper_temp",
"value": 52
},
{
"code": "eco",
"value": false
},
{
"code": "child_lock",
"value": false
}
],
"sub": false,
"time_zone": "+01:00",
"uid": "***",
"update_time": 1628766018,
"uuid": "40041254bcddc2403e8e"
}`

**Thermostat 2**
`{
"active_time": 1594129616,
"biz_type": 0,
"category": "wk",
"create_time": 1594129616,
"icon": "smart/icon/15264583415nnlzwfs1qd2wqz6i937op3nmi_0.png",
"id": "40041254bcddc2403dc3",
"ip": "***",
"lat": "***",
"local_key": "***",
"lon": "***",
"model": "",
"name": "Termostat ložnice",
"online": true,
"owner_id": "11178045",
"product_id": "IAYz2WK1th0cMLmL",
"product_name": "thermostat",
"status": [
{
"code": "switch",
"value": false
},
{
"code": "temp_set",
"value": 40
},
{
"code": "upper_temp",
"value": 54
},
{
"code": "eco",
"value": false
},
{
"code": "child_lock",
"value": false
}
],
"sub": false,
"time_zone": "+01:00",
"uid": "***",
"update_time": 1627153308,
"uuid": "40041254bcddc2403dc3"
}`

**Device specifications**

**Thermostat 1**
`2021-08-15 22:35:44 DEBUG (SyncWorker_4) [tuya iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/devices/40041254bcddc2403e8e/specifications, params = None, body = None, t = 1629059744466
2021-08-15 22:35:44 DEBUG (SyncWorker_4) [tuya iot] Response: {
"result": {
"category": "wk",
"functions": [
{
"code": "switch",
"type": "Boolean",
"values": "{}"
},
{
"code": "child_lock",
"type": "Boolean",
"values": "{}"
},
{
"code": "temp_set",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":10,\"max\":70,\"scale\":1,\"step\":5}"
},
{
"code": "eco",
"type": "Boolean",
"values": "{}"
},
{
"code": "upper_temp",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":5}"
}
],
"status": [
{
"code": "eco",
"type": "Boolean",
"values": "{}"
},
{
"code": "temp_set",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":10,\"max\":70,\"scale\":1,\"step\":5}"
},
{
"code": "switch",
"type": "Boolean",
"values": "{}"
},
{
"code": "child_lock",
"type": "Boolean",
"values": "{}"
},
{
"code": "upper_temp",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":5}"
}
]
},
"success": true,
"t": 1629059744554
}`

**Thermostat 2**
`2021-08-15 22:35:44 DEBUG (SyncWorker_4) [tuya iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/devices/40041254bcddc2403dc3/specifications, params = None, body = None, t = 1629059744846
2021-08-15 22:35:44 DEBUG (SyncWorker_4) [tuya iot] Response: {
"result": {
"category": "wk",
"functions": [
{
"code": "switch",
"type": "Boolean",
"values": "{}"
},
{
"code": "child_lock",
"type": "Boolean",
"values": "{}"
},
{
"code": "temp_set",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":10,\"max\":70,\"scale\":1,\"step\":5}"
},
{
"code": "eco",
"type": "Boolean",
"values": "{}"
},
{
"code": "upper_temp",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":5}"
}
],
"status": [
{
"code": "eco",
"type": "Boolean",
"values": "{}"
},
{
"code": "temp_set",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":10,\"max\":70,\"scale\":1,\"step\":5}"
},
{
"code": "switch",
"type": "Boolean",
"values": "{}"
},
{
"code": "child_lock",
"type": "Boolean",
"values": "{}"
},
{
"code": "upper_temp",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":5}"
}
]
},
"success": true,
"t": 1629059744943
}`

**Additional Info**

These are the thermostats: BHT-002-GBLW https://www.aliexpress.com/item/32896579061.html

**Comment by tsutsuku** [comment]
Your device info lost "temp_current", so You should create a ticket in the Tuya service console with your device specifications to standardize it.
https://service.console.tuya.com/8/2/create?step=3&id=01030503&source=content_feedback.

**Comment by patrik-malina** [comment]
@tsutsuku 
In v1.5.0 Thermostat shows entities, but similar as Michal, don't have operation modes available.
Opened ticked on Tuya IoT.
Here is log file:

```
{
"active_time": 1605952059,
"biz_type": 18,
"category": "qn",
"create_time": 1605952059,
"icon": "smart/icon/ay1539244260287RY0l6/15591841423ee64e9437b.png",
"id": "bf40b9e3bb5c1f2e01wxjf",
"ip": "***",
"lat": "***",
"local_key": "***",
"lon": "***",
"model": "ETOP-HT",
"name": "Thermostat",
"online": true,
"owner_id": "17222907",
"product_id": "0yj3dopm2hu61ntu",
"product_name": "HeatingThermostat",
"status": [
{
"code": "switch",
"value": true
},
{
"code": "temp_set",
"value": 200
},
{
"code": "temp_current",
"value": 280
},
{
"code": "lock",
"value": false
}
],
"sub": false,
"time_zone": "+01:00",
"uid": "***",
"update_time": 1629055157,
"uuid": "555f2588c1709952"
},
```

**Comment by michalpulda** [comment]
> Your device info lost "temp_current", so You should create a ticket in the Tuya service console with your device specifications to standardize it.
> https://service.console.tuya.com/8/2/create?step=3&id=01030503&source=content_feedback.

Thanks for your reply. Where do I get the correct device specifications? The one I copy pasted from logs is missing the "temp_current" value, so I guess that cannot be used.

**Comment by tsutsuku** [comment]
@michalpulda Using the scale, you can check it for more detail.
https://developer.tuya.com/en/docs/iot/datatypedescription?id=K9i5ql2jo7j1k#title-2-Value%20constraint

**Comment by michalpulda** [comment]
@tsutsuku Thank you for the details. Would you know how to put together correct device specifications, then, please?

**Comment by tsutsuku** [comment]
After your ticket is done. The missing "temp_current" should in your device specifications.

**Comment by koforiko** [comment]
I've already seen what it is. I will keep trying. Thanks

**Comment by rafalg7** [comment]
I've raised ticket on Tuya IoT platform about missing current room temperature & floor temperature + incorrect scaling of the temperatures.
Both values (room + floor temp) seems to be reported by the device, but are not in the IoT API.

**Comment by rafalg7** [comment]
I've raised ticket on support center in Tuya to "standarize" it & engineer is saying that the scale & values used to set temperature are determined by vendor of the device when produced, so client's API should use correct values (e.g. transform it to the values accepted by device, in this case target temp / 5, so same solution would be needed as in old API - to set scaling on HA level...

Another cool thing that this thermostat have is floor temperature, which is nicely displayed & operated via Tuya Smart App, but floor temp is not available in API itself.

@tsutsuku - can you explain if possible, how standarization process works? What data is expected to be provided, to make it easier for Tuya engineers to proceed?

**Comment by rafalg7** [comment]
@michalpulda which method did you used to flash it? From which main+mcu fw version it worked?

**Comment by rafalg7** [comment]
short update, no conclusion with Tuya ticket, they won't do much in this matter.
Solved by flashing all my 18 thermostats with Tasmota & being controlled by MQTT - the struggle is over :)
