### ISSUE TITLE
Door sensor (mcs or qt?) not reporting battery status

### ISSUE THREAD

**Issue by Zeunas** [tuya/tuya-home-assistant#424]
**Describe the bug**
I have 2 door sensors (mcs) one has a second entity that reports battery % the other doesn't. 

**Expected behavior**
2nd door sensor to have a second entity for battery %

**Home Assistant Version**
- 2021.8.8

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
```
{
"active_time": 1618826065,
"biz_type": 18,
"category": "mcs",
"create_time": 1561395914,
"icon": "smart/product_icon/qt.png",
"id": "00112223807d3a2a2e39",
"ip": "***",
"lat": "***",
"local_key": "***",
"lon": "***",
"model": "",
"name": "Front door",
"online": true,
"owner_id": "4826775",
"product_id": "7by9ERqg60JA8wxA",
"product_name": "Door Sensor",
"status": [
{
"code": "doorcontact_state",
"value": false
},
{
"code": "battery_value",
"value": 73
}
],
"sub": false,
"time_zone": "+00:00",
"uid": "***",
"update_time": 1630081238,
"uuid": "00112223807d3a2a2e39"
},
```

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
```
2021-08-27 22:03:37 DEBUG (SyncWorker_4) [tuya iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/devices/00112223807d3a2a2e39/specifications, params = None, body = None, t = 1630098217319
2021-08-27 22:03:37 DEBUG (SyncWorker_4) [tuya iot] Response: {
"result": {
"category": "mcs",
"functions": [],
"status": [
{
"code": "doorcontact_state",
"type": "Boolean",
"values": "{}"
},
{
"code": "battery_value",
"type": "Integer",
"values": "{\"unit\":\"v\",\"min\":0,\"max\":1000,\"scale\":-2,\"step\":1}"
}
]
},
"success": true,
"t": 1630098217388
}
```

**Additional context**
A few notes:
- The door sensor that has the second entity for battery %, when debugging it on iot.tuya.com I can see that the DPCODE is `batter_percentage` however the second door sensor that doesn't report batter % has the DPCODE `battery_value`, which is OK but when setting it up under `sensor.py` on the tuya_2 folder like the below:

    `DPCODE_BATTERY_VALUE = "battery_value"`
```
    if DPCODE_BATTERY_VALUE in device.status:
                entities.append(
                    TuyaHaSensor(
                        device,
                        device_manager,
                        DEVICE_CLASS_BATTERY,
                        DPCODE_BATTERY_VALUE,
                        PERCENTAGE,
                    )
                )
```
It doesn't work, a second entity is created but just shows "unavailable"

- Also to point out when debugging the second door sensor (the one without the battery status) on iot.tuya.com the "Product Category" is set as "qt" however HA reports it as "mcs", which is quite bizarre but adding the "qt" category in `sensor.py` doesn't seem to change anything.

**Comment by tsutsuku** [comment]
battery_value is not supported in v1.5.0. But will be supported soon.
Can you try the master branch?

**Comment by Zeunas** [comment]
HI @tsutsuku tried the master branch but no cigar, I'll wait do be added no worries ;)

**Comment by frenck** [comment]
This has been addressed and added/fixed with the Home Assistant Core version of the integration and is pending release with Home Assistant 2021.11.
