### ISSUE TITLE
Cannot add smart radiator thermostat.

### ISSUE THREAD

**Issue by lbida** [tuya/tuya-home-assistant#429]
Hello
I bought smart radiator thermostat head and I cannot connect it to Home Assistant.
I can use it via SmartLife app, I can see it on tuya developer account and I get it on logs, but I cannot see it on Home Assistant integration.
Here is log:
> {
"active_time": 1630084942,
"biz_type": 18,
"category": "wkf",
"create_time": 1630084942,
"icon": "smart/icon/bay1590985471642quoi/7bf56ec7badbc505eec2356669a293ca.jpg",
"id": "***",
"ip": "***",
"lat": "***",
"local_key": "***",
"lon": "***",
"model": "",
"name": "Living room thermostat",
"node_id": "***",
"online": true,
"owner_id": "***",
"product_id": "***",
"product_name": "Thermostat Valve",
"status": [
{
"code": "mode",
"value": "manual"
},
{
"code": "temp_set",
"value": 5
},
{
"code": "temp_current",
"value": 220
},
{
"code": "switch_rapid",
"value": false
},
{
"code": "countdown_rapid",
"value": 0
},
{
"code": "work_state",
"value": "closed"
},
{
"code": "window_check",
"value": true
},
{
"code": "window_state",
"value": "opened"
},
{
"code": "child_lock",
"value": false
},
{
"code": "battery_percentage",
"value": 100
}
],
"sub": true,
"time_zone": "+02:00",
"uid": "***",
"update_time": 1630096421,
"uuid": "***"
},

**Comment by GNious** [comment]
Basically same, Home Assistant 2021.12.7, Tuya device type "wkf" (Radiator Thermostat) doesn't appear to be supported.

In my case the device is a, "Moes TRV ZigBee 3.0 Tuya New Radiator Actuator Valve."

**Comment by frenck** [comment]
Yesterday, Home Assistant 2022.2 was released and it contains a new diagnostic tool.

There is now a "Download Diagnostics" button on each Tuya device on the device page. Clicking that button will download diagnostics information for that specific device. Drag the downloaded file into this issue.

This will help us learn about your device and provide details for implementing/adding support.

Thanks!

**Comment by GNious** [comment]
As i understand your request, see below. 

[tuya-bd55f52f469b64fdd51acf0acddf2623-Bel Thermostat -4d502bb1f7eb563fbd80b9e9390479cf.json.txt](https://github.com/tuya/tuya-home-assistant/files/8104313/tuya-bd55f52f469b64fdd51acf0acddf2623-Bel.Thermostat.-4d502bb1f7eb563fbd80b9e9390479cf.json.txt)
