### ISSUE TITLE
Orion Grid Connect SMART Security Contact Sensor Does not appear in Home Assistant

### ISSUE THREAD

**Issue by dcwilli** [tuya/tuya-home-assistant#437]
**Device normal info**
- Orion Grid Connect SMART Security Contact Sensor
- Model: SWSO6HA 
- Issue: Does not appear in Home Assistant

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
like this:
{
      "active_time": 1630669735,
      "biz_type": 18,
      "category": "mc",
      "create_time": 1630663079,
      "icon": "smart/icon/ay1536534747810ekKBj/62f7c0fc52607574799a8bf1a3e9dca3.png",
      "id": "64305102e8db84c76923",
      "ip": "***",
      "lat": "***",
      "local_key": "***",
      "lon": "***",
      "model": "SWS06HA",
      "name": "Laundry Door Wi-Fi Contact Sensor",
      "online": true,
      "owner_id": "2761739",
      "product_id": "vorytkc6j7lqvgvx",
      "product_name": "",
      "status": [
        {
          "code": "doorcontact_state",
          "value": true
        }
      ],
      "sub": false,
      "time_zone": "+10:00",
      "uid": "***",
      "update_time": 1630669995,
      "uuid": "64305102e8db84c76923"
    },

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
Same device's id, like this:
2021-09-03 22:01:26 DEBUG (MainThread) [tuya iot] start
2021-09-03 22:01:26 DEBUG (Thread-5) [tuya iot] Request: method = POST, url = https://openapi.tuyaeu.com/v1.0/iot-03/open-hub/access-config, params = None, body = {'uid': '***', 'link_id': '***', 'link_type': 'mqtt', 'topics': 'device', 'msg_encrypted_version': '1.0'}, t = 1630670486421 
2021-09-03 22:01:26 DEBUG (SyncWorker_4) [tuya iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/users/eu15452257318457LSkh/devices, params = None, body = None, t = 1630670486427 
2021-09-03 22:01:26 DEBUG (Thread-5) [tuya iot] Response: {
  "result": {
    "client_id": "***",
    "expire_time": 7200,
    "password": "***",
    "sink_topic": {
      "device": "cloud/token/out/{device_id}"
    },
    "source_topic": {
      "device": "cloud/token/in/db176e44819e2dd1c012cca724b4f5d9"
    },
    "url": "ssl://m1.tuyaeu.com:8883",
    "username": "cloud_db176e44819e2dd1c012cca724b4f5d9"
  },
  "success": true,
  "t": 1630670486685
}
2021-09-03 22:01:26 DEBUG (Thread-5) [tuya iot] connecting ssl://m1.tuyaeu.com:8883
2021-09-03 22:01:27 DEBUG (Thread-5) [tuya iot] _on_log: Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=b'cloud_7c593107ee74f96124cd1ab0f261c796'
2021-09-03 22:01:28 DEBUG (Thread-6) [tuya iot] _on_log: Received CONNACK (0, 0)
2021-09-03 22:01:28 DEBUG (Thread-6) [tuya iot] connect flags->{'session present': 0}, rc->0
2021-09-03 22:01:28 DEBUG (Thread-6) [tuya iot] _on_log: Sending SUBSCRIBE (d0, m1) [(b'cloud/token/in/db176e44819e2dd1c012cca724b4f5d9', 0)]
2021-09-03 22:01:28 DEBUG (Thread-6) [tuya iot] _on_log: Received SUBACK
2021-09-03 22:01:28 DEBUG (Thread-6) [tuya iot] _on_subscribe: 1
2021-09-03 22:01:29 DEBUG (SyncWorker_4) [tuya iot] Response: {

**Comment by dcwilli** [comment]
UPDATE:
Got it to work:

Added:
![image](https://user-images.githubusercontent.com/55827604/132015973-66e38596-bb3c-4957-a18c-08221588e180.png)
to sensor.py
and "mc" to TUYA_SUPPORT_TYPE in sensor.py

**Comment by dcwilli** [comment]
The new update has not added these devices. Can anyone help. These devices are now "unavailable" with the new update

**Comment by sEdsKi** [comment]
Got one of these into HA that I have owed for over a year. Went and bought more to put on entry doors. The new ones are pingable, and are in the Tuya IoT Platform, but they just don't show up as newly discovered devices in the LocalTuya Integration. Tried adding manually but get 'Cannot connect to device. Verify that address is correct and try again.'

**Comment by johnmacfadyen** [comment]
I believe this device has the wrong product category set on it. It reports as MC but returns the same data as the MCS product category. I was able to get it working by changing the control instruction mode in the Tuya IOT platform. After that it would report the door state correctly. 

To get the battery status and tamper switch working I had to modify the sensor.py and binary_sensor.py files in the Tuya component and install it as a custom component in HA. I don't really know any python so muddled my way through to get it working so it's quite messy but happy to share the code if anyone wants it. 

![image](https://user-images.githubusercontent.com/32566829/211147137-4c10e25c-73ca-470b-bf78-9c967abd766a.png)


@sEdsKi I had the same issue with mine this week which led me back to trying to get it working with the official Tuya integration.

**Comment by mateushirose** [comment]
> I believe this device has the wrong product category set on it. It reports as MC but returns the same data as the MCS product category. I was able to get it working by changing the control instruction mode in the Tuya IOT platform. After that it would report the door state correctly.
> 
> To get the battery status and tamper switch working I had to modify the sensor.py and binary_sensor.py files in the Tuya component and install it as a custom component in HA. I don't really know any python so muddled my way through to get it working so it's quite messy but happy to share the code if anyone wants it.
> 
> ![image](https://user-images.githubusercontent.com/32566829/211147137-4c10e25c-73ca-470b-bf78-9c967abd766a.png)
> 
> @sEdsKi I had the same issue with mine this week which led me back to trying to get it working with the official Tuya integration.

Hi. How did you manage to do that? I have exactly same devices, but some are has MC prod. cat and some has MCS
