### ISSUE TITLE
Add device: circuit breaker

### ISSUE THREAD

**Issue by WildeRNS** [tuya/tuya-home-assistant#45]
Please add support for device, purchased here: 
https://a.aliexpress.com/_AmEcRR

**Device info:
{
      "active_time": 1621338539,
      "biz_type": 18,
      "category": "dlq",
      "create_time": 1621338539,
      "icon": "smart/icon/bay1591839287906taVN/267162108e2f97cf9ddf39067b4eae7a.png",
      "id": "bf5b2e5690617d4c81lxse",
      "ip": "censored",
      "lat": "censored",
      "local_key": "censored",
      "lon": "23.5329977",
      "model": "",
      "name": "Kitchen Breaker",
      "online": true,
      "owner_id": "12366373",
      "product_id": "ntwmuj82anq1l92i",
      "product_name": "Breaker",
      "status": [
        {
          "code": "total_forward_energy",
          "value": 330
        },
        {
          "code": "phase_a",
          "value": "CPIAAAAAAAcAAA=="
        },
        {
          "code": "phase_b",
          "value": "AAAAAAAAAAAAAA=="
        },
        {
          "code": "phase_c",
          "value": "AAAAAAAAAAAAAA=="
        },
        {
          "code": "switch",
          "value": true
        }
      ],
      "sub": false,
      "time_zone": "+03:00",
      "uid": "eu1589556857161CVwFG",
      "update_time": 1625250446,
      "uuid": "73a5daf4df7529f5"
    },

**Comment by WildeRNS** [comment]
![Screenshot_2021-07-04-18-17-27-644_com tuya smartlife](https://user-images.githubusercontent.com/1622732/124390429-43a5c380-dcf4-11eb-97c9-1bde3d09e7bc.jpg)
Thanks for adding support for breaker, but 8n Home Assistant I only see switch and total energy but not other parameters (see screenshot)

**Comment by WildeRNS** [comment]
Any news, when rest sensors will be available?

**Comment by skynetua** [comment]
@WildeRNS can you check is the following data still encrypted in latest version's logs?
```
"code": "phase_a",
"value": "CPIAAAAAAAcAAA=="
```
I believe I can add them in the same way as in #257

**Comment by WildeRNS** [comment]
> @WildeRNS can you check is the following data still encrypted in latest version's logs?
> 
> ```
> "code": "phase_a",
> "value": "CPIAAAAAAAcAAA=="
> ```
> 
> I believe I can add them in the same way as in #257

Will check it, maybe today or tomorrow and write you back.

**Comment by hermesonfg** [comment]
Hey how did u connect  ur socket or plug? I did on mine only shows on and
off .

Em qui., 29 de jul. de 2021 06:02, WildeRNS ***@***.***>
escreveu:

**Comment by WildeRNS** [comment]
> @WildeRNS can you check is the following data still encrypted in latest version's logs?
> 
> ```
> "code": "phase_a",
> "value": "CPIAAAAAAAcAAA=="
> ```
> 
> I believe I can add them in the same way as in #257

Still have:
` {
          "code": "phase_a",
          "value": "CUwAE4gABDMAAA=="`

**Comment by frenck** [comment]
Support for circuit breakers has been added and will be available in Home Assistant 2022.2 (already available as beta, feel free to join that!)

**Comment by hermesonfg** [comment]
How can I add it on my HA?????

**Comment by frenck** [comment]
@hermesonfg As I said in my response above, it will be part of Home Assistant 2022.2, which is expected to be released upcoming Wednesday.

**Comment by hermesonfg** [comment]
> @hermesonfg As I said in my response above, it will be part of Home Assistant 2022.2, which is expected to be released upcoming Wednesday.

thank you!!!! looking forward to it!!!
