### ISSUE TITLE
After adding integration no devices

### ISSUE THREAD

**Issue by bohanic** [tuya/tuya-home-assistant#478]
After Add integration to HA, fill  correct credintial it show no devices. In Tuya IoT Platform web page I have 13 devices.

I use Tuya app.

![Tuya v2 - problem 2](https://user-images.githubusercontent.com/90909465/133878732-5c982840-a950-4024-be0c-e4ff9d473e4e.JPG)
![Tuya v2 - problem 1](https://user-images.githubusercontent.com/90909465/133878735-4404759f-ff2d-4c18-822a-7acc6c4f5a09.JPG)
![Tuya v2 - problem 1b](https://user-images.githubusercontent.com/90909465/133878736-ede3c4f7-1bcd-4fc6-acad-cfa0c0219b93.JPG)
![Tuya v2 - problem 1c](https://user-images.githubusercontent.com/90909465/133878738-d5913e60-23b1-4449-8fea-ab4e70f6e409.JPG)

**Comment by Greglsh** [comment]
I have the same problem, I have 2 smart switches with power monitoring which show in the Tuya IoT platform, but no devices in HA.

**Comment by bohanic** [comment]
I have 10 wifi wall switches.
One Motion Sensor (with temperature and humidity)
One Doorbell
One switch braker

![Tuya v2 - problem devices list](https://user-images.githubusercontent.com/90909465/133886265-6583ae1a-e3a0-4d52-9453-cefe88214b8a.JPG)

In my cloud prject I have these services
![image](https://user-images.githubusercontent.com/90909465/133886291-7593fb7b-958d-4969-8f32-1c391b14af6c.png)

I tried many time to restart HA, create new cloud project, pair APP, but still that same. Everything goes good, but 0 devices a 0 entities.

What could I check?

**Comment by gmackean** [comment]
I have a similar symtom. In my case when I check the log file I have this error:

error while get mqtt config
10:25:28 AM – (ERROR) /srv/homeassistant/lib/python3.8/site-packages/tuya_iot/openmq.py

debug log has...
2021-09-18 10:25:26 DEBUG (SyncWorker_1) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/iot-01/associated-users/actions/authorized-login...
...},
"success": true,
}

2021-09-18 10:25:27 DEBUG (MainThread) [tuya iot] start
2021-09-18 10:25:27 DEBUG (Thread-3) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/iot-03/open-hub/access-config....
2021-09-18 10:25:28 DEBUG (Thread-3) [tuya iot] Response: {
"code": xxxxxxxx,
"msg": "No permissions. This API is not subscribed.",
"success": false,
"t": xxxxxxxxxxxxx
}
2021-09-18 10:25:28 ERROR (Thread-3) [tuya iot] error while get mqtt config
...
the log file does show successful retrieval of the device list and the settings of my dimmer switch but they do not get returned to HA because of the error above.

**Comment by luanbon** [comment]
I am facing the same problem here.

**Comment by bohanic** [comment]
@gmackean I havent same log. Do you have Services subscribed in IoT Platform?
![image](https://user-images.githubusercontent.com/90909465/133917683-77e77558-c1cc-4f50-8546-80297705381e.png)

![image](https://user-images.githubusercontent.com/90909465/133917708-54fd53c0-5720-4b86-befb-4f144bb48665.png)

Only log info what i found is:

2021-09-18 12:27:56 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tuya_v2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Comment by gmackean** [comment]
@bohanic , thanks - I had missed "Device Status Notification". Had the other 5 but not that one. Now I still have no devices but I believe that is becausee the only device I have on my network at the moment is the Smart DImmer Switch which I see from another bug is not supported yet...

**Comment by mgsnell** [comment]
Not intending to beat a dead horse, but I thought maybe some additional info could help. Of course I have the same problem but the additional info is that all 7 of my devices show up in the Tuya integration and not in this one (Tuya  v2) don't know if that means anything or not but there it is.

**Comment by bohanic** [comment]
I really dont know what can be important. But on IoT platform I see all devices. There are correct status (online, offline). Also when I open device (for example Wifi Switch - 3 buttons) and I open Device Log I can see correct values:
![image](https://user-images.githubusercontent.com/90909465/133941046-b84bfa46-03f5-4486-b1c6-a8c2d89aa496.png)

But when I want to change status (on, off) on IoT platform I get error message:
![image](https://user-images.githubusercontent.com/90909465/133941120-f3ae6d90-2818-4248-9cd0-e1b0fca41ea0.png)

**Comment by some-guy-in-oz** [comment]
Have you tried adding and subscribing to the API specified here: 
https://github.com/tuya/tuya-home-assistant/issues/475#issuecomment-922245869

**Comment by gnosis3825** [comment]
For what it's worth, I have this problem as well. Integration installs in HA, Smart Life app connects to IoT platform, devices visible in platform, status updates in platform as changes to device are made in Smart Life app. devices are visible in old Tuya HA integration, but do not show in in Tuya 2. I am subscribed to Device Status Notification. I've removed and reinstalled from HA and created a different project in platform. None of those things fixed it. The Tuya 2 integration is simply not getting the data from the IoT platform.

**Comment by some-guy-in-oz** [comment]
What about "Device Log Query" API?  What error shows in your log?

**Comment by totalitarian** [comment]
> For what it's worth, I have this problem as well. Integration installs in HA, Smart Life app connects to IoT platform, devices visible in platform, status updates in platform as changes to device are made in Smart Life app. devices are visible in old Tuya HA integration, but do not show in in Tuya 2. I am subscribed to Device Status Notification. I've removed and reinstalled from HA and created a different project in platform. None of those things fixed it. The Tuya 2 integration is simply not getting the data from the IoT platform.
> 
> EDIT after @some-guy-in-oz questions:
> I see only these "tuya" related errors in the HA log -->
> 
> 1. 2021-09-20 12:55:54 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tuya_v2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
>    2)2021-09-20 16:06:33 ERROR (Thread-75) [tuya iot] Unexpected disconnection.1 (although I haven't seen this one since the restart (about 15 minutes ago))
> 
> Also:
> Since I can't see how to add an API to an existing IoT Platform Project, I created a new project and added the Device Log Query API (also subscribed) along with Device Status Notification [FYI - since my first project, the platform will not allow me to have all the other default APIs, are they needed?), re-added the app on the client and platform sides, can see the devices in the new project, deleted and re-added the integration in HA with the new platform project authorization and restarted HA, but still see no devices in the HA integration.

Exactly same issue here. Please help Tuya!

**Comment by totalitarian** [comment]
Noticed that i'm not actually subscribed to a lot of the apis

![image](https://user-images.githubusercontent.com/2385696/134219134-811d8b7c-c14a-4f3c-b689-8a1acd7fbe1e.png)

When I try to subscribe I get this message

![image](https://user-images.githubusercontent.com/2385696/134219215-304b2293-cb9f-4377-8e6e-7380bdaa2ecd.png)

**Comment by ravensergio** [comment]
> Noticed that i'm not actually subscribed to a lot of the apis
-----
I have the same issue! Supposedly when making a new project in the Cloud it should automatically subscribe you to the needed Services, but it did NOT in my case, and I cannot subscribe manually ( except Device Status Notification), I have the same message " ...you already purchased 1..." .

Also in HA logs i have:
................................
"result": {
"access_token": "***",
"expire_time": 7200,
"platform_url": "https://openapi.tuyaeu.com",
"refresh_token": "***",
"uid": "***"
},
"success": true,
"t": 1632246264971
}
..............and then.....................
2021-09-21 20:44:25 DEBUG (Thread-4) [tuya iot] connecting ssl://m1.tuyaeu.com:8883
2021-09-21 20:44:25 DEBUG (SyncWorker_2) [tuya iot] Response: {
"code": 28841101,
"msg": "No permissions. This API is not subscribed.",
"success": false,
....etc .............
Sorry I don't know what info I can put without my private information.

**Comment by totalitarian** [comment]
> > Noticed that i'm not actually subscribed to a lot of the apis
> 
> I have the same issue! Supposedly when making a new project in the Cloud it should automatically subscribe you to the needed Services, but it did NOT in my case, and I cannot subscribe manually ( except Device Status Notification), I have the same message " ...you already purchased 1..." .
> 
> Also in HA logs i have:
> ................................
> "result": {
> "access_token": "_**", "expire_time": 7200, "platform_url": "https://openapi.tuyaeu.com", "refresh_token": "**_",
> "uid": "***"
> },
> "success": true,
> "t": 1632246264971
> }
> ..............and then.....................
> 2021-09-21 20:44:25 DEBUG (Thread-4) [tuya iot] connecting ssl://m1.tuyaeu.com:8883
> 2021-09-21 20:44:25 DEBUG (SyncWorker_2) [tuya iot] Response: {
> "code": 28841101,
> "msg": "No permissions. This API is not subscribed.",
> "success": false,
> ....etc .............
> Sorry I don't know what info I can put without my private information.

Yep that backs up my findings. Also I can't run any apis via the web portal. Same error - not subscribed. Must be a change that tuya have made to their developer site...

```
{
  "code": 28841101,
  "msg": "No permissions. This API is not subscribed.",
  "success": false,
  "t": 1632245665055
}
```

**Comment by totalitarian** [comment]
This is working for me today. Created a new project and all the subscriptions correctly registered and the HA addon found my devices. Must have been an issue with the dev portal.

**Comment by bohanic** [comment]
> This is working for me today. Created a new project and all the subscriptions correctly registered and the HA addon found my devices. Must have been an issue with the dev portal.

I also make new project and everything is OK.

**Comment by ravensergio** [comment]
> This is working for me today. Created a new project and all the subscriptions correctly registered and the HA addon found my devices. Must have been an issue with the dev portal.


> I also make new project and everything is OK.

Thank You both. I can confirm also that, by making a new project I can now see the added devices, including a dehumidifier (altough just with basic settings).

**Comment by luanbon** [comment]
As described by others before, It's working now ! I have created another project and everything started working.

**Comment by gnosis3825** [comment]
One more confirmation that this worked for me too. Everything appeared *immediately* upon integration. Thank you to whoever fixed this!
