### ISSUE TITLE
Tuya V2 not added to available integrations after installing via HACS

### ISSUE THREAD

**Issue by damienraj** [tuya/tuya-home-assistant#494]
Describe the bug:
Followed installation instructions from Wiki (https://github.com/tuya/tuya-home-assistant/wiki/Install-Tuya-v2?_source=d10de34623e3daca5b02e3c31528a0c4) to install Tuya V2 on Home Assistant via HACS.  At step 2.4 in the wiki, after re-starting Home Assistant, the Tuya V2 integration does not appear to be available in list of integrations.

Expected behavior:
The wiki describes Tuya V2 being available as a separate integration from standard Tuya.  Only standard Tuya appears available.

**Screenshots**
![image](https://user-images.githubusercontent.com/90476180/134759891-1aa49a9c-f059-4bee-97f0-b5ce68e9c20d.png)

Home Assistant Version
2021.9.6

No device info available as cannot install integration.

**Comment by tetsuo55** [comment]
Can you send a screenshot of the custom repositories

**Comment by damienraj** [comment]
hi tetsuo55, the problem seems to have gone away by itself.  TuyaV2 is now available in the integrations list.  Thanks anyway

**Comment by VirusAlex** [comment]
Same issue:
![image](https://user-images.githubusercontent.com/28566658/136080076-8d69bff5-8885-467b-80b7-6cf6bafad4fe.png)
![image](https://user-images.githubusercontent.com/28566658/136080114-5c9702ab-6063-45c1-bd64-4800e1c3c421.png)
