### ISSUE TITLE
Please support sensor devices

### ISSUE THREAD

**Issue by chaopeng** [tuya/tuya-home-assistant#5]
- PIR sensor
- temp and humidity sensor
- ...

**Comment by shawnfaleiro** [comment]
Please support sensor devices

**Comment by rredeyess** [comment]
Please support sensor devices

**Comment by zlinoliver** [comment]
Hi @chaopeng @f021930c we have updated the integration and add sensor devices support, please check this file: https://github.com/tuya/tuya-home-assistant/blob/master/custom_components/tuya_v2/sensor.py

**Comment by philhzss** [comment]
> Hi @chaopeng @f021930c we have updated the integration and add sensor devices support, please check this file: https://github.com/tuya/tuya-home-assistant/blob/master/custom_components/tuya_v2/sensor.py

Hi,
I've only been using Home Assistant for a few days, but I have the same issue (thermometer shows up as switch):
![image](https://user-images.githubusercontent.com/41757256/121103577-3ae1d080-c7ce-11eb-9338-24c2c6e0b88b.png)


How/when will the integration be update on Home Assistant? Can I import the .py file you linked myself, or must I wait for an official Tuya integration update in Home Assistant?

Thank you!

**Comment by tsutsuku** [comment]
@philhzss  @BadgerJed You can install the integration by following the [README](https://github.com/tuya/tuya-home-assistant#21-home-assistant-custom-components-installation)
After installing, you can see the sensor in the dashboard if the integration support now.

**Comment by philhzss** [comment]
@tsutsuku Thank you, I'm trying to do it with the README instructions, but now it seems my sensor devices don't show up (even though they show up in the cloud projects). My lights do show up though.

Should I be installing the "master" branch into HACS? Because the latest release v1.1 is 15 days ago and I'm not sure you had added sensor support by then?
Thank you!

**Comment by philhzss** [comment]
Oh, I got it working! I had to install "tuyav2" from HACS. It says that it's 213C, I suppose thats 21.3C.

**Comment by BadgerJed** [comment]
> Oh, I got it working! I had to install "tuyav2" from HACS. It says that it's 213C, I suppose thats 21.3C.

Did you have to remove the whole original integration first before installing the V2 version? Thanks.

**Comment by philhzss** [comment]
Im not sure about removing the old version, I accidentally corrupted my entire RaspberryPi last week so I had to delete everything and start from scratch. I already have a Tuya dev account for another project I did a few months back.. it says "trial" so I hope this never expires?? Im not sure. But yeah I had to create a new project like the readme says and get an access ID and password from there

**Comment by BadgerJed** [comment]
I'm almost there now, I don't understand how to do this final step of the readme. Do you have any pointers thanks.
![Finl step](https://user-images.githubusercontent.com/85431111/122116360-6e031000-ce1d-11eb-9ad3-c899f696619f.JPG)

**Comment by tsutsuku** [comment]
@BadgerJed  It's home assistant core launch command. you can also read 
https://www.home-assistant.io/installation/linux#create-the-virtual-environment

**Comment by zlinoliver** [comment]
> Im not sure about removing the old version, I accidentally corrupted my entire RaspberryPi last week so I had to delete everything and start from scratch. I already have a Tuya dev account for another project I did a few months back.. it says "trial" so I hope this never expires?? Im not sure. But yeah I had to create a new project like the readme says and get an access ID and password from there

Using the latest version of the Tuya Home Assistant Integration v2 from this github repo, you don't need to remove the old version, they can be installed simultaneously. For the "trial" version of the Tuya cloud project, you can renew it for free next year.
