### ISSUE TITLE
Thermostat wrong temperature

### ISSUE THREAD

**Issue by flayy73** [tuya/tuya-home-assistant#502]
Hi, 
I try to set up this Thermostat model : https://www.aliexpress.com/item/1005001874317882.html?spm=a2g0s.9042311.0.0.40d74c4d5VSqTv

Should be possible to see the actual temperature, to set a temperatore, switch on/stand-by the thermostat but unfortunately none of this options are possible with the Thermostat standar card into lovelace and the current temperature is completely wrong.

Here the card image
![immagine](https://user-images.githubusercontent.com/86019626/135248226-4fb0426f-0f5c-454a-91c4-4af911378783.png)

**Home Assistant Version**
core-2021.9.7
supervisor-2021.09.4

**Device info **
2021-09-29 11:26:22 DEBUG (SyncWorker_0) [tuya iot] Response: {
  "result": [
    {
      "active_time": 1628280192,
      "biz_type": 18,
      "category": "wk",
      "create_time": 1622049142,
      "icon": "smart/icon/15264583415nnlzwfs1qd2wqz6i937op3nmi_0.png",
      "id": "878608518caab5e502f5",
      "ip": "***",
      "lat": "***",
      "local_key": "***",
      "lon": "***",
      "model": "",
      "name": "Termostato01",
      "online": true,
      "owner_id": "35277597",
      "product_id": "IAYz2WK1th0cMLmL",
      "product_name": "thermostat",
      "status": [
        {
          "code": "switch",
          "value": false
        },
        {
          "code": "temp_set",
          "value": 30
        },
        {
          "code": "upper_temp",
          "value": 45
        },
        {
          "code": "eco",
          "value": false
        },
        {
          "code": "child_lock",
          "value": false
        }
      ],
      "sub": false,
      "time_zone": "+01:00",
      "uid": "***",
      "update_time": 1632846559,
      "uuid": "878608518caab5e502f5"
    }
  ],
  "success": true,
  "t": 1632907582148
}

Tks for your support

**Comment by JavierJMzgz** [comment]
Exactly the same issue here with BHT-6000 thermostat (HA shows 4,2ºC when it should be 21ºC)
In previous official integration (let's say v1) there were some parameters in its configuration that allowed to apply some multipliers to fix the temperature shown in HA. It would be fine if something similar could be implemented in tuya v2, as @derekoharrow said before.

**Comment by efcarv** [comment]
Same problem here...

**Comment by gabrieledaltoe** [comment]
Same Issue with BHT-002... I see wrong setpoint temperature (HA shows 3,7°C when it should be 18,5°C), but I Can not see actual temperature!!!

**Comment by EmmanuelLM** [comment]
Same here

**Comment by Roky8-6** [comment]
same problem... and it is no longer possible to display the room temperature
A lifetime to troubleshoot v.1 and now let's start again :/

**Comment by piwi3910** [comment]
same here

**Comment by krisnoble** [comment]
Following as I have the same problem. Very disappointing to be a month down the line and still missing such basic functionality. And even more frustrating having jumped through a bunch of hoops to get to this stage!

**Comment by AlessandroTischer** [comment]
Same issue in HA 2021.11... I think I'll keep using 2021.9.7 for a while...

**Comment by mrascol** [comment]
Regarding the number of issue for the same subject... a lest the following :
https://github.com/tuya/tuya-home-assistant/issues/676
https://github.com/tuya/tuya-home-assistant/issues/675
https://github.com/tuya/tuya-home-assistant/issues/670
https://github.com/tuya/tuya-home-assistant/issues/547
https://github.com/tuya/tuya-home-assistant/issues/542
https://github.com/tuya/tuya-home-assistant/issues/535
https://github.com/tuya/tuya-home-assistant/issues/502

It appears to be a Critical issue... unfortunatly I'm note able to contribute...
Is anyone able to fix Thermostat issue : 
- wrong temperature set reported by the integration plugin
- unable to get  current temperature
- unable to change/manage/set the temperature

**Comment by kossn93** [comment]
There was a problem that the temperature was displayed correctly on the thermostat and in the tuya application, for example, 26 degrees Celsius, and in HA 2.6 degrees, a temporary solution is to change the divider in the climate.py file from 100 to 10, on line number 40. in my case this file is located config \ deps \ Python38 \ site-packages \ tuyaha \ devices.
Maybe this will help someone too.

**Comment by AlessandroTischer** [comment]
Hi! Is there any news on this topic? Any way to get our thermostats working with the official integration? (I have a couple of them in another place, so being on different networks I can't use local-Tuya)

**Comment by evanvruggink** [comment]
> There was a problem that the temperature was displayed correctly on the thermostat and in the tuya application, for example, 26 degrees Celsius, and in HA 2.6 degrees, a temporary solution is to change the divider in the climate.py file from 100 to 10, on line number 40. in my case this file is located config \ deps \ Python38 \ site-packages \ tuyaha \ devices. Maybe this will help someone too.

This file doesn't exist for me, also I have the same problem. It's a shame that the previous option to multiply/devide the temperature was removed.

**Comment by kizio1000** [comment]
Hi.

For months already I have been postponing update of Home assistant due to this problem. Beginning of 2022 Tuya planned to stop functionality of "old" integration and still there is no solution for making this thermostat working.   :/
![x](https://user-images.githubusercontent.com/76654878/147752328-78459214-06a7-4c28-8848-2b243edb974e.jpg)

**Comment by richardcastle** [comment]
Same problem here. Target temperature seems to be out by a factor of 5 and actual temperature reports null.

**Comment by paulius2k** [comment]
Same problem with BHT-002-GCLW
