### ISSUE TITLE
Deta Grid Connect Smart Double Touch Power Point 

### ISSUE THREAD

**Issue by Diramu** [tuya/tuya-home-assistant#506]
**Device normal info**
- Deta
- 6922HA

**Device info**
 {
      "active_time": 1607130955,
      "biz_type": 0,
      "category": "cz",
      "create_time": 1607130955,
      "icon": "smart/icon/ay1536534747810ekKBj/1565060176b67ed87bfab.png",
      "id": "31062738483fda4180e4",
      "ip": "***",
      "lat": "***",
      "local_key": "***",
      "lon": "***",
      "name": "brmo  sideboard gpo 1",
      "online": true,
      "owner_id": "7962227",
      "product_id": "0Er7V22WLD2CyS1P",
      "product_name": "Double Power Point 6922HA",
      "status": [
        {
          "code": "switch_1",
          "value": true
        },
        {
          "code": "switch_2",
          "value": true
        },
        {
          "code": "countdown_1",
          "value": 0
        },
        {
          "code": "countdown_2",
          "value": 0
        }
      ],
      "sub": false,
      "time_zone": "+10:00",
      "uid": "***",
      "update_time": 1631521671,
      "uuid": "31062738483fda4180e4"
    }

**Device specifications **
2021-09-30 15:28:53 DEBUG (SyncWorker_0) [tuya iot] Request: method = POST, url = https://openapi.tuyaeu.com/v1.0/devices/31062738483fda4180e4/commands, params = None, body = {'commands': [{'code': 'switch_1', 'value': True}]}, t = 1632979733718
2021-09-30 15:28:53 DEBUG (SyncWorker_0) [tuya iot] Response: {
  "result": true,
  "success": true,
  "t": 1632979733911
}

** Current Tuya-V2 Status  **
This device can be switched off by HA, but after a second or two, the status switches back to on.
![switch_off](https://user-images.githubusercontent.com/973442/135394438-ff47d7d1-d152-4b27-bf34-638896ad874c.gif)
To turn it back on, you need to turning it off again, and while the status show it is off,  then turn if on (double click)
![switch_on](https://user-images.githubusercontent.com/973442/135394443-bfff1123-ffe5-4159-b3fe-6103818b907a.gif)

**Comment by passions88** [comment]
SkyLight Records, Radio #1 $ with my Team #1 Singer in the whole wide world in the Rocken Roll Hall of Fame Chad Michael Sheda

**Comment by passions88** [comment]
> SkyLight Records, Radio #1 $ with my Team #1 Singer in the whole wide world in the Rocken Roll Hall of Fame Chad Michael Sheda

**Comment by Diramu** [comment]
I discover I did not have my Device Status Notification service authorized. Working fine now.
