### ISSUE TITLE
State changes are not visible in Home Assistant (Plug socket)

### ISSUE THREAD

**Issue by andytuinman3** [tuya/tuya-home-assistant#52]
**Describe the bug**
I have multiple Hombli plugs and wanted to test out the new tuya v2 integration. I setup everything just fine and the devices are visible. But first of all Power measurements are not refreshed. It just pulls it one time and leaves it at that. Whatever happens. 
Second: Whenever I switch off my socket with the smart life app, the entity in Home assistant doesnt change. It stays on. I can click it off and click it back on and the socket turns on via home assistant just fine. It just wont register any changes on/off and power measurments. 

**Expected behavior**
A timer based power measurement or even just the same speed as the smart life app. And switch changes on Home assistant regardless of where I turn off the plug. (Smart life or physical button) 

**Screenshots**

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
like this:
2021-07-03 22:27:11 DEBUG (SyncWorker_1) [tuya iot] Response: {
  "result": [
    {
      "active_time": 1624460882,
      "biz_type": 18,
      "category": "cz",
      "create_time": 1624460882,
      "icon": "smart/icon/ay1554288005676QBjh1/c092ddd9338cc8a583ac66a931089c55.jpg",
      "id": "xxxxxx",
      "ip": "xxx.xxx.xxx.xxx",
      "lat": "",
      "local_key": "xxxxxx",
      "lon": "",
      "name": "PC plug",
      "online": true,
      "owner_id": "31593721",
      "product_id": "guonyunxhmth3aun",
      "product_name": "Hombli Smart Socket",
      "status": [
        {
          "code": "switch_1",
          "value": true
        },
        {
          "code": "countdown_1",
          "value": 0
        },
        {
          "code": "add_ele",
          "value": 12
        },
        {
          "code": "cur_current",
          "value": 135
        },
        {
          "code": "cur_power",
          "value": 239
        },
        {
          "code": "cur_voltage",
          "value": 2350
        }
      ],
      "sub": false,
      "time_zone": "+02:00",
      "uid": "eu1622401036167YME84",
      "update_time": 1625342436,
      "uuid": "4b2eefdb03b18f01"
    },
    {
      "active_time": 1622401146,
      "biz_type": 18,
      "category": "cz",
      "create_time": 1622401146,
      "icon": "smart/icon/ay1554288005676QBjh1/c092ddd9338cc8a583ac66a931089c55.jpg",
      "id": "xxxxxxx",
      "ip": "xxx.xxx.xxx.xxx",
      "lat": "00.000000",
      "local_key": "xxxxxxx",
      "lon": "0.000000",
      "name": "TV plug",
      "online": true,
      "owner_id": "31593721",
      "product_id": "guonyunxhmth3aun",
      "product_name": "Hombli Smart Socket",
      "status": [
        {
          "code": "switch_1",
          "value": false
        },
        {
          "code": "countdown_1",
          "value": 0
        },
        {
          "code": "add_ele",
          "value": 44
        },
        {
          "code": "cur_current",
          "value": 0
        },
        {
          "code": "cur_power",
          "value": 0
        },
        {
          "code": "cur_voltage",
          "value": 2337
        }
      ],
      "sub": false,
      "time_zone": "+02:00",
      "uid": "eu1622401036167YME84",
      "update_time": 1625342299,
      "uuid": "822066c5f7de3bc5"
    }

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
Same device's id, like this:
2021-07-03 22:27:11 DEBUG (SyncWorker_1) [tuya iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/devices/xxxxxx/specifications, params = None, body = None, headers = {'client_id': 'xxxxxx', 'sign': 'xxxxxxx', 'sign_method': 'HMAC-SHA256', 'access_token': 'xxxxxxx', 't': '1625344031411', 'lang': 'en'}
2021-07-03 22:27:11 DEBUG (SyncWorker_1) [tuya iot] Response: {
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "add_ele",
        "type": "Integer",
        "values": "{\"unit\":\"kwh\",\"min\":0,\"max\":50000,\"scale\":3,\"step\":100}"
      },
      {
        "code": "cur_current",
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_power",
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":50000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "cur_voltage",
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1625344031434
}
2021-07-03 22:27:11 DEBUG (SyncWorker_1) [tuya iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/devices/xxxxxx/specifications, params = None, body = None, headers = {'client_id': 'xxxxxx', 'sign': 'xxxxxxx', 'sign_method': 'HMAC-SHA256', 'access_token': 'xxxxxxx', 't': '1625344031444', 'lang': 'en'}
2021-07-03 22:27:11 DEBUG (SyncWorker_1) [tuya iot] Response: {
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "add_ele",
        "type": "Integer",
        "values": "{\"unit\":\"kwh\",\"min\":0,\"max\":50000,\"scale\":3,\"step\":100}"
      },
      {
        "code": "cur_current",
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_power",
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":50000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "cur_voltage",
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1625344031490
}

**Comment by kbarendrecht** [comment]
This issue seems to be the same as mine: #39 
Can you verify if you have a `/usr/local/lib/python3.8/site-packages/tuya_iot/` folder?

**Comment by andytuinman3** [comment]
But your switch doesn't work at all. I can switch it on and off through home assistant just fine. But whenever I switch it on or off through smart life the state doesn't change on home assistant.

**Comment by kbarendrecht** [comment]
It only functions when the state of the entity matches the state of the switch. I found out that if I press twice quickly, it does send the 'off' command, after which it will work one time again, because it sends the 'on' command.

**Comment by kbarendrecht** [comment]
@andytuinman3 Can you verify if you have added the `Device status notification API` to your tuya developer account, AND authorized your project to use that API? Its working for me now 🎉

**Comment by andytuinman3** [comment]
You are a hero. It works like a charm now. Every 30 seconds the power consumption refreshes now. This issue is solved for me now
