### ISSUE TITLE
Login Error 1106: Permission deny

### ISSUE THREAD

**Issue by Aephir** [tuya/tuya-home-assistant#540]
I get the error code 1106 when trying to add this "new" integration in Home Assistant.

I have seen a few others with this issue, though on the tuya-homebridge repo (#110 #46 #64), but I am using the correct password (from Tuya Smart app, not developer account). 

I've also looked [here](https://www.home-assistant.io/integrations/tuya/#error-codes-and-troubleshooting), but the account is linked (I see my devices in `Devices`-> `All Devices` on https://iot.tuya.com), the username/password are copied from my password manager (that I also used to log in to the Tuya Smart app today). The last link on that page about `availability zones` links to a page that doesn't mention the word `availability` or the word `zones` anywhere.

The `Country` on my Tuya Smart app is Denmark, which is also what I select for the Home Assistant integration. For `Account` I wrote `Tuya Smart`, which is the app I use. I'm using `Central Europe Datacenter`, and I'm fairly sure this is correct, since when I tried with `Western Europe`, the devices did not appear under `All Devices`.

**Home Assistant Version**
- e.g. 2021.10.1

**Comment by henrikhjelm** [comment]
![nedladdning (71)](https://user-images.githubusercontent.com/5031424/136630728-25327149-28e3-448c-ae96-6bc4f8b4e161.png)
https://developer.tuya.com/en/docs/iot/Home_Assistant_Integration?id=Kamcjcbvk2mu8

**Comment by dulantha-tuya** [comment]
[This page](https://developer.tuya.com/en/docs/iot/Platform_Configuration_smarthome?id=Kamcgamwoevrx#title-5-Correspondence%20of%20regions%20(of%20apps)%20and%20availability%20zones%20(of%20cloud%20development%20projects)) has a table at the bottom showing the country code selected in the Tuya Smart App called "Region" and the corresponding "Availability Zones"

https://developer.tuya.com/en/docs/iot/Platform_Configuration_smarthome?id=Kamcgamwoevrx#title-5-Correspondence%20of%20regions%20(of%20apps)%20and%20availability%20zones%20(of%20cloud%20development%20projects)

**Comment by Aephir** [comment]
@henrikhjelm That is what is listed in the link to Home Assistant documentation I gave in the first post. As I said, I have gonne through that already.
@dulantha-tuya Thanks, but Denmark is not on the list. Does that mean I can't use this integration because me App is set up for my current location (Denmark)?

**Comment by asasi83** [comment]
I had the same issue, then I fiddled around and I have added my account under users, don't know if that is the correct way but I was able to log in after that.
![image](https://user-images.githubusercontent.com/13108368/136650638-fda3b82a-1234-442f-a2bd-08ecae747e4f.png)

Currently, after that, I have this issue... (https://github.com/tuya/tuya-home-assistant/issues/530)

**Comment by dulantha-tuya** [comment]
I just tried with a different project and different Tuya Smart user and I was unable to login with a 12 character password, but able to login after changing to an 11 character password. I can see the devices,

**Comment by Aephir** [comment]
I've now tried setting up the user in tuya cloud project, and "crippled" my password to 11 characters only using letters, numbers and underscores. But I still get the same, error 1106, when trying in Home Assistant.

**Comment by asasi83** [comment]
I can confirm that shortening the password as @dulantha-tuya stated worked for me,  adding user as I stated in the prior post is not needed. 
![image](https://user-images.githubusercontent.com/13108368/136700287-86aa7101-9b14-48da-9315-42ed2d73f9d1.png)

**Comment by seb-5x** [comment]
Yes indeed with a shorter password it works
