### ISSUE TITLE
Tuya Heater : Error adding entities

### ISSUE THREAD

**Issue by griZouw** [tuya/tuya-home-assistant#560]
**Describe the bug**
I've bought an Eurom Heater, i've successfully added to smart life app, and added it with the new tuya integration, the device is correctly added in Home assistant, but without any entities. 

**Expected behavior**
The ability to control this heater.

**Error logs**

**Home Assistant Version**
2021.10.3

**Device info :**
{
      "active_time": 1633874273,
      "biz_type": 18,
      "category": "qn",
      "create_time": 1633687289,
      "icon": "smart/product_icon/qn.png",
      "id": "677840228cce4ede9d62",
      "ip": "***",
      "lat": "***",
      "local_key": "***",
      "lon": "***",
      "model": "LPL-18",
      "name": " Your Eurom Heater",
      "online": true,
      "owner_id": "2876052",
      "product_id": "wv9d5ocs76u6maqj",
      "product_name": " Your Eurom Heater",
      "status": [
        {
          "code": "switch",
          "value": true
        },
        {
          "code": "temp_set",
          "value": 20
        },
        {
          "code": "temp_current",
          "value": 21
        }
      ],
      "sub": false,
      "time_zone": "+01:00",
      "uid": "***",
      "update_time": 1633874278,
      "uuid": "677840228cce4ede9d62"
    },

**Error**

2021-10-11 11:45:13 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform tuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 498, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 228, in capability_attributes
    self.hass, self.min_temp, self.temperature_unit, self.precision
  File "/usr/src/homeassistant/homeassistant/components/tuya/climate.py", line 354, in min_temp
    return temp_min * 1.0 / (10 ** temp_set_scal)
TypeError: can't multiply sequence by non-int of type 'float'

**Comment by kxqcvl** [comment]
thanks for the respond, but the link refers to a topic that is deleted it seems.

I have a eurom airco, and here i can set different HVAC modes and set the temperature
![debug airco Tuya](https://user-images.githubusercontent.com/73292082/137618983-e0dd152d-84f4-4b05-9ab4-ff28f57007a5.jpg)

The Eurom heaters have no option to set temperature, they also do not report status when i change HVAC mode in home Assistant,they keep reporting OFF when they are ON, so they are useless for me at the moment
![debug heaters Tuya](https://user-images.githubusercontent.com/73292082/137619063-5eb56223-6831-4565-ac1f-f5357e2ab18f.jpg)

Is there anyway i can add HVAC modes or temperature settings in the Tuya Iot platform like the airco has? so i can integrate them properly in Home Assistant

**Comment by malosaa** [comment]
@griZouw 

i fixed everything 

Se our issue, and go to my forked version, link is available in the last message 
https://github.com/tuya/tuya-home-assistant/issues/482
