### ISSUE TITLE
Problem with my heaters

### ISSUE THREAD

**Issue by lmichalak78** [tuya/tuya-home-assistant#574]
I have found a several bugs in the code of climate.py - it is not working for my heaters (switch only mode).
After a few changes in code it now works fine:

def hvac_mode(self) -> str:
        """Return hvac mode."""
        if not self.tuya_device.status.get(DPCODE_SWITCH, True):
            return HVAC_MODE_OFF
            
        if DPCODE_MODE not in self.tuya_device.function:
            if self.tuya_device.status.get(DPCODE_SWITCH, False):
                return HVAC_MODE_HEAT
        
        if self.tuya_device.status.get(DPCODE_MODE) is not None:
            return TUYA_HVAC_TO_HA[self.tuya_device.status.get(DPCODE_MODE)]
        
        return HVAC_MODE_OFF

    @property
    def hvac_modes(self) -> List:
        """Return hvac modes for select."""
        if DPCODE_SWITCH in self.tuya_device.function:
            return [HVAC_MODE_OFF, HVAC_MODE_HEAT]
        
        
        if DPCODE_MODE not in self.tuya_device.function:
            return []
        modes = json.loads(self.tuya_device.function.get(DPCODE_MODE, {}).values).get(
            "range"
        )

        _LOGGER.debug(f"hvac_modes->{modes}")
        hvac_modes = [HVAC_MODE_OFF]
        for tuya_mode, ha_mode in TUYA_HVAC_TO_HA.items():
            if tuya_mode in modes:
                hvac_modes.append(ha_mode)

        return hvac_modes

Could you please correct your code to support devices wchich has no mode attribute?

**Comment by lmichalak78** [comment]
It does not work in my integration. My heaters look like this:
![image](https://user-images.githubusercontent.com/77161867/137719052-69071779-6225-45c4-90cf-ed267c3fe727.png)

What is more in my loga I have:
Oct 18 10:55:46 havm hass[15099]: 2021-10-18 10:55:46 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform tuya_v2.sensor: Platform not found (cannot import name 'STATE_CLASS_TOTAL_INCREASING' from 'homeassistant.components.sensor' (/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/sensor/__init__.py)).

Where is the problem?

**Comment by malosaa** [comment]
That's weird, for me every heater working.

Can u show me the debug output?

**Comment by malosaa** [comment]
try to delete line 407+408 in climate.py  and let me know 

this:
          ```
  if not self.tuya_device.status.get(DPCODE_SWITCH, True):
                return HVAC_MODE_OFF
```

**Comment by Daandeve** [comment]
Still the same, it jumps back to the old state. Also the `current_temperature` is reported as `null`

**Comment by malosaa** [comment]
@Daandeve  with your patch does it show the temperature?

https://github.com/tuya/tuya-home-assistant/issues/574#issue-1026375795

**Comment by Daandeve** [comment]
@malosaa I found with issue on the home assistant github, this is my heater model. Note the last comment...
https://github.com/home-assistant/core/issues/26837
