### ISSUE TITLE
Login error (2406): skill id invalid

### ISSUE THREAD

**Issue by Marcos-kp** [tuya/tuya-home-assistant#582]
I was using the old integration, updated HASSIO and can't set up the new Tuya integration.
After I tried to use the same Account ID and password from the dev platform, I checked the https://www.home-assistant.io/integrations/tuya/ website and saw this: "Make sure that your cloud project on the Tuya IoT Platform should be created after May 25, 2021. Otherwise, you need to create a new project or migrate data to a new project. For more information, see Operation on the Tuya IoT Platform."

Ok, since I had my project set before may, I created a new project, deleted the old integration, unlinked my devices from my old project and linked with the new one. Same error.

After that, I created a new dev account and tried from scratch, same error.

I was using local tuya, but can't find any relation since I am using a brand new account for this setup and my old account don't have any link with my smart tuya account (the one used in the app)

Home Assistant Version

Home Assistant OS 6.5
core-2021.10.4
supervisor-2021.10.0

**Comment by HiveMindAutomation** [comment]
Also having the same issue. Cannot setup the integration in new Home Assistant 2021.10.5 (implemented natively, without need for HACS install)

**Comment by pensivealbatross** [comment]
:(   I have exactly the same.   Created a whole new developer account to no avail.

**Comment by Marcos-kp** [comment]
Thanks @dancurtis1988 !

**Comment by lpt2007** [comment]
thx @Marcos-kp 

Now is working :)

**Comment by BigBad2000** [comment]
Similar boat to pgv123.

Have created two new projects today and still have the same login error.  Am connecting to Australia.  Have confirmed that my project is on the Central Europe server.  Have linked my tuya smart app to the project and can see the devices in the project.  Entering correct information into Tuya integration in home assistant, choosing Australia, entered the access ID and secret.  Used same username and password for the tuya smart app.

Still same issue.

**Comment by BigBad2000** [comment]
> I'm still struggling to get a result here. I had no previous developer account but did have tuya integration for a long time in HA. Have one lone Wifi Brilliant Smart lamp. I'm based in Australia I have created a new developer account and was able to connect the tuya app and the lamp shows up in the All Devices list. All appears fine. I had to set my server to Central Europe to get it to appear. In HA I removed all reference to Tuya in the configuration and rebooted. When attempting to set up the integration in HA I stll get this login error (2406): skill id invalid. Is it necessary to create a whole new login for the app? It seems that you cannot effectively delete the current user for at least 7 days. What am I missing here?

Hey pgv I found in an reddit post changing from Australia to Sweden works.  And it does.  I suspect there is something in the Tuya backend servers that is blocking the Australia portion for some reason..

**Comment by pgv123** [comment]
> > I'm still struggling to get a result here. I had no previous developer account but did have tuya integration for a long time in HA. Have one lone Wifi Brilliant Smart lamp. I'm based in Australia I have created a new developer account and was able to connect the tuya app and the lamp shows up in the All Devices list. All appears fine. I had to set my server to Central Europe to get it to appear. In HA I removed all reference to Tuya in the configuration and rebooted. When attempting to set up the integration in HA I stll get this login error (2406): skill id invalid. Is it necessary to create a whole new login for the app? It seems that you cannot effectively delete the current user for at least 7 days. What am I missing here?
> 
> Hey pgv I found in an reddit post changing from Australia to Sweden works. And it does. I suspect there is something in the Tuya backend servers that is blocking the Australia portion for some reason..

Spot on! Works perfectly.

Strange thing...

**Comment by thecutehacker** [comment]
> 
> 
> > I'm still struggling to get a result here. I had no previous developer account but did have tuya integration for a long time in HA. Have one lone Wifi Brilliant Smart lamp. I'm based in Australia I have created a new developer account and was able to connect the tuya app and the lamp shows up in the All Devices list. All appears fine. I had to set my server to Central Europe to get it to appear. In HA I removed all reference to Tuya in the configuration and rebooted. When attempting to set up the integration in HA I stll get this login error (2406): skill id invalid. Is it necessary to create a whole new login for the app? It seems that you cannot effectively delete the current user for at least 7 days. What am I missing here?
> 
> Hey pgv I found in an reddit post changing from Australia to Sweden works. And it does. I suspect there is something in the Tuya backend servers that is blocking the Australia portion for some reason..

Another Australian user, can confirm that changing to sweeden on the home assistant tuya login works! Along with the central europe server

**Comment by sebastian-tennant** [comment]
> > Hey pgv I found in an reddit post changing from Australia to Sweden works. And it does. I suspect there is something in the Tuya backend servers that is blocking the Australia portion for some reason..
> 
> Another Australian user, can confirm that changing to sweeden on the home assistant tuya login works! Along with the central europe server

Another aussie confirming Sweden worked :)

**Comment by MattyWylde** [comment]
I'm an Aussie here. I have data centre set to central Europe, country set to region and I'm still having the same issue. Does anyone know a work around?

**Comment by lboue** [comment]
Same issue for me. I live in France

**Comment by jakub-a** [comment]
Same issue. I live in Poland.

**Comment by get-fooby** [comment]
New account, signed up today, got stuck in Isle of Man for my account (im in England) tried to link got 2406, selected Sweden in Home Assistant - worked.
