### ISSUE TITLE
Issue with motion sensor in v1.6

### ISSUE THREAD

**Issue by hiraniha** [tuya/tuya-home-assistant#583]
I have a motion sensor in my garage which is working as expected in v1.5 but stops working in v1.6

HA doesn't see the motion detected always appear as Clear.

Works fine again if I downgrade to v1.5

**Home Assistant Version**
core-2021.10.4
supervisor-2021.10.0

**Comment by berre011** [comment]
Have the same problem and went back to 1.5

**Comment by Zeunas** [comment]
Same with door sensors
