### ISSUE TITLE
 you cannot scan the qr code to add a device deployed in another data center

### ISSUE THREAD

**Issue by bdr1991** [tuya/tuya-home-assistant#585]
anyone else had the above issue when trying to link your Tuya app on the Tuya IOT website?

**Comment by Dsm20001** [comment]
Yeah I'm getting it too. frustrating as heck every time I tried to get this integration to work, there are problems, and I can't never install it.

**Comment by dish67** [comment]
in home assistant(HA)  the app tuya does not work anymore, I try to follow your documentation try to add application on 
https://ue.iot.tuya.com/cloud/ ==> Link Tuya App Account ==> Add app Account and scan with the appl tuya android and I receiced the error you cannot scan the qr code to add a device deployed in another data center!!!

this is the same problem as bdr1991 you cannot scan the qr code to add a device deployed in another data center!!!

do you have solution , Thank you

**Comment by erwinf** [comment]
same error here. i unlinked my app account and can no longer link again.

**Comment by Scope666** [comment]
> I resolved my problem from u/nubycake22 (redit) I believe I found how to solve this!!
> 
> Apparently, when seting up your Link Tuya App Account in the Devices tab under My Cloud Projects, there is a dropdown in the top right of the page that is the region your device will be connected.
> 
> You need to use the correct one (and the only this one for this to work). So, before everything, go to all your accounts and projects and make sure to unlink your app account and make sure to unlink from all regions. You can edit your project, add all regions and unlink it. After you done this, go on and try linking your app account (with the QR code) region by region and checking if the All Devices tab show your devices. When it does, make sure to unlink from all other regions.
> 
> After that is done, I was able to connect with HASSIO and get my devices working!

This worked for me, thanks!!!!

**Comment by bdr1991** [comment]
> I resolved my problem from u/nubycake22 (redit) I believe I found how to solve this!!
> 
> Apparently, when seting up your Link Tuya App Account in the Devices tab under My Cloud Projects, there is a dropdown in the top right of the page that is the region your device will be connected.
> 
> You need to use the correct one (and the only this one for this to work). So, before everything, go to all your accounts and projects and make sure to unlink your app account and make sure to unlink from all regions. You can edit your project, add all regions and unlink it. After you done this, go on and try linking your app account (with the QR code) region by region and checking if the All Devices tab show your devices. When it does, make sure to unlink from all other regions.
> 
> After that is done, I was able to connect with HASSIO and get my devices working!

This worked for me too. When selecting data centre i just selected all and then edited it in the top right corner of the add tuya app screen until i found a QR code that worked.

**Comment by fredanaman** [comment]
> > I resolved my problem from u/nubycake22 (redit) I believe I found how to solve this!!
> > Apparently, when seting up your Link Tuya App Account in the Devices tab under My Cloud Projects, there is a dropdown in the top right of the page that is the region your device will be connected.
> > You need to use the correct one (and the only this one for this to work). So, before everything, go to all your accounts and projects and make sure to unlink your app account and make sure to unlink from all regions. You can edit your project, add all regions and unlink it. After you done this, go on and try linking your app account (with the QR code) region by region and checking if the All Devices tab show your devices. When it does, make sure to unlink from all other regions.
> > After that is done, I was able to connect with HASSIO and get my devices working!
> 
> This worked for me too. When selecting data centre i just selected all and then edited it in the top right corner of the add tuya app screen until i found a QR code that worked.

Thanks, got it working finally. In my case i had to select central eu instead of western.

**Comment by mcousine** [comment]
here the solution visualy add all datacenter in your cloud project 

![tuyaImpossibleAddDeviceDataCenterLink](https://user-images.githubusercontent.com/4398519/140083671-1184ffe9-7b01-4b4b-8fff-e67ed7a39fd0.png)

go to link tuya app and select up-right one datacenter at a time Generate QRCode try it in Tuya App one buy one datacenter
![tuyaImpossibleAddDeviceDataCenterLinkpart2](https://user-images.githubusercontent.com/4398519/140083735-c38c3a3a-860d-43ad-af96-b7e2098581a3.png)

**Comment by jcavalheri** [comment]
Hi guys, indeed !!!
So the trick is,if you are using an old Tuya Smart connection, the datacenter is not actually from your region, but actually coming from China.

The way I discover it >> I added all datacenters Like image above + one by one, try to link the QR code.

![image](https://user-images.githubusercontent.com/48921229/142182488-5932fb08-e29c-404c-a454-522d17809cb2.png)
