### ISSUE TITLE
Water Leak Detector not available in HA

### ISSUE THREAD

**Issue by mrteausa** [tuya/tuya-home-assistant#592]
I already setup the IoT Tuya platform and all my devices is available including the Water Leak Detector.  It works fine with the SmartLife app.  When I intregration with Home Assistant the Water Leak Sensor entity/devices does not show up.  All other devices show up fine except this one.  Any update needed in the future for this sensor?

**Comment by PrzemekSkw** [comment]
Hi, did You try to run that sensor? Give some water to wake him up?

**Comment by martin3000** [comment]
see #597

**Comment by frenck** [comment]
Water Detectors has been added to the Home Assistant Core version, pending the 2021.11 release.

**Comment by mrteausa** [comment]
I just updated the latest version of HA core-2021.11.4.  The Tuya Water Leak still did not show up in HA.  The Tuya IOT site, I can see the Water Sensor and battery level just fine.  Any ldea why.

**Comment by JohnB7754** [comment]
I am having the exact same issue with my water sensors. The battery status on all of them (I have 6 sensors) update instantly but the device status just says Dry all the time. Even if i hit the sensors with water, the Tuya IOT updates correctly but Home Assist says Dry. Is there any update on this? I Have tried V2 but that is not supported and i had issues getting the sensors to connect via Local Tuya
