### ISSUE TITLE
Sensors stops updating after a while

### ISSUE THREAD

**Issue by t0ny-peng** [tuya/tuya-home-assistant#605]
**Describe the bug**

It is very often that the value of Wi-Fi thermometer in Home assistant stops being updated. The only solution is to restart the Tuya V2 integration. 

I'm sure it's not the problem of the thermometer itself because the correct value is shown in the Tuya app. 

**Expected behavior**
The value should be updated in HA.

**Screenshots**

See the horizontal line representing the value of Tuya sensors. 
<img width="420" alt="Screen Shot 2021-10-19 at 12 03 09 PM" src="https://user-images.githubusercontent.com/4816327/137975049-2ffab7d1-2d0c-4998-bd6a-c312c13a320b.png">

**Home Assistant Version**
- 2021.10.5

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
Collecting...

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
Collecting.... But it's just normal thermometer that can sense temperature and humidity.

**Additional context**

No

**Comment by zlinoliver** [comment]
Hi @t0ny-peng , the Tuya developer team really appreciates your contributions and efforts to this Tuya v2 integration project. As we stop maintaining it now, please help to recreate your issue in the Home Assistant Core repository: <https://github.com/home-assistant/core/tree/dev/homeassistant/components/tuya>
