### ISSUE TITLE
Arlec Smart Power Monitoring Plug (PC399HA) Power info missing in official tuya2 integration

### ISSUE THREAD

**Issue by zagnuts** [tuya/tuya-home-assistant#606]
**Describe the bug**
I have a number of Arlec branded power switches that also report power consumption. The old integration did not expose the power usage info but with the Tuya2 custom integration power consumption, volts, etc appeared as separate entities. With the Tuya2 official integration, that information is no longer available. Looking at the debug log, the raw data appears to still be there.

**Expected behavior**
The power, volts etc would either appear as attributes for the switch entity, or as separate entities.

**Screenshots**
n/a

**Home Assistant Version**
- core-2021.10.6

**Device info 
```
    {
      "active_time": 1602806606,
      "biz_type": 18,
      "category": "cz",
      "create_time": 1592870560,
      "icon": "smart/icon/ay1536534747810ekKBj/1567489983a750d08c70e.png",
      "id": "6552561***********",
      "ip": "***",
      "lat": "***",
      "local_key": "***",
      "lon": "***",
      "model": "PC399HA",
      "name": "Gaming PC",
      "online": true,
      "owner_id": "5974179",
      "product_id": "4ooy6eeqo6hnlax1",
      "product_name": "Smart Plug with Energy Meter PC399HA",
      "status": [
        {
          "code": "switch_1",
          "value": true
        },
        {
          "code": "countdown_1",
          "value": 0
        },
        {
          "code": "add_ele",
          "value": 78
        },
        {
          "code": "cur_current",
          "value": 1350
        },
        {
          "code": "cur_power",
          "value": 1716
        },
        {
          "code": "cur_voltage",
          "value": 250
        }
      ],
      "sub": false,
      "time_zone": "+10:00",
      "uid": "***",
      "update_time": 1634573195,
      "uuid": "6552561***********"
    },
```

**Device specifications
```
2021-10-19 08:05:13 DEBUG (SyncWorker_0) [tuya iot] Response: {
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "add_ele",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":50000,\"scale\":3,\"step\":100}"
      },
      {
        "code": "cur_current",
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_power",
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":50000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "cur_voltage",
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1634591113134
}

```
**Additional context**
Well, basically it *did* work when the Tuya2 integration was custom but moving it into the stable HA release it disappeared. It makes me think that perhaps a parser from the old integration has been used....

**Comment by zagnuts** [comment]
Saw something from https://twitter.com/Frenck saying that he had finished adding in support, and then I found https://github.com/home-assistant/core/pull/57668. So maybe it is coming?

**Comment by cutzenfriend** [comment]
Any updates on this? It's really frustrating that no power consumption is available for all my 10 switches...

**Comment by zagnuts** [comment]
I closed this as I saw support was coming, and in fact the most recent update brought back power monitoring for my switches (had to enable it though). This may not be the case for your specific devices, but the good news is that support for additional devices is increasing....

**Comment by jstott1070** [comment]
Still no progress on this? I was hoping for an update in The .12 update but nothing..

**Comment by zagnuts** [comment]
> Still no progress on this? I was hoping for an update in The .12 update but nothing..
Again, as noted above it works for me now with the Arlec devices. Check the integration itself (configuration/devices & services, tuya (click on devices), then click on the specific device itself. For mine I now have a control (the on/off switch) and sensors for current, power and voltage. They may not be enabled by default, and if this is the case there should be an option to toggle them on. If you still only have the switch, then hopefully it will come eventually!

**Comment by jstott1070** [comment]
Yeah, i do now get the power as a sensor on the plugs and they are showing valid data however they are not available within Energy for monitoring. 

Where as my plugs are named to a certain level of logic such as: sensor.power_monitor_05_fridge_power

The list of sensors i have in Energy are some sort of GUID such as: sensor.tybf21d6f1ae2e7bc36ed53m_4 - none of which show within the Tuya entities.. 

I guess my next step would be to remove Tuya and re-add and see if that fixes the issue

**Comment by jstott1070** [comment]
Hmm, removed Tuya however the phantom energy sensors (that dont function) are still in Energy.. Looks like i have to dig a little deeper.

**Comment by zagnuts** [comment]
> Yeah, i do now get the power as a sensor on the plugs and they are showing valid data however they are not available within Energy for monitoring.

Ah. By default the energy monitoring didn't magically appear either - I had to add in entries in my sensor.yaml for each device eg:

```
- platform: integration
    source: sensor.tybf21d6f1ae2e7bc36ed53m_4
    name: Fridge power
    unit_prefix: k
    round: 2
```
