### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by miraixyz** [tuya/tuya-home-assistant#617]
**Describe the bug**
I am trying to installed the Tuya V2 integration from the integration page but I am getting "Control Flow Could Not Be Loaded"

**Expected behavior**
As mentioned above, when I try to add the integration, it pauses for a few seconds as if it were installing but then pops up the above stated error.

**Screenshots**
![image](https://user-images.githubusercontent.com/36748647/138302439-9ce57a28-0d7e-4c32-b3c1-3f17d4c02177.png)

**Home Assistant Version**
2021.10.2

**Comment by frenck** [comment]
Anything in the logs?

**Comment by miraixyz** [comment]
Ah yes...sorry.

Logs:

Logger: homeassistant.config_entries
Source: config_entries.py:711
First occurred: 6:56:07 AM (1 occurrences)
Last logged: 6:56:07 AM

Error occurred loading configuration flow for integration tuya_v2: cannot import name 'ProjectType' from 'tuya_iot' (/usr/local/lib/python3.9/site-packages/tuya_iot/__init__.py)
