### ISSUE TITLE
linked devices not showing in tuya v2

### ISSUE THREAD

**Issue by yab999** [tuya/tuya-home-assistant#62]
linked my tuya account to tuya v2, authorization was successful and in the integration section Tuya v2 shows my tuya smart account ID. although no devices were added and there is no configuration option within the tuya v2 tab.

I disabled my local tuya and tuya integration from my HA but nothing solved the issue. even tried deleting the integration and started with a fresh copy.

![image](https://user-images.githubusercontent.com/86785852/124380525-acc21280-dcc5-11eb-81a7-01320d0f6890.png)

**Comment by tsutsuku** [comment]
@yab999 check your device is supported.
https://github.com/tuya/tuya-home-assistant/wiki/Supported-Device-Category

**Comment by yab999** [comment]
> @yab999 check your device is supported.
> https://github.com/tuya/tuya-home-assistant/wiki/Supported-Device-Category

its a tuya dimmer, works fine with tuya smart and logs do not show any issues

**Comment by tsutsuku** [comment]
@yab999 Can you provide device specifications from the log?

**Comment by yab999** [comment]
> @yab999 Can you provide device specifications from the log?

sure, thats HA logs:
`2021-07-05 18:33:39 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration tuya_v2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-05 18:33:39 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-05 18:33:39 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-05 18:33:58 ERROR (Thread-3) [tuya iot] error while get mqtt config
2021-07-05 18:33:58 ERROR (Thread-3) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.8/site-packages/tuya_iot/openmq.py", line 173, in run
time.sleep(self.mq_config.expireTime - 60)
AttributeError: 'TuyaOpenMQ' object has no attribute 'mq_config'
2021-07-05 18:34:15 ERROR (MainThread) [custom_components.hacs] thomasloven/lovelace-gui-sandbox - Repository is archived.
2021-07-05 18:34:15 ERROR (MainThread) [custom_components.hacs] thomasloven/lovelace-dummy-entity-row - Repository is archived.
2021-07-05 18:34:15 ERROR (MainThread) [custom_components.hacs] thomasloven/lovelace-gap-card - Repository is archived.`

and this is from tuya iot hub:

`
Dimmer 1
{
  "result": {
    "active_time": 1625167062,
    "biz_type": 0,
    "category": "tgkg",
    "create_time": 1625167062,
    "icon": "smart/icon/ay1536047723331OpdLN/16f98664612d4aad7010a64b3170851c.png",
    "id": "eb55bc88dbb084d0bffmns",
    "name": "Smart Dimmer Switch 2",
    "online": true,
    "owner_id": "44730101",
    "product_id": "4pa61y3uci6i1wmg",
    "product_name": "Smart Dimmer Switch",
    "status": [
      {
        "code": "switch_led_1",
        "value": true
      },
      {
        "code": "bright_value_1",
        "value": 640
      },
      {
        "code": "brightness_min_1",
        "value": 10
      },
      {
        "code": "led_type_1",
        "value": "led"
      },
      {
        "code": "work_mode",
        "value": "light_white"
      },
      {
        "code": "light_mode",
        "value": "none"
      }
    ],
    "sub": false,
    "time_zone": "+03:00",
    "uid": "az1625161985280qtxsJ",
    "update_time": 1625167066,
    "uuid": "f08b554038806b9f"
  },
  "success": true,
  "t": 1625167901147
}




Dimmer 2

{
  "result": {
    "active_time": 1625167033,
    "biz_type": 0,
    "category": "tgkg",
    "create_time": 1625167033,
    "icon": "smart/icon/ay1536047723331OpdLN/16f98664612d4aad7010a64b3170851c.png",
    "id": "eb3338800b713aa4abldif",
    "local_key": "",
    "name": "Smart Dimmer Switch",
    "online": true,
    "owner_id": "44730101",
    "product_id": "4pa61y3uci6i1wmg",
    "product_name": "Smart Dimmer Switch",
    "status": [
      {
        "code": "switch_led_1",
        "value": false
      },
      {
        "code": "bright_value_1",
        "value": 510
      },
      {
        "code": "brightness_min_1",
        "value": 10
      },
      {
        "code": "led_type_1",
        "value": "led"
      },
      {
        "code": "work_mode",
        "value": "light_white"
      },
      {
        "code": "light_mode",
        "value": "none"
      }
    ],
    "sub": false,
    "time_zone": "+03:00",
    "uid": "az1625161985280qtxsJ",
    "update_time": 1625167039,
    "uuid": "28562e3dbd5f50d6"
  },
  "success": true,
  "t": 1625167963463
}`

**Comment by tsutsuku** [comment]
@yab999 category tgkg is not supported now.

**Comment by yab999** [comment]
> @yab999 category tgkg is not supported now.

thank you for letting me know, hope this gets added soon.
