### ISSUE TITLE
Tuya login error response: {'code': 500, 'msg': 'system error, please contact the admin', 'success': False, 't': 1635454264251}

### ISSUE THREAD

**Issue by isaacandy** [tuya/tuya-home-assistant#640]
I'm getting this error since I've added the Tuya v2 
Couldn't get it to work 

```
Logger: custom_components.tuya_v2
Source: custom_components/tuya_v2/__init__.py:153 
Integration: Tuya v2 (documentation) 
First occurred: 4:51:04 AM (1 occurrences) 
Last logged: 4:51:04 AM

Tuya login error response: {'code': 500, 'msg': 'system error, please contact the admin', 'success': False, 't': 1635454264251}
```

**Comment by isaacandy** [comment]
Im getting this error "Error occurred loading configuration flow for integration tuya: cannot import name 'AuthType' from 'tuya_iot' (/srv/homeassistant/lib/python3.9/site-packages/tuya_iot/__init__.py)"

```
Logger: homeassistant.config_entries
Source: config_entries.py:711 
First occurred: 3:43:43 PM (1 occurrences) 
Last logged: 3:43:43 PM

Error occurred loading configuration flow for integration tuya: cannot import name 'AuthType' from 'tuya_iot' (/srv/homeassistant/lib/python3.9/site-packages/tuya_iot/__init__.py)
```

**Comment by mrteausa** [comment]
I have the same error when I update the HA-core2021.11.0.   How do you fix this issue of new Tuya v2 integrations?

**Comment by isaacandy** [comment]
> I have the same error when I update the HA-core2021.11.0.   How do you fix this issue of new Tuya v2 integrations?
> 
> I downgrade to Tuya version 1.4, I got the same error 500.  Maybe issue with new HA version 11 problem.

I had to downgrade 1.4.2 on HACS integration Tuya v2. If it doesn't allow you to login, try downgrading to 1.5.0. Once successful login, perform the update to 1.6

But I did made several attempts before it succeeded tho
