### ISSUE TITLE
Light Sensor not being recognized by HomeAssistant Tuya Integration

### ISSUE THREAD

**Issue by dum-skywalker** [tuya/tuya-home-assistant#641]
**Describe the bug**
Even when Integration documents tells that light sensor is accepted, mine doesn't. I have other 7 devices working in Smartlife and HA without problems after everything ok in the Tuya IoT Platform.

**Expected behavior**
The device should appear in home assistant.

**Screenshots**
N/A

**Home Assistant Version**
- e.g. 2021.10.6

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
Product Name
光照度传感器（WIFI低功耗）
Device ID
00254078a4e57c939640
Product Category
ldcg
Device Status
Online
Activated At
2021-10-26 19:01:02

**Comment by frenck** [comment]
This has been added to Home Assistant 2021.11, which is pending release.
