### ISSUE TITLE
The temperature of the air conditioner is not set

### ISSUE THREAD

**Issue by indoor25** [tuya/tuya-home-assistant#654]
Hello guys, I installed this integration and connected the air conditioner.
Everything works, only the temperature control does not work. The set temperature is displayed correctly.
With the Tuya Smart application - the temperature is set
Help adjust the temperature control work

core-2021.10.7

I can provide the necessary information

**Comment by jnex26** [comment]
Mine does the Same things

**Comment by indoor25** [comment]
after update - works
core-2021.11.0
