### ISSUE TITLE
Can't see Tuya V2 in Integrations after adding via HACS or Manual Install

### ISSUE THREAD

**Issue by hiraniha** [tuya/tuya-home-assistant#66]
After adding the Integration and rebooting HA, when I do Add Integration I only see Tuya and LocalTuya, I don't have Tuya V2. 

I also tried downloading and installing manually.

Any idea what I have done wrong, I have tried it a couple of times, I can see the files in the custom components

**Comment by frankosborne** [comment]
Try clearing your cache or loading HA in a inPrivate or incognito window. :)

**Comment by hiraniha** [comment]
Thanks that did the trick, I tried reloading it so many times, but didn't try that :(

**Comment by tsutsuku** [comment]
@hiraniha Can you provide logs?

**Comment by hiraniha** [comment]
This one is resolved now, it was just me I need to close the browser and reopen it as it only showed up after that, there was nothing in the logs
