### ISSUE TITLE
Suddenly unable to log in

### ISSUE THREAD

**Issue by cyh801** [tuya/tuya-home-assistant#664]
Suddenly unable to log in tuya_v2

Logger: custom_components.tuya_v2
Source: custom_components/tuya_v2/__init__.py:153
Integration: Tuya v2 (documentation)
First occurred: 上午12:31:56 (1 occurrences)
Last logged: 上午12:31:56

Tuya login error response: {'code': 1106, 'msg': 'permission deny', 'success': False, 't': 1636043515499}

**Comment by pkejval** [comment]
Already reported and acknowledged in https://github.com/tuya/tuya-home-assistant/issues/662#issuecomment-961054789
