### ISSUE TITLE
Door/ Window sensor. Only battery percentage displaying in Home Assistant

### ISSUE THREAD

**Issue by markusg1234** [tuya/tuya-home-assistant#67]
**Device normal info**
- Generic Brand
- Door/Window Sensor

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
like this:
{
  "result": {
    "active_time": 1625389986,
    "biz_type": 0,
    "category": "mcs",
    "create_time": 1625389986,
    "icon": "smart/icon/ay1562803410690AUgvL/69156044ad292c77ba9af1d74fb51da8.jpg",
    "id": "aaaaaaaaaaaaaaaa",
    "ip": "xxxxxxxxxx",
    "lat": "xxxxxxx",
    "local_key": "xxxxxxxxxxxxxx",
    "lon": "xxxxxxx",
    "name": "WIFI Door Sensor",
    "online": true,
    "owner_id": "9450177",
    "product_id": "y2zhupitkfazrfx3",
    "product_name": "WIFI Door Sensor",
    "status": [
      {
        "code": "doorcontact_state",
        "value": true
      },
      {
        "code": "battery_percentage",
        "value": 100
      }
    ],
    "sub": false,
    "time_zone": "xxxx",
    "uid": "xxxxxxxxxxxxxxxxx",
    "update_time": 1625391844,
    "uuid": "xxxxxxxxxxxxxxxxx"
  },
  "success": true,
  "t": 1625399102142
}

2021-07-04 21:43:37 DEBUG (SyncWorker_6) [tuya iot] Response: {
"result": {
"category": "mcs",
"functions": [],
"status": [
{
"code": "doorcontact_state",
"type": "Boolean",
"values": "{}"
},
{
"code": "battery_percentage",
"type": "Integer",
"values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
}
]
},
"success": true,
"t": 1625400817009
}

**Comment by tsutsuku** [comment]
@markusg1234  Try v1.3.1

**Comment by markusg1234** [comment]
Thankyou. It now works correctly.
