### ISSUE TITLE
Sensors are displayed but show an unsupported label

### ISSUE THREAD

**Issue by iMrLopez** [tuya/tuya-home-assistant#672]
So with the new version the sensors are now displayed (cool) but they are unsupported, is there any way to collaborate on adding support to my sensors?

![Screen Shot 2021-11-05 at 23 50 51](https://user-images.githubusercontent.com/8272737/140599497-9f8162fe-7003-4a00-9a8a-a866f8404952.png)

**Comment by frenck** [comment]
Home Assistant is an open source project. Anyone is welcome to open up a pull request that add support for new device categories to the Home Assistant Core Tuya integration.

**Comment by Ostoja1970** [comment]
+1 Zigbee door sensor "unsupported"

**Comment by iMrLopez** [comment]
I moved out of having Tuya devices in my install cause i decided to have everything local and not depend on anything cloud, closing this as i cannot contribute to the project and dont want to leave an open issue.
