### ISSUE TITLE
Tuya thermostat (climate) not reporting "current temperature" values

### ISSUE THREAD

**Issue by Kydonakis** [tuya/tuya-home-assistant#676]
**Describe the bug**
Tuya thermostat still not reporting "current temperature" values; it shows a "null" instead. I think I read somewhere it was about to get a fix on v.2011.11 but I suspect there is no progress. Is any?

**Screenshots**
![image](https://user-images.githubusercontent.com/71886113/140625043-0df4b2e7-6538-422a-a3b0-ed3bddafc9f0.png)

**Home Assistant Version**
2021.11.1

**Device info
{
  "result": {
    "active_time": 1599925303,
    "biz_type": 18,
    "category": "wk",
    "create_time": 1599925303,
    "name": "Thermostat",
    "online": true,
    "product_id": "IAYz2WK1th0cMLmL",
    "product_name": "thermostat",
    "status": [
      {
        "code": "switch",
        "value": true
      },
      {
        "code": "temp_set",
        "value": 34
      },
      {
        "code": "upper_temp",
        "value": 46
      },
      {
        "code": "eco",
        "value": false
      },
      {
        "code": "child_lock",
        "value": false
      }
    ],
    "sub": false,
    "time_zone": "+02:00",
    "update_time": 1636186094,
  },
  "success": true,
  "t": 1636215016652
}

**Device specifications
{
  "result": {
    "category": "wk",
    "functions": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "child_lock",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":10,\"max\":70,\"scale\":1,\"step\":5}"
      },
      {
        "code": "eco",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "upper_temp",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":5}"
      }
    ],
    "status": [
      {
        "code": "eco",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":10,\"max\":70,\"scale\":1,\"step\":5}"
      },
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "child_lock",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "upper_temp",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":5}"
      }
    ]
  },
  "success": true,
  "t": 1636215116305
}

**Comment by flayy73** [comment]
Any progress?

**Comment by richardcastle** [comment]
Exact same issue as described above. Log file dumps identical to what's been posted.
