### ISSUE TITLE
No entities or devices shown in the integration

### ISSUE THREAD

**Issue by esjani** [tuya/tuya-home-assistant#69]
**Describe the bug**
Setup was done through HACS, Tuya v2 can be added via the integration, but no devices or entities are available. In the Tuya IOT I can see all my devices under the project

**Expected behavior**
All devices which are shown ont the Tucya IOT are available under the Tuya V2 integration in HA

**Screenshots**
![210A321F-CD49-42A4-8B63-CD7A086E8C23](https://user-images.githubusercontent.com/48880245/124385935-2ebb3700-dcd8-11eb-9f0e-f63da6d605e4.jpeg)
![2C1FDA40-2E81-4B8E-BE34-A1FD62DBA086](https://user-images.githubusercontent.com/48880245/124385938-31b62780-dcd8-11eb-9b7c-bc4e4835864b.jpeg)

**Device info (please complete the following information, which can be found in [log]

Found this in the Core Log, maybe it helps:

[2021-07-04 14:27:22,168] [tuya-openmq] error while get mqtt config
2021-07-04 14:27:22 ERROR (Thread-3) [tuya iot] error while get mqtt config
2021-07-04 14:27:22 ERROR (Thread-3) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/site-packages/tuya_iot/openmq.py", line 173, in run
    time.sleep(self.mq_config.expireTime - 60)
AttributeError: 'TuyaOpenMQ' object has no attribute 'mq_config'

**Additional context**
Add any other context or logs about the problem here.

**Comment by tsutsuku** [comment]
@esjani Can you provide more logs?

**Comment by esjani** [comment]
Sure, can you please specify what you need!

**Comment by SgtBatten** [comment]
@esjani 

log tuya in more detail with this in configuration.yaml

```
logger:
  default: warning
  logs:
    custom_components.tuya_v2: debug
```

**Comment by tsutsuku** [comment]
@esjani Have you subscribed "Device status notification" in API
![WeChatWorkScreenshot_fb4e9c3b-2aa2-4a1e-8ae0-946fcdd9bcd5](https://user-images.githubusercontent.com/18442047/124412706-ae511080-dd81-11eb-9d15-f4c5d1315e88.png)

**Comment by schmurrie** [comment]
I have exactly the same issue, and I just can't figure it out. 

Tuya Iot project created 2 days ago
Smartlife account successfully linked to Iot account, and all devices showing under region "Europe" 

Installed integration through HACS and also tried manually 

Seems to install fine and log in "successfully" I set the region to "Europe" I'm in Australia and used +61 for country code

But no tuya icon and no devices are showing in HA 

Tried the install procedure 10 times now. No luck. 

Please help 

![image](https://user-images.githubusercontent.com/79039030/124454300-eaed2e00-ddba-11eb-8174-fdcd9259cabb.jpeg)

![image](https://user-images.githubusercontent.com/79039030/124454317-f0e30f00-ddba-11eb-968c-c71c3f674074.jpeg)
![image](https://user-images.githubusercontent.com/79039030/124454345-f80a1d00-ddba-11eb-9e2a-1c55f54d439b.jpeg)

**Comment by esjani** [comment]
> @esjani Have you subscribed "Device status notification" in API
> ![WeChatWorkScreenshot_fb4e9c3b-2aa2-4a1e-8ae0-946fcdd9bcd5](https://user-images.githubusercontent.com/18442047/124412706-ae511080-dd81-11eb-9d15-f4c5d1315e88.png)

Hey, thank you - I added the APIs and the devices showed up. If I am not mistaken, the install process should be updated, it was not obvious to me that I need those APIs…

Thanks again!

**Comment by SgtBatten** [comment]
i never had to subscribe manually. just checked and it seems to have been automatic.

**Comment by esjani** [comment]
For me it was completly empty. I had to subscribe and authorize all of the services manually.

**Comment by msrost** [comment]
So I had this same problem and I went and tried to match the services.The Smart Home Data Service is not in the list to add as an API either. I believe this may be the issue.

 Now the entities are showing up in my home assistant and I have them configured as a toggle, but when I click on the button, they fire one time and then do not update the icon or allow another click. It doesn't update or respond unless I restart my HA docker container: 

![Screenshot from 2021-10-06 19-50-28](https://user-images.githubusercontent.com/2001535/136298957-265a5177-108a-49aa-b91a-99a2f4710747.png)

**Comment by mkono87** [comment]
> Looks like I selected the incorrect Development Method when creating the project. I had to make a new project from scratch to get this to work properly.

Di's you choose custom instead?
