### ISSUE TITLE
Smart Blinds (unsupported) by Tuya

### ISSUE THREAD

**Issue by JmanNZ** [tuya/tuya-home-assistant#690]
**Describe the bug**
Smart Blinds showing as (unsupported) by Tuya

**Expected behavior**
To control the blinds

Device Information
Product Name Smart Blinds
Device ID 5303671024a160230b0e
Product Category cl

Json Debug
[
  {
    "code": "switch_1",
    "value": false
  },
  {
    "code": "percent_control",
    "value": 0
  }
]

Same issue is reported here https://github.com/home-assistant/core/issues/59158

**Comment by stevellion** [comment]
#652

**Comment by rackxp** [comment]
Hey Guys, 

Any updates on this one?

**Comment by JmanNZ** [comment]
I have installed 2021.12.6 and the blinds are now working

**Comment by frenck** [comment]
Glad the issue has been resolved 👍
