### ISSUE TITLE
Errors when detecting device - Diffuser

### ISSUE THREAD

**Issue by hiraniha** [tuya/tuya-home-assistant#70]
**Describe the bug**
When I add the integration I see the device correctly and it show 2 entities, but neither works the on/off or the light

**Expected behavior**
The on/off should switch the diffuser on/off and the light control has a rbg configuration in the Tuya App, there is also a Weak/Strong feature on the app, which doesn't appear in the integration, but that could be an enhacement

**Screenshots**

**Device info**
{
  "result": {
    "active_time": 1622787735,
    "biz_type": 0,
    "category": "jsq",
    "create_time": 1620455665,
    "icon": "smart/icon/1525845952fdp74cirr3t6okop58w0wl8fr_0.png",
    "id": "51082010e8db84cae16a",
    "ip": "121.218.43.37",
    "lat": "-33.7066982",
    "local_key": "34494dca012af695",
    "lon": "150.9078416",
    "model": "",
    "name": "Diffuser",
    "online": true,
    "owner_id": "31807239",
    "product_id": "6ASdNwe9IdaewQEl",
    "product_name": "Aromatherapy machine",
    "status": [
      {
        "code": "switch_spray",
        "value": true
      },
      {
        "code": "switch_led",
        "value": true
      },
      {
        "code": "mode",
        "value": "small"
      },
      {
        "code": "colour_data_hsv",
        "value": "{\"h\":214.0,\"s\":255.0,\"v\":255.0}"
      },
      {
        "code": "work_mode",
        "value": "white"
      },
      {
        "code": "moodlighting",
        "value": "1"
      },
      {
        "code": "bright_value",
        "value": 255
      }
    ],
    "sub": false,
    "time_zone": "+10:00",
    "uid": "eu16227858687542g6fx",
    "update_time": 1624966587,
    "uuid": "51082010e8db84cae16a"
  },
  "success": true,
  "t": 1625404767390
}

2021-07-04 23:14:34 ERROR (MainThread) [homeassistant.components.light] Error adding entities for domain light with platform tuya_v2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 615, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 404, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 796, in state_attributes
    color_mode = self._light_internal_color_mode
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 644, in _light_internal_color_mode
    if COLOR_MODE_HS in supported and self.hs_color is not None:
  File "/config/custom_components/tuya_v2/light.py", line 262, in hs_color
    s_range = self._tuya_hsv_s_range()
  File "/config/custom_components/tuya_v2/light.py", line 308, in _tuya_hsv_s_range
    return hsv_s.get("min", 0), hsv_s.get("max", 255)
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by tsutsuku** [comment]
@hiraniha  Can you provide the device's specification?

**Comment by hiraniha** [comment]
> @hiraniha Can you provide the device's specification?

IS this what you are refferring to?

{
  "result": {
    "category": "jsq",
    "functions": [
      {
        "code": "switch_led",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_spray",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "type": "Enum",
        "values": "{\"range\":[\"small\",\"large\"]}"
      },
      {
        "code": "colour_data_hsv",
        "type": "Json",
        "values": "{\"min\":0,\"unit\":\"\",\"scale\":0,\"max\":255,\"step\":1}"
      },
      {
        "code": "work_mode",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"colourful1\"]}"
      },
      {
        "code": "moodlighting",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\"]}"
      },
      {
        "code": "bright_value",
        "type": "Integer",
        "values": "{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch_led",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_spray",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "type": "Enum",
        "values": "{\"range\":[\"small\",\"large\"]}"
      },
      {
        "code": "colour_data_hsv",
        "type": "Json",
        "values": "{\"min\":0,\"unit\":\"\",\"scale\":0,\"max\":255,\"step\":1}"
      },
      {
        "code": "work_mode",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"colourful1\"]}"
      },
      {
        "code": "moodlighting",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\"]}"
      },
      {
        "code": "bright_value",
        "type": "Integer",
        "values": "{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1625440814907
}

**Comment by tsutsuku** [comment]
@hiraniha on/off is supported in v1.3.1.
And the light, there is some wrong with the product DP code. We will fix it soon.

**Comment by hiraniha** [comment]
I saw v1.3.1 pop up today, I'll upgrade and confirm if the on/off is resolved.

Look forward to the solution for the light

**Comment by hiraniha** [comment]
I can confirm on/off now works.

When I add to Lovelace, it looks like this.  The Humidity is redundant for a Diffuser really.

![image](https://user-images.githubusercontent.com/73940881/124414408-07c33a80-dd96-11eb-9c2e-142020236fe6.png)

The Tuya app actually has Modes : Strong, Weak and Off

When I select Weak, it shows On- small

![image](https://user-images.githubusercontent.com/73940881/124414621-6b4d6800-dd96-11eb-9466-d82bb22a28ea.png)

When I select Strong it show On - large

![image](https://user-images.githubusercontent.com/73940881/124414669-828c5580-dd96-11eb-81fa-b12f79521364.png)

But when I select off which comes after Strong, it continues to show On - large

![image](https://user-images.githubusercontent.com/73940881/124414739-9fc12400-dd96-11eb-82a7-d9808d85b4e6.png)
