### ISSUE TITLE
Smart Thermostat not unsupported - Moes Zigbee

### ISSUE THREAD

**Issue by alxnegrila** [tuya/tuya-home-assistant#713]
**Describe the bug**
Moes smart thermostat is unsupported through Home Assistant Tuya integrartion but it works on Tuya App.

**Expected behavior**
Support integration full functionality.

**Home Assistant Version**
- 2021.11.5

**Device info**

Product Name
Thermostat Valve
Device ID
bf25fce\*\*\*\*\*ef140ebtft
Product Category
wkf
Device Status
Online
Activated At
2021-11-23 19:49:40
Device Association
Project
SmartCasa
Association
\*@alxnegrila.\*\*
Data Center
Central Europe Data Center
Extension Information
Sub-Device or Not
Yes
IP Address
\-\-

All problematic devices
bf25fce\*\*\*\*\*ef140ebtft
bf28197\*\*\*\*\*bc7865ltfp
bf415b3\*\*\*\*\*e08ff24t1d
bf4fae2\*\*\*\*\*9d4592om07
bf57af0\*\*\*\*\*ca3ad6pl7g
bf693e6\*\*\*\*\*817fdcuioy

**Additional context**
All devices are of the same producer (Moes) and were added around same date

**Comment by p-jakub** [comment]
hi, i have same problem with 9 thermostats 'wkf' Moes  "Thermostat Valve (unsupported) producent: Tuya " . Clean Home assistant installation 2021.11.5, someone can fix the problem?

**Comment by jdanion** [comment]
Same here, I also have several HY368RT Zigbee thermostatic valves in my setup, whose product category is "wk" not "wkf" like Moes' valve, and it works. Is it a wrong category bug ?

**Comment by augard** [comment]
Same problem, Moes thermostat valve

**Comment by znidaxp** [comment]
Same here, I have 5 wk and 5 wkf. First half works in HA, other half Unsupported. Can we fix this? What needs to be done? I am willing to help if I can.

**Comment by frenck** [comment]
@znidaxp Home Assistant 2022.2 (will be released on Wednesday, Feb 2nd) has a new feature "Diagnostics".

It allows to dump diagnostics data for a device and share it. The information provided by that can be a help to implement new features, add support for new devices or fix issues.

Sharing that information will help a lot!

**Comment by znidaxp** [comment]
> @znidaxp Home Assistant 2022.2 (will be released on Wednesday, Feb 2nd) has a new feature "Diagnostics".
> 
> It allows to dump diagnostics data for a device and share it. The information provided by that can be a help to implement new features, add support for new devices or fix issues.
> 
> Sharing that information will help a lot!

I will dump it as soon as an update comes.

**Comment by augard** [comment]
I already have beta, so i hope it's this. [dianostics data](https://www.dropbox.com/s/vyw13059ih07gmz/tuya-a447440c516b1305e83446da0fdd4d34-Valve%204-606dc0fac29a898a9687b7fbc846da39.json.txt?dl=0)

**Comment by frenck** [comment]
Thanks, @augard 👍

That is really useful, on first glance, it would not be hard to add support for that one.

**Comment by Fougues** [comment]
has anyone found a solution?
thank you
