### ISSUE TITLE
Slow response from PIR to HA

### ISSUE THREAD

**Issue by hiraniha** [tuya/tuya-home-assistant#718]
**Describe the bug**
I have a powered PIR, that shows immediate state change in the Tuya App, but HA takes about 10 seconds to detect the same.  Therefore an automation waits about 10 seconds before turning on a light

**Expected behavior**
When I was testing with the Tuya V2 it was fast, but since HA brought it into HA Integrations there seems to be a different behaviour

**Screenshots**
n/a

**Home Assistant Version**
core-2021.11.5
supervisor-2021.10.8

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
like this:
{
  "result": {
    "active_time": 1625390602,
    "category": "pir",
    "category_name": "Motion Detector",
    "create_time": 1625390602,
    "gateway_id": "",
    "icon": "smart/icon/ay1536534747810ekKBj/33e050831a2f667fcae9bff8aa5ec73b.png",
    "id": "675063713c6105dd66f5",
    "ip": "101.180.23.20",
    "lat": "????",
    "local_key": "?????",
    "lon": "???",
    "model": "Starlux DET102HA",
    "name": "Garage Sensor",
    "online": true,
    "owner_id": "31807239",
    "product_id": "oapo5mmfbcr2y7ox",
    "product_name": "DET102HA",
    "sub": false,
    "time_zone": "+10:00",
    "update_time": 1637974505,
    "uuid": "675063713c6105dd66f5"
  },
  "success": true,
  "t": 1637987494028
}

**Comment by zlinoliver** [comment]
Hi @hiraniha the slow response issue has been improved, please check if it works now.

**Comment by hiraniha** [comment]
Hi @zlinoliver, just tested, that is much better now.  Light turns on immediately after hearing the internal rely in the PIR triggering.

Thanks for the quick fix.

**Comment by hiraniha** [comment]
I have noticed that quite often this sensor is not being picked up by HA, the Tuya app show the change in status fine, but HA doesn't see it, and automations then don't work.

If I restart HA or reload the Tuya integration it starts to work again, and then I don't know what triggers the issue but it stops again at some point.

**Comment by Cueball666uk** [comment]
I'm having this issue still (Feb 2022) ... Tuya PIR sensor not functioning in Home Assistant, but works well in the Tuya app, Also the state of all of my Tuya bulbs/LED controllers just not showing the correct state. Unfortunately no matter how much i appreciate the hard work that people put into home assistant. But because the majority of my devices are Tuya (stupid mistake) I think for now my home assistant venture is going on hold for a while. Back to simple Google Home/Tasker/Tuya app combo  for stable day to day use.
