### ISSUE TITLE
Tuya device found. No entities found.

### ISSUE THREAD

**Issue by Rubeast** [tuya/tuya-home-assistant#723]
**Describe the bug**
When adding the Tuya Integration, it sees my 1 device (Eurom Heater), but it does not have entities I can use.

**Expected behavior**
I should be able to control the device.

**Screenshots**
![image](https://user-images.githubusercontent.com/5304947/144761157-b942a7eb-8a95-4389-aa3f-9c5f7b68b53f.png)
![image](https://user-images.githubusercontent.com/5304947/144761389-25da60f3-52a9-4784-aa0a-3fbb8993796b.png)
![image](https://user-images.githubusercontent.com/5304947/144761396-dee49cf9-73fd-4462-9559-7ff259f709d3.png)
![image](https://user-images.githubusercontent.com/5304947/144761410-2c97a14f-0334-434b-8734-fb58c044c926.png)

**Home Assistant Version**
- core-2021.10.6 (docker)

**Additional context**
First time setting up Tuya.  Followed all the steps specified here: https://www.home-assistant.io/integrations/tuya/
It can find my device just fine. Just not showing any entitities.
When I go to the Tuya IoT Platform, choose my device there and go to Device Debugging, I can control the device just fine.
![image](https://user-images.githubusercontent.com/5304947/144761559-e0dae304-b7bf-4fa5-9bcc-5c07570bb717.png)

**Comment by rzrpt** [comment]
Same happens to the Tuya IR Temp/Humidity sensor (S06ProWB3S). I get it that you cant control IR devices, but you can read the temps and humidity values just fine from Tuya Cloud:

![image](https://user-images.githubusercontent.com/51623462/148680267-966c6890-6c7a-4b1d-9bc7-44ec0416b9e2.png)

**Comment by dimaperi** [comment]
same problem...
when i download the debug log from the integration i see the parameters.
but no entities and no option to control the device throw HA

**Comment by frenck** [comment]
Home Assistant 2022.2 was released.
Could you try upgrading to that version and see if the issue has been resolved?

If not, Home Assistant 2022.2 contains a new diagnostic tool. There is now a "Download Diagnostics" button on each Tuya device on the device page. Clicking that button will download diagnostics information for that specific device. Drag the downloaded file into this issue. It will help with finding out what the problem is.

**Comment by dimaperi** [comment]
Hi,
the version is up to date.
i upload the diagnostic info.
[tuya-ca1288b77252e25b32b0c473dbe26b39-HEAT PUMP-791c9ae7e3b8971aa2519bd0ed5f33d0.json (4).txt](https://github.com/tuya/tuya-home-assistant/files/8005195/tuya-ca1288b77252e25b32b0c473dbe26b39-HEAT.PUMP-791c9ae7e3b8971aa2519bd0ed5f33d0.json.4.txt)


thanks

**Comment by frenck** [comment]
@dimaperi Added support for it in <https://github.com/home-assistant/core/pull/65707>

**Comment by ikysek** [comment]
Hi i need too climate from tuya please.
