### ISSUE TITLE
Tuya portable AC returns true/false instead of c/f

### ISSUE THREAD

**Issue by ishioni** [tuya/tuya-home-assistant#725]
**Describe the bug**
My portable AC unit returns true/false for c_f instead of "c" or "f". This breaks the integration

**Expected behavior**
The device returns "c" or "f"

**Screenshots**

<img width="716" alt="Screenshot 2021-12-07 at 13 51 10" src="https://user-images.githubusercontent.com/50323052/145032196-42e699d9-1425-453e-8005-e4589793ba5b.png">

**Home Assistant Version**
- e.g. 2021.11.5

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
```
{
"active_time": 1624800048,
"biz_type": 0,
"category": "kt",
"create_time": 1624459589,
"icon": "smart/icon/1493368574_0.png",
"id": "4875044784cca893e465",
"ip": "***",
"lat": "***",
"local_key": "***",
"lon": "***",
"name": "Paulina AC",
"online": true,
"owner_id": "33144346",
"product_id": "jsf9spFEoWRFozCC",
"product_name": "Portable Air Conditioner",
"status": [
{
"code": "switch",
"value": true
},
{
"code": "mode",
"value": "wind"
},
{
"code": "temp_set",
"value": 25
},
{
"code": "windspeed",
"value": "1"
},
{
"code": "c_f",
"value": false
},
{
"code": "temp_set_f",
"value": 75
}
],
"sub": false,
"time_zone": "+01:00",
"uid": "***",
"update_time": 1638455288,
"uuid": "4875044784cca893e465"
}
```

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
```
"result": {
"category": "kt",
"functions": [
{
"code": "switch",
"type": "Boolean",
"values": "{}"
},
{
"code": "mode",
"type": "Enum",
"values": "{\"range\":[\"auto\",\"cold\",\"hot\",\"wet\",\"wind\"]}"
},
{
"code": "temp_set",
"type": "Integer",
"values": "{\"min\":13,\"unit\":\"℃\",\"scale\":0,\"max\":32,\"step\":1}"
},
{
"code": "windspeed",
"type": "Enum",
"values": "{\"range\":[\"1\",\"2\",\"3\",\"0\"]}"
},
{
"code": "c_f",
"type": "Enum",
"values": "{\"range\":[\"C\",\"F\"]}"
},
{
"code": "temp_set_f",
"type": "Integer",
"values": "{\"unit\":\"℉\",\"min\":55,\"max\":90,\"scale\":0,\"step\":1}"
}
],
"status": [
{
"code": "switch",
"type": "Boolean",
"values": "{}"
},
{
"code": "temp_set",
"type": "Integer",
"values": "{\"min\":13,\"unit\":\"℃\",\"scale\":0,\"max\":32,\"step\":1}"
},
{
"code": "c_f",
"type": "Enum",
"values": "{\"range\":[\"C\",\"F\"]}"
},
{
"code": "windspeed",
"type": "Enum",
"values": "{\"range\":[\"1\",\"2\",\"3\",\"0\"]}"
},
{
"code": "mode",
"type": "Enum",
"values": "{\"range\":[\"auto\",\"cold\",\"hot\",\"wet\",\"wind\"]}"
},
{
"code": "temp_set_f",
"type": "Integer",
"values": "{\"unit\":\"℉\",\"min\":55,\"max\":90,\"scale\":0,\"step\":1}"
}
]
},
"success": true,
"t": 1638881620699
}
```

**Additional context**
I wrote about this in #15 and was told by @tsutsuku this was a server-side change. Right now I modify the component manually in code, but would like it if it would work out of the box

**Comment by frenck** [comment]
Yesterday, Home Assistant 2022.2 was released.
Could you try upgrading to that version and see if the issue has been resolved?

If not, Home Assistant 2022.2 contains a new diagnostic tool. There is now a "Download Diagnostics" button on each Tuya device on the device page. Clicking that button will download diagnostics information for that specific device. Drag the downloaded file into this issue. It will help with finding out what the problem is.

**Comment by ishioni** [comment]
@frenck Right, i forgot about this! It's been working since your neat patch in 2021.12.9 :)

**Comment by frenck** [comment]
Awesome, thanks for letting me know 👍
