### ISSUE TITLE
Login error (1109): param is illegal ,please check it

### ISSUE THREAD

**Issue by souravj96** [tuya/tuya-home-assistant#738]
I'm facing 1109 param is illegal issue while setting up tuya integration in home assistant.
while my tuya IoT development project is in India Data Center, my tuya app account is in the India region.
I tried changing the app account password.
nothing is working.
and also while I link my tuya app account to the tuya IoT development project, it's showing 0 devices.

![Home assistant issue](https://user-images.githubusercontent.com/52346695/146358605-dd744b73-c380-424c-b4c8-3932cc55c2fb.png)

![tuya IoT project](https://user-images.githubusercontent.com/52346695/146358757-ec0eca68-fee7-4707-877f-a42751e4b62c.png)

![account details of tuya app](https://user-images.githubusercontent.com/52346695/146359108-4f5147e3-ae74-4fa8-ae99-5bd2888b087b.jpg)

![All devices on tuya app](https://user-images.githubusercontent.com/52346695/146359628-9ee0eeb1-9b0d-4355-9169-5eb2a4eb75b8.PNG)

Home Assistant Version | core-2021.12.2
-- | --
Installation Type | Home Assistant OS

**Comment by souravj96** [comment]
this issue got resolved after replacing the tuya it account

**Comment by copetogo** [comment]
I am still having this 1109 param is illegal issue. what do you mean replacing the tuya iot account.My data center is central europe while country is india as my app login country. although my devices appear in the iot but the tuya integration in HA is not working due to this error

> this issue got resolved after replacing the tuya iot account

**Comment by arpith20** [comment]
I'm facing the same issue. @souravj96 could you please elaborate on what did you do to fix this?

**Comment by copetogo** [comment]
> 
while configuring in HA just change the country to any other except India. in my case i just randomly put afghanistan  and it worked

**Comment by arpith20** [comment]
@copetogo Thanks! That worked!

**Comment by pintoeu** [comment]
the Tuya account used to create the Cloud Project must be different from the Tuya account used to link devices to the mobile app.

If the same Tuya account used for the mobile app is used to create the cloud project, an error is received while adding integration in Home Assistant ( Login error (1109): param is illegal).

**Comment by beckdac** [comment]
> the Tuya account used to create the Cloud Project must be different from the Tuya account used to link devices to the mobile app.
> 
> If the same Tuya account used for the mobile app is used to create the cloud project, an error is received while adding integration in Home Assistant ( Login error (1109): param is illegal).

I can confirm the 1109 is if the same account name (i.e., email) is used.

It still isn't working for me, but when I deleted the mobile app account and created a new one using a different email I no longer got the 1109.  (I have a different error code, but I'm not going to pollute this comment.)

**Comment by copetogo** [comment]
> > the Tuya account used to create the Cloud Project must be different from the Tuya account used to link devices to the mobile app.
> > If the same Tuya account used for the mobile app is used to create the cloud project, an error is received while adding integration in Home Assistant ( Login error (1109): param is illegal).
> 
> I can confirm the 1109 is if the same account name (i.e., email) is used.
> 
> It still isn't working for me, but when I deleted the mobile app account and created a new one using a different email I no longer got the 1109. (I have a different error code, but I'm not going to pollute this comment.)

I don't think it in issue with tuya account but rather than the country you are selecting . Try selecting afganistan or any other random country . i know it like a bit of hitting in dark but it worked with the same account which i sbeing used to configure tuya account
