### ISSUE TITLE
Wifi Temperature Humidity Sensor MIR-TE200 not updated

### ISSUE THREAD

**Issue by Richard7325** [tuya/tuya-home-assistant#74]
**Describe the bug**
Wifi Temperature Humidity Sensor MIR-TE200 not updated.

Initial value was as in the tuya smart app. But not updates when the temperature changes. Change are visible in the  tuya smart app

**Expected behavior**
Home assistant temperature same as tuya app. 

Version 1.3.1

**Comment by tsutsuku** [comment]
@Richard7325 Can you provide the log?

**Comment by Richard7325** [comment]
I dont see any log.

**Comment by Richard7325** [comment]
With the device notification api on lts working.
