### ISSUE TITLE
Fanco DC Fan Support

### ISSUE THREAD

**Issue by sumur1au** [tuya/tuya-home-assistant#745]
The fan is added to Home Assistant but it is unavailable, the fan is powered on and can be controlled by the Tuya IoT platform. 

**Device normal info**
- Fanco
- Infinity-iD DC

**Device info**

2021-12-22 18:13:24 ERROR (MainThread) [homeassistant.components.fan] Error while setting up tuya platform for fan
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 540, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 630, in state_attributes
data[ATTR_SPEED] = self.speed
File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 468, in speed
if self._implemented_preset_mode and (preset_mode := self.preset_mode):
File "/usr/src/homeassistant/homeassistant/components/tuya/fan.py", line 165, in preset_mode
return self.device.status[DPCode.MODE]
KeyError: <DPCode.MODE: 'mode'>

**Device specifications :**

{
  "result": {
    "category": "fs",
    "functions": [
      {
        "code": "switch",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_speed_percent",
        "lang_config": {
          "unit": ""
        },
        "name": "Wind Speed Level",
        "type": "Integer",
        "values": "{\"min\":1,\"max\":6,\"scale\":0,\"step\":1}"
      },
      {
        "code": "light",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Light",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "bright_value",
        "lang_config": {
          "unit": ""
        },
        "name": "Brightness",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_value",
        "lang_config": {
          "unit": ""
        },
        "name": "Color Temperature",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_speed_percent",
        "lang_config": {
          "unit": ""
        },
        "name": "Wind Speed Level",
        "type": "Integer",
        "values": "{\"min\":1,\"max\":6,\"scale\":0,\"step\":1}"
      },
      {
        "code": "light",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Light",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "bright_value",
        "lang_config": {
          "unit": ""
        },
        "name": "Brightness",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_value",
        "lang_config": {
          "unit": ""
        },
        "name": "Color Temperature",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1640157503986
}

**Comment by frenck** [comment]
Yesterday, Home Assistant 2022.2 was released.
Could you try upgrading to that version and see if the issue has been resolved?

If not, Home Assistant 2022.2 contains a new diagnostic tool. There is now a "Download Diagnostics" button on each Tuya device on the device page. Clicking that button will download diagnostics information for that specific device. Drag the downloaded file into this issue. It will help with finding out what the problem is.

**Comment by sumur1au** [comment]
@frenck 

Your changes to the fan code has fixed this issue. Many thanks. 

The only issue I have now is the states in Tuya not being updated without reloading the integration.
