### ISSUE TITLE
Blinds that direction is set to reversed in app reports incorrectly in HA

### ISSUE THREAD

**Issue by mrulke** [tuya/tuya-home-assistant#773]
When the curtains are down/closed, the only button that I can push is the close and stop button. Also vice versa.

In the Tuya Smart app, the status of the curtains is correct.
I do notice that in the app the % is 0 for closed and on a no reversed motor the % is 100 for closed.
this is for these blinds

https://www.aliexpress.com/item/4000170174017.html?spm=a2g0o.9042311.0.0.27424c4ddsARdb

**Comment by men9xuan** [comment]
Not just reversed all curtain motors show reversed in Home Kit
