### ISSUE TITLE
Dehumidifier not supported

### ISSUE THREAD

**Issue by mortendok** [tuya/tuya-home-assistant#774]
**Describe the bug**
Using the Tuya integration in Home Assistant.
Adding the Tuya account and linking to the app works fine (in Home Assistant - integration).
In the Integrations under Tuya when viewing the devices it says "Dehumidifier (unsupported)"

Home Assistant Version
Core_2021.12.10
Supervisor-2021.12.2

Tuya Service API
IOT Core
Authorization
Smart Home Scene Linkage
Data Dashboard Service
Device Status Notification
![Tuya1](https://user-images.githubusercontent.com/25794116/151191077-62786e54-cb27-4ab6-b738-6144eb815ab5.GIF)

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
like this:
I do not the the suggested output. I only get the errorlog (see futher down)

**Additional context**
2022-01-26 15:50:34 ERROR (MainThread) [homeassistant.components.humidifier] Error while setting up tuya platform for humidifier
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/usr/src/homeassistant/homeassistant/components/tuya/humidifier.py", line 72, in async_setup_entry
async_discover_device([*hass_data.device_manager.device_map])
File "/usr/src/homeassistant/homeassistant/components/tuya/humidifier.py", line 68, in async_discover_device
TuyaHumidifierEntity(device, hass_data.device_manager, description)
File "/usr/src/homeassistant/homeassistant/components/tuya/humidifier.py", line 114, in __init__
self._attr_min_humidity = int(type_data.min_scaled)
File "/usr/src/homeassistant/homeassistant/components/tuya/base.py", line 39, in min_scaled
return self.scale_value(self.min)
File "/usr/src/homeassistant/homeassistant/components/tuya/base.py", line 48, in scale_value
return value * 1.0 / (10 ** self.scale)
TypeError: can't multiply sequence by non-int of type 'float'

**Comment by frenck** [comment]
This bug should be resolved in Home Assistant 2022.2.

If you are up for it, you could try the Home Assistant beta for 2022.2, which is now available.

**Comment by mortendok** [comment]
I have updated to core-2022.2.0b1, supervisor-2022.01.0.

I can now see the dehumidifier - nice 👍
In the Integrations under Tuya I can now see 1 device and 1 entity. 


However I can not see the humidity right now (see picture below). I do not know if that is a bug or not.

![image](https://user-images.githubusercontent.com/25794116/151560533-2a4b0d07-4607-4849-9607-afd6ae6b9129.png)

**Comment by mortendok** [comment]
I have done a test now.

It show (like above), but is not working. Can not turn it on/off or set the humidity. 

`Logger: homeassistant.components.websocket_api.http.connection
Source: components/tuya/humidifier.py:153
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 15.09.23 (2 occurrences)
Last logged: 16.03.29

[1762663200] Cannot set humidity, device doesn't provide methods to set it
[1746032624] Cannot set humidity, device doesn't provide methods to set it
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 190, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1630, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1667, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 921, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/humidifier/__init__.py", line 201, in async_set_humidity
    await self.hass.async_add_executor_job(self.set_humidity, humidity)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/tuya/humidifier.py", line 153, in set_humidity
    raise RuntimeError(
RuntimeError: Cannot set humidity, device doesn't provide methods to set it
`

**Comment by frenck** [comment]
On the device page (in the latest beta) there is a "download diagnostics" button.

Could you guys share those diagnostics?

**Comment by mortendok** [comment]
No problem - however I do not know how to find the device page. I have been looking, but can not finde any "download diagnostics" anywhere.

Running core-2022.2.0b2

**Comment by frenck** [comment]
Configuration -> Devices & Services -> Devices tab -> Search device and click on it.

**Comment by mortendok** [comment]
Allright - there is no "download diagnostics" button.
![image](https://user-images.githubusercontent.com/25794116/151656628-d50a97df-4547-45b2-a21c-8f7981c77ce7.png)

**Comment by frenck** [comment]
In that case, you are not running the latest  beta as I mentioned in my initial comment

**Comment by mortendok** [comment]
I am running the latest beta as far as I know - see screenshot
![image](https://user-images.githubusercontent.com/25794116/151715939-6f5d8754-a429-4a4e-b143-126ffab7f86e.png)

**Comment by frenck** [comment]
Than it should have a download diagnostics button on the device page. Are you sure you are not running Tuya as a custom integration/custom component?

**Comment by mortendok** [comment]
What I did:
Configuration -> Devices & Services -> + ADD INTEGRATION (Blue button) -> Tuya (selected from the list)

**Comment by frenck** [comment]
The 2022.2.0 beta has diagnostics, we have received many already.

I am not sure what you are running, looking at or why it doesn't show for you; however, it will be hard to diagnose this problem without that information

**Comment by mortendok** [comment]
Hmm - have been running Home Assistant on the same RPI3 for a long time - never gave any trouble before now. Not sure I want to reinstall from scratch - giving it a thought though.

Thanks for you time.

**Comment by frenck** [comment]
Reinstallation is never a solution.

**Comment by mortendok** [comment]
If reinstall is not a solution - where do I start to look for a solution on the missing button? Have been looking in the logs - but found nothing.

**Comment by frenck** [comment]
> where do I start to look for a solution on the missing button?

I really don't know how your system is set up. Home Assistant 2022.2 was released as stable yesterday, try upgrading to that?

**Comment by sambeetm** [comment]
@frenck I have the exact same issue. The tuya de-humidifier is not working. No on/off. It shows temperature...Here is the diagnostics file.
[tuya-dbc5ad24f4465821270a6144f91f548e-Basement Dehumidifier-85a76a160db348c094c941f482f4c9fe.json.txt](https://github.com/tuya/tuya-home-assistant/files/7998175/tuya-dbc5ad24f4465821270a6144f91f548e-Basement.Dehumidifier-85a76a160db348c094c941f482f4c9fe.json.txt)

**Comment by frenck** [comment]
@sambeetm If you look at the diagnostics file, you'll find function and status fields. The Tuya only provided temperature and wind speed for your devices, thus the result in Home Assistant you are describing sounds correct.

If you think that is incorrect, I would recommend on submitting an support ticket directly to Tuya, by logging in into your Tuya IoT account.

**Comment by mortendok** [comment]
@frenck in core-2022.2.3 I got the diagnostics button. My files is somewhat different from sambeetm.

If I understand the file, I should be able to read/set eg. fanspeed and the humidity-level (dehumidify_set_value)
```
    "status": {
      "switch": true,
      "dehumidify_set_value": 45,
      "fan_speed_enum": "low",
      "humidity_indoor": 47
```

however it do not show up in the devoloper tool (see screen shot)

![Tuya2](https://user-images.githubusercontent.com/25794116/152759546-de186b2f-c734-4f49-bdae-31ee8e7de8ea.GIF)

[tuya-1ca683c9d3cd447b3369fe341ae5ce12-Affugter-0d44b02a90afa1ce6a858899a8107804.json (1).txt](https://github.com/tuya/tuya-home-assistant/files/8013820/tuya-1ca683c9d3cd447b3369fe341ae5ce12-Affugter-0d44b02a90afa1ce6a858899a8107804.json.1.txt)

**Comment by frenck** [comment]
The Home Assistant humidifier does not support setting fan speeds. Thus that won't indeed not show.
