### ISSUE TITLE
Kogan Portable Aircon - Multiple Issues

### ISSUE THREAD

**Issue by sambarlick** [tuya/tuya-home-assistant#778]
**Describe the bug**
1. Current Temperature value no longer being imported to HA.
2. Fan control speed not available in HA.
3. HVAC modes displayed incorrectly in HA. When AirCon is in Dry (dehumidy) HA displays HVAC mode as heat.

**Expected behavior**
1. Current temperature sensor to be visible in HA.
2. Fan Control to be available in HA.
3. HVAC mode correctly identified in HA.

**Screenshots**

![Screenshot_20220201-112945](https://user-images.githubusercontent.com/47462284/151918927-d9f8fa58-8f08-496b-90e1-40648dcba44f.png)

![Screenshot_20220201-112732](https://user-images.githubusercontent.com/47462284/151918935-05114582-395d-4225-bec6-16bc27e7701e.png)
ae1.png)

![Screenshot_20220201-112744](https://user-images.githubusercontent.com/47462284/151919771-2936002d-1886-4b86-aaa3-c424358ce44a.png)

**Home Assistant Version**
- 2022. 2.0b4

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
like this:
{
    {
  "result": {
    "active_time": 1643671277,
    "biz_type": 18,
    "category": "kt",
    "create_time": 1639201912,
    "icon": "smart/icon/ay15253387844269Sg99/e5ee4cdd52c1a86220bfad2a47605b52.png",
    "id": "655401068caab5e3d49e",
    "ip": "xxxxx",
    "lat": "-xxx",
    "local_key": "xxxx",
    "lon": "xxx",
    "model": "KAWFPAC16PYA",
    "name": "Aircon",
    "online": true,
    "owner_id": "xxx",
    "product_id": "1z9vbwsgpmsrhuha",
    "product_name": "Kogan Smart PAC_PY16 ",
    "status": [
      {
        "code": "switch",
        "value": true
      },
      {
        "code": "temp_set",
        "value": 22
      },
      {
        "code": "temp_current",
        "value": 24
      },
      {
        "code": "mode",
        "value": "hot"
      },
      {
        "code": "windspeed",
        "value": "1"
      },
      {
        "code": "c_f",
        "value": "C"
      }
    ],
    "sub": false,
    "time_zone": "+10:00",
    "uid": "eu1589623177329OFGIL",
    "update_time": 1643671441,
    "uuid": "655401068caab5e3d49e"
  },
  "success": true,
  "t": 1643694846111
}

**Additional context**
Add any other context or logs about the problem here.

**Comment by frenck** [comment]
Yesterday, Home Assistant 2022.2 was released.
Could you try upgrading to that version and see if the issue has been resolved?

If not, Home Assistant 2022.2 contains a new diagnostic tool. There is now a "Download Diagnostics" button on each Tuya device on the device page. Clicking that button will download diagnostics information for that specific device. Drag the downloaded file into this issue. It will help with finding out what the problem is.

**Comment by sambarlick** [comment]
Hi Frenck,

Thanks for your reply. 

I'm now on 2022.2, here are the diagnostics.
[tuya-b8cdc72214a1d97a96321b11889b2984-Aircon-c52ee842aea86afdc17948f06afa0850.json.txt](https://github.com/tuya/tuya-home-assistant/files/7993045/tuya-b8cdc72214a1d97a96321b11889b2984-Aircon-c52ee842aea86afdc17948f06afa0850.json.txt)

My fans now work but as I said there is no fan speed control in the aircon.

Hopefully the logs help.
If you need anything else, let me know.

Thanks,
Sam

**Comment by frenck** [comment]
Thanks for those diagnostics @sambarlick! That was really helpful.

I've opened up a pull request to address the issue here: <https://github.com/home-assistant/core/pull/65511>

**Comment by sambarlick** [comment]
No problem Frenck. Seems much easier with the new download diagnostic tool.

Sam

**Comment by frenck** [comment]
> Seems much easier with the new download diagnostic tool.

Its a blessing really 🙏
