### ISSUE TITLE
no low and high switch for Flinq panel heater

### ISSUE THREAD

**Issue by Loob123** [tuya/tuya-home-assistant#789]
**Describe the bug**

In HA the integration does not seem to support the low and high setting that is available in Tuya Smart.
Only heat and power off can be selected in e.g. an automation.

**Expected behavior**

At the moment, HA reads the produced  power of  my solar panels  from the P1-port and switches on the panel heater at a certain level. 
It would be great to be able to switch between high and low automatically.

**Diagnostics for integrations and devices**

You can download the diagnostics text file by clicking the "Download diagnostics" button in (Configuration -> Integrations -> Tuya Integration -> lower right button), please check the image below:

<img src="https://user-images.githubusercontent.com/907831/152950135-320e9ea2-45bc-4d80-b961-0db8eb9c7ae5.png" alt="image" width="250"/>

**Screenshots** from Tuya Smart:
![image](https://user-images.githubusercontent.com/102522355/160389043-3d05af30-dfbe-4c48-841e-c3a0c711f97c.png)
![image](https://user-images.githubusercontent.com/102522355/160389445-010e9a7e-86a1-4f12-81f9-12551d2a2fc2.png)

**Home Assistant Version**
- e.g. 2022.2.3

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**

like this:

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**

action:
  - device_id: ***
    domain: climate
    entity_id: climate.flinq_panel_heater
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: parallel
  max: 10

**Additional context**

Add any other context or logs about the problem here.

**Comment by Odinlistening** [comment]
This a dead thread - but did you ever get anywhere with this? I am looking to access the same element.

**Comment by Loob123** [comment]
No, 
I still switch manually between high and low.
The chat I had with Flinq with the technical explanation about this is not accessible anymore I'm afraid.

**Comment by MartijnJa** [comment]
I had the same issue and I am also hoping to integrate my Flinq panel heater into Home Assistant. The Smart Life app on my phone was able to change the status between on/off and Eco, comfort and antifrost settings in parallel to home assistant only switching on/off. 
It should therefore be possible in Home Assistant as well, but I don't understand any of the coding yet or how to copy-paste things in the right place on my Raspberry Pi 4. Simply cannot find files other than .yaml and such or even why my changes to these files don't show what I intended. :-)

**Comment by Loob123** [comment]
> I had the same issue and I am also hoping to integrate my Flinq panel heater into Home Assistant. The Smart Life app on my phone was able to change the status between on/off and Eco, comfort and antifrost settings in parallel to home assistant only switching on/off. It should therefore be possible in Home Assistant as well, but I don't understand any of the coding yet or how to copy-paste things in the right place on my Raspberry Pi 4. Simply cannot find files other than .yaml and such or even why my changes to these files don't show what I intended. :-)

Hi, I recovered the conversation with the Tuya engineer. He writes: "I checked the function points of the device, "low and high" are the values customized by the device manufacturer <Flinq>, which do not conform to Tuya Cloud's standard command/status set, so Open API and Homeassitant cannot get it."
