### ISSUE TITLE
产品开通失败

### ISSUE THREAD

**Issue by evlo** [tuya/tuya-home-assistant#815]
I get error 产品开通失败 (Product activation failed) when I try to register cloud service for **IoT Core** and since _IoT Core provides the fundamental device connection_ I can't connect my devices.

![image](https://user-images.githubusercontent.com/8813196/173866346-0714d6c1-f28f-4a78-9eb4-789a1ea632fb.png)

Please help.

And just for fun if I try to start the trial
![image](https://user-images.githubusercontent.com/8813196/173865475-e0e75a95-ea41-461a-8209-61e5063ea2d3.png)

I have checked
https://developer.tuya.com/en/docs/iot/applying-for-api-group-permissions?id=Ka6vf012u6q76#title-2-Subscribe%20to%20cloud%20products

https://developer.tuya.com/en/docs/iot/applying-for-api-group-permissions?id=Ka6vf012u6q76#title-3-Authorize%20projects%20to%20call%20the%20cloud%20product

and i the steps i can access i get the same error

maybe this can help you?
![image](https://user-images.githubusercontent.com/8813196/173873849-bc276f69-408e-407d-a6ab-4ff7713f20e6.png)

{"login":true,"t":1655309801057,"success":false,"errorCode":"API_PROJECT_OPEN_FAILED","status":"error","errorMsg":"API产品开通失败"}

**Comment by JonathanKarstrom** [comment]
I'm having the same issue. When i try to buy the service thorugh the service store https://www.tuya.com/vas/commodity/IOT_CORE_V2 I get a error message "Service has been delisted".

**Comment by evlo** [comment]
It now works, i guess it was just a fluke in the service
