### ISSUE TITLE
New device support -> Blitzwolf BW-FUN3

### ISSUE THREAD

**Issue by Jhonattan-Souza** [tuya/tuya-home-assistant#84]
**Device normal info**
- Brand BlitzWolf
- Model BW-FUN3

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):** like this:
```
{
   "active_time":1617574645,
   "biz_type":18,
   "category":"xxj",
   "create_time":1608581576,
   "icon":"smart/icon/ay1506337792739cXrIR/5d779ee65c541e0a351db6dc01da4720.jpg",
   "id":"734305088caab5f0fee0",
   "ip":"168.194.164.90",
   "lat":"",
   "local_key":"f4c01d31433175c4",
   "lon":"",
   "name":"BW-FUN3",
   "online":true,
   "owner_id":"11596570",
   "product_id":"6dwaaq5egthwitlb",
   "product_name":"BW-FUN3",
   "status":[
      {
         "code":"switch_spray",
         "value":false
      },
      {
         "code":"mode",
         "value":"small"
      }
   ],
   "sub":false,
   "time_zone":"-03:00",
   "uid":"az1576125271010d3j7N",
   "update_time":1625085721,
   "uuid":"734305088caab5f0fee0"
}
```

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
```
{
   "category":"xxj",
   "functions":[
      {
         "code":"switch_spray",
         "type":"Boolean",
         "values":"{}"
      },
      {
         "code":"mode",
         "type":"Enum",
         "values":"{\"range\":[\"large\",\"small\"]}"
      }
   ],
   "status":[
      {
         "code":"switch_spray",
         "type":"Boolean",
         "values":"{}"
      },
      {
         "code":"mode",
         "type":"Enum",
         "values":"{\"range\":[\"large\",\"small\"]}"
      }
   ]
},
"success":true,
"t":1625437526216
}
```

**Comment by Jhonattan-Souza** [comment]
I'm trying to add light capacity to the diffuser, but this error ocurrs with this request

Request:
{
   "commands":[
      {
         "code":"switch_led",
         "value":true
      }
   ]
}

Response:
{
   "code":2008,
   "msg":"command or value not support",
   "success":false,
   "t":1625522202845
}

**Comment by freitas666** [comment]
@Jhonattan-Souza back to Home Assistant Brasil bro kkkkk by L.FREITAS99 <3

**Comment by tsutsuku** [comment]
@Jhonattan-Souza

**Comment by tsutsuku** [comment]
@Jhonattan-Souza

**Comment by tsutsuku** [comment]
@Jhonattan-Souza 
This device needs to standardize, so light capacity will be enabled. we will fix it soon.

**Comment by Jhonattan-Souza** [comment]
@tsutsuku Any news on the standardize of this device? Thanks!

**Comment by tsutsuku** [comment]
@Jhonattan-Souza  It's fixed, try again.

**Comment by Jhonattan-Souza** [comment]
Thanks @tsutsuku ! I'm wrapping up everything to send the pull request.
