### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'int' and 'str'

### ISSUE THREAD

**Issue by galtamur** [tuya/tuya-home-assistant#851]
After migrating to HA Core 2022.9.7 (on docker-debian) the Tuya integration cannot setup and i see this error in the log:

Logger: homeassistant.config_entries
Source: components/tuya/__init__.py:79
First occurred: 9:35:56 AM (1 occurrences)
Last logged: 9:35:56 AM

Error setting up entry giuliano@altamuraonline.net for tuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/tuya/__init__.py", line 79, in async_setup_entry
    response = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/tuya_iot/openapi.py", line 222, in connect
    self.token_info = TuyaTokenInfo(response)
  File "/usr/local/lib/python3.10/site-packages/tuya_iot/openapi.py", line 41, in __init__
    token_response.get("t", 0)
TypeError: unsupported operand type(s) for +: 'int' and 'str'

Any help?

**Comment by buurman** [comment]
I've got the exact same issue since this morning after a restart of the HA server.

**Comment by MathieuDebouvries** [comment]
Hello. I have exactly the same issue.

I tried creating a new tuya project. Changing my password. Disabled the integration. Etc...

**Comment by dulantha-p** [comment]
Seeing the same thing, no changes to config. 
Just stopped working after a scheduled restart. 
Could be a server side issue?

**Comment by shreyashag** [comment]
I am just get something less janky than this. Seems like devs updated their APIs

**Comment by neildsb** [comment]
nothing changed my end, and the app works, looks like a server end change?

Logger: homeassistant.config_entries
Source: config_entries.py:1073
First occurred: 10:07:31 am (1 occurrences)
Last logged: 10:07:31 am

Config entry 'Tuya' for tuya integration not ready yet: {'code': 2406, 'msg': 'skill id invalid', 'success': False, 't': ***********, 'tid': '*************'}; Retrying in background

**Comment by galtamur** [comment]
I managed to solve the problem:
1. edit the openapi.py file in /usr/local/lib/python3.10/site-packages/tuya_iot
2. modify instruction in line 41-42 
    from:
        token_response.get("t", 0)
        + result.get("expire", result.get("expire_time", 0)) * 1000
    to:
        token_response.get("t", 0)
        + int(result.get("expire", result.get("expire_time", 0)) * 1000)

Looks working now (need to restart the docker to read the modified file).
Comments?

**Comment by defsix** [comment]
Thanks, 
Where is this located ? 
 /usr/local/lib/python3.10/site-packages/tuya_iot
I don't see this in my docker install

**Comment by dulantha-p** [comment]
inside the container image /usr/local/lib/python3.10/site-packages/tuya_iot/openapi.py

**Comment by dulantha-p** [comment]
My solution similar to @galtamur I changed lines 39-42 in openapi.py from this:
```
        self.expire_time = (
            token_response.get("t", 0)
            + result.get("expire", result.get("expire_time", 0)) * 1000
        )
```
to this:
```
        self.expire_time = (
            int(token_response.get("t", 0))
            + int(result.get("expire", result.get("expire_time", 0))) * 1000
        )
```
and put a copy of the patched file in a subdirectory where my Dockerfile lives _patch/openapi.py_

Here is my Dockerfile:
```
FROM ghcr.io/home-assistant/home-assistant:stable
COPY patch/openapi.py /usr/local/lib/python3.10/site-packages/tuya_iot/openapi.py
```

**Comment by harro2400** [comment]
how would i make this change in HASS OS?

**Comment by SKiV000** [comment]
> inside the container image /usr/local/lib/python3.10/site-packages/tuya_iot/openapi.py

I don't have such a file, what should I do?

```
[core-ssh ~]$ cd /usr/local/lib
[core-ssh lib]$ ls -l
total 49516
-rwxr-xr-x    1 root     root      22397664 Aug  2 16:46 libjemalloc.a
lrwxrwxrwx    1 root     root            16 Aug  2 16:46 libjemalloc.so -> libjemalloc.so.2
-rwxr-xr-x    1 root     root       5887272 Aug  2 16:46 libjemalloc.so.2
-rwxr-xr-x    1 root     root      22407794 Aug  2 16:46 libjemalloc_pic.a
drwxr-xr-x    2 root     root          4096 Aug  2 16:46 pkgconfig
[core-ssh lib]$
```

**Comment by galtamur** [comment]
> > inside the container image /usr/local/lib/python3.10/site-packages/tuya_iot/openapi.py
> 
> I don't have such a file, what should I do?
> 
> ```
> [core-ssh ~]$ cd /usr/local/lib
> [core-ssh lib]$ ls -l
> total 49516
> -rwxr-xr-x    1 root     root      22397664 Aug  2 16:46 libjemalloc.a
> lrwxrwxrwx    1 root     root            16 Aug  2 16:46 libjemalloc.so -> libjemalloc.so.2
> -rwxr-xr-x    1 root     root       5887272 Aug  2 16:46 libjemalloc.so.2
> -rwxr-xr-x    1 root     root      22407794 Aug  2 16:46 libjemalloc_pic.a
> drwxr-xr-x    2 root     root          4096 Aug  2 16:46 pkgconfig
> [core-ssh lib]$
> ```

May happen that the problem is that you should search INSIDE the docker; could be?

**Comment by SKiV000** [comment]
> May happen that the problem is that you should search INSIDE the docker; could be?

tell a beginner how to do it?

**Comment by Zingrock** [comment]
> > May happen that the problem is that you should search INSIDE the docker; could be?
> 
> tell a beginner how to do it?

Seems like its an issue for everyone - i.e. server side  
I'm going to wait a few hours and hope they fix with an update

**Comment by riccardo-runci** [comment]
> > inside the container image /usr/local/lib/python3.10/site-packages/tuya_iot/openapi.py
> 
> I don't have such a file, what should I do?
> 
> ```
> [core-ssh ~]$ cd /usr/local/lib
> [core-ssh lib]$ ls -l
> total 49516
> -rwxr-xr-x    1 root     root      22397664 Aug  2 16:46 libjemalloc.a
> lrwxrwxrwx    1 root     root            16 Aug  2 16:46 libjemalloc.so -> libjemalloc.so.2
> -rwxr-xr-x    1 root     root       5887272 Aug  2 16:46 libjemalloc.so.2
> -rwxr-xr-x    1 root     root      22407794 Aug  2 16:46 libjemalloc_pic.a
> drwxr-xr-x    2 root     root          4096 Aug  2 16:46 pkgconfig
> [core-ssh lib]$
> ```

same problem for me

**Comment by strasharo** [comment]
> My solution similar to @galtamur I changed lines 39-42 in openapi.py from this:
> 
> ```
>         self.expire_time = (
>             token_response.get("t", 0)
>             + result.get("expire", result.get("expire_time", 0)) * 1000
>         )
> ```
> 
> to this:
> 
> ```
>         self.expire_time = (
>             int(token_response.get("t", 0))
>             + int(result.get("expire", result.get("expire_time", 0))) * 1000
>         )
> ```
> 
> and put a copy of the patched file in a subdirectory where my Dockerfile lives _patch/openapi.py_
> 
> Here is my Dockerfile:
> 
> ```
> FROM ghcr.io/home-assistant/home-assistant:stable
> COPY patch/openapi.py /usr/local/lib/python3.10/site-packages/tuya_iot/openapi.py
> ```

This solution fixed the issue for me, thanks a lot for the tip.

**Comment by malosaa** [comment]
Will this be fixed in the next hass update ? 
as i'm having the same issue, running it from VM

**Comment by neslieang** [comment]
> My solution similar to @galtamur I changed lines 39-42 in openapi.py from this:
> 
> ```
>         self.expire_time = (
>             token_response.get("t", 0)
>             + result.get("expire", result.get("expire_time", 0)) * 1000
>         )
> ```
> 
> to this:
> 
> ```
>         self.expire_time = (
>             int(token_response.get("t", 0))
>             + int(result.get("expire", result.get("expire_time", 0))) * 1000
>         )
> ```
> 
> and put a copy of the patched file in a subdirectory where my Dockerfile lives _patch/openapi.py_
> 
> Here is my Dockerfile:
> 
> ```
> FROM ghcr.io/home-assistant/home-assistant:stable
> COPY patch/openapi.py /usr/local/lib/python3.10/site-packages/tuya_iot/openapi.py
> ```

any advise how to access the python libs path in VM installation?

**Comment by Mithriler** [comment]
> how would i make this change in HASS OS?

any hint?

**Comment by buhito81** [comment]
This looks like _we might just get_ a HA 2022.9.8 release

**Comment by strasharo** [comment]
Created a PR for it:
https://github.com/tuya/tuya-iot-python-sdk/pull/65

**Comment by galtamur** [comment]
> > May happen that the problem is that you should search INSIDE the docker; could be?
> 
> tell a beginner how to do it?

To enter the docker execute:
docker exec -it home-assistant sh

**Comment by zibbs** [comment]
And it's allready working, without doing nothing.

**Comment by whitebearded** [comment]
Same issue using HAS OS. Not sure if this is causing any update issues later on or whether it will survive a restart but this fixed it immediately for me. **Use on your own risk!**

1. Login via SSH
2. Run `docker exec -it homeassistant sh`
3. Inside the docker container run: 
`sed -i 's/ result.get("expire", result.get("expire_time", 0))/ int(result.get("expire", result.get("expire_time", 0)))/g' /usr/local/lib/python3.10/site-packages/tuya_iot/openapi.py`

**Comment by defsix** [comment]
Just rebuilt my container with the latest image pull and all is now working.

I didn't change anything on my end.

[docker.io/homeassistant/home-assistant:latest](http://10.0.1.10:9000/#!/2/docker/images/docker.io~2Fhomeassistant~2Fhome-assistant%3Alatest)

**Comment by Raksha91** [comment]
Try now. It seems to have been resolved.

**Comment by Zingrock** [comment]
> > > May happen that the problem is that you should search INSIDE the docker; could be?
> > 
> > 
> > tell a beginner how to do it?
> 
> Seems like its an issue for everyone - i.e. server side I'm going to wait a few hours and hope they fix with an update

Well I'm glad I waited - its fixed now :)

**Comment by buhito81** [comment]
> After migrating to HA Core 2022.9.7 (on docker-debian) the Tuya integration cannot setup and i see this error in the log:
> 
> Logger: homeassistant.config_entries
> Source: components/tuya/__init__.py:79
> First occurred: 9:35:56 AM (1 occurrences)
> Last logged: 9:35:56 AM
> 
> Error setting up entry giuliano@altamuraonline.net for tuya
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/usr/src/homeassistant/homeassistant/components/tuya/__init__.py", line 79, in async_setup_entry
>     response = await hass.async_add_executor_job(
>   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.10/site-packages/tuya_iot/openapi.py", line 222, in connect
>     self.token_info = TuyaTokenInfo(response)
>   File "/usr/local/lib/python3.10/site-packages/tuya_iot/openapi.py", line 41, in __init__
>     token_response.get("t", 0)
> TypeError: unsupported operand type(s) for +: 'int' and 'str'
> 
> Any help?

Will you close the issue?

**Comment by galtamur** [comment]
Thank you
