### ISSUE TITLE
Tuya Outlet/Plug - add kWh (day/month) sensors

### ISSUE THREAD

**Issue by JamieP83** [tuya/tuya-home-assistant#858]
**Describe the bug**

With the plugs today, you have the following available in HA:
- switch (on/off)
- Current
- Power
- Voltage
However the ability to see kWh for energy monitoring is missing. 

**Expected behavior**

In the Tyua app, you also get energy monitor of kWh per day and month 
this is required for the "energy" dashboard in HA. 

**Diagnostics for integrations and devices**

**Screenshots**

<img width="764" alt="image" src="https://user-images.githubusercontent.com/48566948/195067307-c3e3d687-9d56-4c12-8f98-e135082a6d67.png">

![image](https://user-images.githubusercontent.com/48566948/195069358-0aa6ac33-ea10-4ff4-8875-ad69415606a2.png)
![image](https://user-images.githubusercontent.com/48566948/195069399-315674ff-8b70-428d-b60d-2407ed036cec.png)

**Home Assistant Version**
Home Assistant 2022.10.3
Supervisor 2022.10.0
Operating System 9.0

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**

like this:
{
      "active_time": 1623229189,
      "biz_type": 18,
      "category": "cz",
      "create_time": 1560491945,
      "icon": "smart/product_icon/cz.png",
      "id": "aaaaaaaaaaa",
      "ip": "xxxxxxxxxxxxxxxx",
      "lat": "xxxxxxxxxx",
      "local_key": "xxxxxxxxxxxxx",
      "lon": "xxxxxxx",
      "model": "",
      "name": "Living Room Socket",
      "online": false,
      "owner_id": "34794909",
      "product_id": "yfemiswbgjhddhcf",
      "product_name": "Switch Product",
      "status": [
        {
          "code": "switch",
          "value": false
        },
        {
          "code": "countdown_1",
          "value": 0
        },
        {
          "code": "cur_current",
          "value": 0
        },
        {
          "code": "cur_power",
          "value": 0
        },
        {
          "code": "cur_voltage",
          "value": 2343
        }
      ],
      "sub": false,
      "time_zone": "+08:00",
      "uid": "xxxxxxxxxxxxxxxxxxx",
      "update_time": 1625101929,
      "uuid": "xxxxxxxxxxxxxxxxxx"
    }

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.10.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "5.15.61-v8",
    "supervisor": "2022.10.0",
    "host_os": "Home Assistant OS 9.0",
    "docker_version": "20.10.17",
    "chassis": "embedded",
    "run_as_root": true
  },
  },
  "integration_manifest": {
    "domain": "tuya",
    "name": "Tuya",
    "documentation": "https://www.home-assistant.io/integrations/tuya",
    "requirements": [
      "tuya-iot-py-sdk==0.6.6"
    ],
    "dependencies": [
      "ffmpeg"
    ],
    "codeowners": [
      "@Tuya",
      "@zlinoliver",
      "@frenck"
    ],
    "config_flow": true,
    "iot_class": "cloud_push",
    "dhcp": [
      {
        "macaddress": "105A17*"
      },
      {
        "macaddress": "10D561*"
      },
      {
        "macaddress": "1869D8*"
      },
      {
        "macaddress": "381F8D*"
      },
      {
        "macaddress": "508A06*"
      },
      {
        "macaddress": "68572D*"
      },
      {
        "macaddress": "708976*"
      },
      {
        "macaddress": "7CF666*"
      },
      {
        "macaddress": "84E342*"
      },
      {
        "macaddress": "D4A651*"
      },
      {
        "macaddress": "D81F12*"
      }
    ],
    "loggers": [
      "tuya_iot"
    ],
    "is_built_in": true
  },
  "data": {
    "endpoint": "https://openapi.tuyaeu.com",
    "auth_type": 0,
    "country_code": "44",
    "app_type": "smartlife",
    "mqtt_connected": true,
    "disabled_by": null,
    "disabled_polling": false,
    "name": "8Tree A",
    "model": "JX-SP23BL-8720CF-13A\u5e26\u8ba1\u91cf\u516c\u7248",
    "category": "cz",
    "product_id": "zae4ua68xt9wxfap",
    "product_name": "",
    "online": true,
    "sub": false,
    "time_zone": "+01:00",
    "active_time": "2022-10-10T11:11:24+00:00",
    "create_time": "2022-10-10T11:11:24+00:00",
    "update_time": "2022-10-10T11:13:43+00:00",
    "function": {
      "switch_1": {
        "type": "Boolean",
        "value": {}
      },
      "countdown_1": {
        "type": "Integer",
        "value": {
          "unit": "s",
          "min": 0,
          "max": 86400,
          "scale": 0,
          "step": 1
        }
      },
      "relay_status": {
        "type": "Enum",
        "value": {
          "range": [
            "power_off",
            "power_on",
            "last"
          ]
        }
      },
      "cycle_time": {
        "type": "String",
        "value": {}
      },
      "random_time": {
        "type": "String",
        "value": {}
      }
    },
    "status_range": {
      "switch_1": {
        "type": "Boolean",
        "value": {}
      },
      "countdown_1": {
        "type": "Integer",
        "value": {
          "unit": "s",
          "min": 0,
          "max": 86400,
          "scale": 0,
          "step": 1
        }
      },
      "add_ele": {
        "type": "Integer",
        "value": {
          "unit": "kW\u00b7h",
          "min": 0,
          "max": 50000,
          "scale": 3,
          "step": 100
        }
      },
      "cur_current": {
        "type": "Integer",
        "value": {
          "unit": "mA",
          "min": 0,
          "max": 30000,
          "scale": 0,
          "step": 1
        }
      },
      "cur_power": {
        "type": "Integer",
        "value": {
          "unit": "W",
          "min": 0,
          "max": 80000,
          "scale": 1,
          "step": 1
        }
      },
      "cur_voltage": {
        "type": "Integer",
        "value": {
          "unit": "V",
          "min": 0,
          "max": 5000,
          "scale": 1,
          "step": 1
        }
      },
      "relay_status": {
        "type": "Enum",
        "value": {
          "range": [
            "power_off",
            "power_on",
            "last"
          ]
        }
      },
      "cycle_time": {
        "type": "String",
        "value": {}
      },
      "random_time": {
        "type": "String",
        "value": {}
      }
    },
    "status": {
      "switch_1": true,
      "countdown_1": 0,
      "add_ele": 4,
      "cur_current": 74,
      "cur_power": 88,
      "cur_voltage": 2428,
      "relay_status": "last",
      "cycle_time": "",
      "random_time": ""
    },
    "home_assistant": {
      "name": "8Tree A",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "tuya__relay_status",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "select.smart_socket_power_on_behavior",
            "state": "last",
            "attributes": {
              "options": [
                "power_off",
                "power_on",
                "last"
              ],
              "device_class": "tuya__relay_status",
              "friendly_name": "8Tree A Power on behavior"
            },
            "last_changed": "2022-10-11T08:57:03.915200+00:00",
            "last_updated": "2022-10-11T08:57:03.915200+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "current",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": "A",
          "state": {
            "entity_id": "sensor.smart_socket_current",
            "state": "0.074",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "A",
              "device_class": "current",
              "friendly_name": "8Tree A Current"
            },
            "last_changed": "2022-10-11T10:36:02.923394+00:00",
            "last_updated": "2022-10-11T10:36:02.923394+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "power",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": "W",
          "state": {
            "entity_id": "sensor.smart_socket_power",
            "state": "8.8",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "W",
              "device_class": "power",
              "friendly_name": "8Tree A Power"
            },
            "last_changed": "2022-10-11T10:36:08.032510+00:00",
            "last_updated": "2022-10-11T10:36:08.032510+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "voltage",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": "V",
          "state": {
            "entity_id": "sensor.smart_socket_voltage",
            "state": "242.8",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "V",
              "device_class": "voltage",
              "friendly_name": "8Tree A Voltage"
            },
            "last_changed": "2022-10-11T10:36:02.924865+00:00",
            "last_updated": "2022-10-11T10:36:02.924865+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "outlet",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.smart_socket_socket_1",
            "state": "on",
            "attributes": {
              "device_class": "outlet",
              "friendly_name": "8Tree A Socket 1"
            },
            "last_changed": "2022-10-11T08:57:04.029133+00:00",
            "last_updated": "2022-10-11T08:57:04.029133+00:00"
          }
        }
      ]
    }
  }
}

**Additional context**

Add any other context or logs about the problem here.

**Comment by frenck** [comment]
Tuya does not provide this value in a way Home Assistant can use it or work with it. As you can see in your API response you have pasted, it nowhere provides this data.

You can use the Riemann sum integral integration to create a energy sensor out of the power sensor, see: <https://www.home-assistant.io/integrations/integration>

../Frenck
