### ISSUE TITLE
Tuya on new HA update 

### ISSUE THREAD

**Issue by kevvar** [tuya/tuya-home-assistant#865]
Hi, today I updated HA to 2022.10.5 and all my tuya devices connected with official integration were erased. Does anyone have the same issue?

**Comment by fordemon92** [comment]
I'm Having a similar issue mine show in home assistant but they are all unavailable so I'm rolling back to the previous version till this has been resolved bc most my stuff is in the tuya platform

**Comment by kevvar** [comment]
Did work for you @fordemon92? I restored my instance but it keeps with the issue

**Comment by fordemon92** [comment]
@kevvar no same here but I did go in and click see known issues apparently it sounds like our api key or part of it has ran out and we have to request another 6 months from tuya to get it back and could take them a few days to get us back in but the guide was under the known issues popup like the 4th one down I believe I'm really new to all this so sorry for not being better help

**Comment by kevvar** [comment]
Dont worry budy I'm new in HA too, thanks!

**Comment by Takesis90** [comment]
some solution??

**Comment by kevvar** [comment]
> some solution??

This work for me #836

**Comment by kevvar** [comment]
> some solution??

This worked for me #836 I'm thinking seriously change my tuya devices, doing this things doesn't have any sense
