### ISSUE TITLE
Battery state not shown for an "mcs" door sensor

### ISSUE THREAD

**Issue by strasharo** [tuya/tuya-home-assistant#89]
**Describe the bug**
The battery status isn't being displayed for an mcs door sensor, even though there's a battery entity for it and it's available in the Tuya app.

**Expected behavior**
The battery status should be displayed in the HA battery entity, as the info is available via the API.

**Screenshots**
![image](https://user-images.githubusercontent.com/3337997/124431935-b442f380-dd79-11eb-9cf1-49d6675342b5.png)

**Home Assistant Version**
- e.g. 2021.6.6

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
like this:
{
  "result": {
    "active_time": 1624891087,
    "biz_type": 0,
    "category": "mcs",
    "create_time": 1624887351,
    "icon": "smart/icon/ay15427647462366edzT/042f961da388104417809668b6c83e2b.jpg",
    "id": "08102037e8db84b83367",
    "ip": "<scrubbed>",
    "lat": "",
    "local_key": "<scrubbed>",
    "lon": "",
    "name": "Server room",
    "online": true,
    "owner_id": "<scrubbed>",
    "product_id": "3slpirlnlqp0bqo1",
    "product_name": "Contact Sensor",
    "status": [
      {
        "code": "doorcontact_state",
        "value": false
      },
      **{
        "code": "battery_state",
        "value": "high"
      }**
    ],
    "sub": false,
    "time_zone": "+02:00",
    "uid": "<scrubbed>",
    "update_time": 1625468758,
    "uuid": "<scrubbed>"
  },
  "success": true,
  "t": 1625469355129
}
**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
Same device's id, like this:
{
  "result": {
    "category": "mcs",
    "functions": [],
    "status": [
      {
        "code": "doorcontact_state",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "battery_state",
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"middle\",\"high\"]}"
      }
    ]
  },
  "success": true,
  "t": 1625469533121
}

**Additional context**
This is the device:
https://expo.tuya.com/product/559866

**Comment by mrwhite31** [comment]
I am having the same problem.
Besides a contact sensor with "battery_state" like above I also do have one with "battery_value".

"status": [
{
"code": "doorcontact_state",
"value": false
},
{
"code": "battery_value",
"value": 100
}
],

................................................................................................................................................................................
................................................................................................................................................................................

"result": {
"category": "mcs",
"functions": [],
"status": [
{
"code": "doorcontact_state",
"type": "Boolean",
"values": "{}"
},
{
"code": "battery_value",
"type": "Integer",
"values": "{\"unit\":\"v\",\"min\":0,\"max\":1000,\"scale\":-2,\"step\":1}"
}
]
},
"success": true,
"t": 1625429449354
}

**Comment by tsutsuku** [comment]
@mrwhite31 Can you provide the device info?
@osk2 Home assistant battery sensor entity only supports percent now, so we can't find a good way to display enum battery level.

**Comment by mrwhite31** [comment]
@tsutsuku please find the device info below.

couldn't you map "high" to 100%, "middle" to 50% and "low" to 10%?

{
"active_time": 1625507348,
"biz_type": 0,
"category": "mcs",
"create_time": 1554913101,
"icon": "smart/product_icon/qt.png",
"id": "",
"ip": "",
"lat": "47.4",
"local_key": "",
"lon": "7.6",
"model": "",
"name": "Window Sensor",
"online": true,
"owner_id": "",
"product_id": "7by9ERqg60JA8wxA",
"product_name": "Door Sensor",
"status": [
{
"code": "doorcontact_state",
"value": false
},
{
"code": "battery_value",
"value": 100
}
],
"sub": false,
"time_zone": "+01:00",
"uid": "",
"update_time": 1625509438,
"uuid": ""
},

**Comment by strasharo** [comment]
@mrwhite31's suggestion to map it to some values makes sense.

**Comment by strasharo** [comment]
@tsutsuku looks like the battery_state sensor coming from the mobile app is an enum:
https://companion.home-assistant.io/docs/core/sensors/

![image](https://user-images.githubusercontent.com/3337997/125071226-b1216d80-e0c1-11eb-9cbe-0832731981f7.png)

![image](https://user-images.githubusercontent.com/3337997/125071267-bda5c600-e0c1-11eb-8f33-83b7381432d7.png)

Maybe the integration could provide that type of entity?

**Comment by strasharo** [comment]
Version v1.3.2 fixed it, the battery now shows "normal" state. Thanks, @tsutsuku !
