### ISSUE TITLE
Australia region 

### ISSUE THREAD

**Issue by OIIIIO** [tuya/tuya-home-assistant#91]
can't connect with a +61 australia region and no options in console to add

**Comment by joe-sydney** [comment]
Are your devices linked in Tuya IoT Platform? Should appear under Europe...

**Comment by millers** [comment]
I'm connected from Australia. For the region I selected Europe (in the tuya iot dashboard and the home assistant I
Integration setup) then used 61 for the country code in HA setup

**Comment by pyrosx** [comment]
I'm having a similar problem. I've tried every combo of Region and Country Code I can think of, and no authentication success yet.

My devices in iot.tuya are listed under America, not Europe.

**Comment by tsutsuku** [comment]
@millers Try v1.3.1, if login is still not successful, please provide the log.

**Comment by jessexoc** [comment]
After some trial and error, I managed to get it working with the following:

I followed steps for "Listing Tuya devices from the **Tuya Smart** or **Smart Life** apps" in https://github.com/codetheweb/tuyapi/blob/1f1f8e5a678c7dd019b21d4b33b9a8d5d3ca02f8/docs/SETUP.md#listing-tuya-devices-from-the-tuya-smart-or-smart-life-apps (note I had done parts of this previously trying to set up a different integration, and some of the steps are not 100% the same, but you should be able to figure it out).

(reproduced here in order)

> 1. Create a new account on [iot.tuya.com](https://iot.tuya.com) and make sure you are logged in. **Select United States as your country when signing up.** This seems to skip a [required verify step](https://github.com/codetheweb/tuyapi/issues/425).
> 2. Go to Cloud -> Projects in the left nav drawer. If you haven't already, you will need to "purchase" the Trial Plan before you can proceed with this step. You will not have to add any form of payment, and the purchase is of no charge. Once in the Projects tab, click "Create". **Make sure you select "Smart Home" for the "Industry" field and PaaS for the development method.** Select your country of use in the for the location access option, and feel free to skip the services option in the next window. After you've created a new project, click into it. The access ID and access key are equivalent to the API key and API secret values need in step 7.

(note that you need to select Europe as one of the Availability Zones here, or you can add it later in the project settings)

> 3. Go to Cloud > Projects> "MyProject" > API > "Go to authorize". "Select API" > click subscribe on "Smart Home Devices Management" in the dropdown. Click subscribe again. Click "basic edition" and "buy now" (basic edition is free). Check if the "Smart Home Devices Management" API is listed under Cloud > Projects > "MyProject" > API. If not, click "New Authorization" and select it.
> 2. Go to Cloud -> Project and click the project you created earlier. Then click "Link Device". Click the "Link Devices by App Account" tab.
> 3. Click "Add App Account" and scan the QR code from your smart phone/tablet app by going to the 'Me' tab in the app, and tapping a QR code / Scan button in the upper right. Your account will now be linked.

Then in the Tuya developer console for the project created for Home assistant:
- (if you didn't do this during the project setup) Project Overview -> Edit -> Availability Zone: add Europe (remove others to make things cleaner if you want)
- Device List -> Region: set to Europe / Account: App Account -> <username>. You should then see the devices you have already paired with your TuyaSmart app account. You can verify the TuyaSmart app username here also.

When setting up the Home Assistant integration:
- Tuya cloud project type: Smart Home PaaS
- Access ID: From the Tuya Cloud Project Overview (`https://iot.tuya.com/cloud/.....`), the value for `Access ID/Client ID`
- Access Secret: From the Tuya Cloud Project Overview (`https://iot.tuya.com/cloud/.....`), the value for `Access Secret/Client Secret`
- Mobile App: TuyaSmart (this is the one I use)
- Country code: 61
- Account: your TuyaSmart app account username
- Password: your TuyaSmart app account password

**Comment by pyrosx** [comment]
Was still failing to login, until I realised the login details where the ones for the Access App (Smart Life), not the Dev (iot.tuya.com) set. Whoops!

**Comment by MickW69** [comment]
Still no success here: 
Tuya v1.3.1
Home Assistant 2021.7.0
Mobile App: TuyaSmart

2021-07-10 10:20:36 INFO (SyncWorker_8) [custom_components.tuya_v2.config_flow] TuyaConfigFlow._try_login finish, response:, {'code': 1106, 'msg': 'permission deny', 'success': False, 't': 1625876436422}

IOT platform set to Europe (new project)
Mobile app Australia

email & password used for login to app and IOT are the same (so I can't get them mixed up)

have tried country code 61 & +61 

out of ideas as to what else to try

**Comment by thetastate1** [comment]
Understood still beta.

I get an 'Unknown error occurred' rather than 'Invalid authentication'.

Australian account. Project created today.

Devices appear in project under China rather than Europe as specified in documentation.

Development method in Tuya IoT console says 'Smart Home' not 'Smart Home PaaS' as documented.

Tuya cloud project type when adding Tuya V2 integration in HA is 0='Smart Home PaaS', 1='Custom Development'

**Comment by thetastate1** [comment]
Still no luck after persevering and creating two new Tuya developer accounts and several projects.

Appreciate any pointers @tsutsuku 

All of my IoT cloud projects (in each developer account) successfully list all 55 Tuya devices but only under 'China'. One of the developer accounts is set to Australia and one to China. TuyaSmart app is Australia with +61 phone number. Both accounts list the devices under China but the Home Assistant integration page returns 'Unknown error occurred'. Section of log extract below.

HA 2021.7.1

Tried rolling back to Tuya v2 1.3 then forward again to 1.3.1. No change.


Log Extract:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/local/lib/python3.8/dist-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/local/lib/python3.8/dist-packages/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
    return await handler(request)
  File "/usr/local/lib/python3.8/dist-packages/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/local/lib/python3.8/dist-packages/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/local/lib/python3.8/dist-packages/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/local/lib/python3.8/dist-packages/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/local/lib/python3.8/dist-packages/homeassistant/components/config/config_entries.py", line 155, in post
    return await super().post(request, flow_id)
  File "/usr/local/lib/python3.8/dist-packages/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/local/lib/python3.8/dist-packages/homeassistant/data_entry_flow.py", line 202, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/local/lib/python3.8/dist-packages/homeassistant/data_entry_flow.py", line 260, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/home/.homeassistant/custom_components/tuya_v2/config_flow.py", line 126, in async_step_user
    response = await self.hass.async_add_executor_job(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/.homeassistant/custom_components/tuya_v2/config_flow.py", line 86, in _try_login
    response = api.login(user_input[CONF_USERNAME],
  File "/home/.homeassistant/deps/lib/python3.8/site-packages/tuya_iot/openapi.py", line 192, in login
    else self.post(
  File "/home/.homeassistant/deps/lib/python3.8/site-packages/tuya_iot/openapi.py", line 303, in post
    return self.__request("POST", path, None, params)
  File "/home/.homeassistant/deps/lib/python3.8/site-packages/tuya_iot/openapi.py", line 246, in __request
    response = self.session.request(
  File "/home/.homeassistant/deps/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)

**Comment by thetastate1** [comment]
What a difference a day makes ;) 
No changes on my side but magically I started getting "Invalid authentication" rather than "Unknown error occurred" this morning. Just popped the +61 instead of 61 and bingo. All working.

**Comment by tsutsuku** [comment]
@OIIIIO  have your issue solved?

**Comment by OIIIIO** [comment]
yes I solved , it yesterday as I have been away  with your guidance,  very much appreciated cheers mat Sent from my Galaxy
-------- Original message --------From: tsutsuku ***@***.***> Date: 26/7/21  17:37  (GMT+10:00) To: tuya/tuya-home-assistant ***@***.***> Cc: OIIIIO ***@***.***>, Mention ***@***.***> Subject: Re: [tuya/tuya-home-assistant] Australia region  (#91) 
@OIIIIO  have your issue solved?
