### ISSUE TITLE
Can't link Tuya app account

### ISSUE THREAD

**Issue by lordbah** [tuya/tuya-home-assistant#939]
**Describe the bug**

Not a bug but a plea for help from others who have been through this. Can't link Tuya app account due to "Data center inconsistency". On the mobile app Smart Life the Region is "United States of America/Can..." (I see no way to view the rest of that string, rotating screen does nothing nor does clicking on it). No such data center exists when creating a new cloud project. I selected all 6 that were available and still got this error. Anyone been through this?

The remainder of the bug template is N/A.

**Comment by lordbah** [comment]
Tuya did something and told me to try Western America again, and it worked.

**Comment by Scotty13a** [comment]
I had a similar problem but in Europe. I was unable to Link Devices by App Account and got the error message: Data centers inconsistency.
Solution: under "Data/Data Profiles" I could change Data Center from Western Europe to Central Europe. After that changing data projects Data Center (still Western) to "Central Europe Data Center" was still not possible. This is cause Account for free only allows the use of one(!) Data Center the same time. I had to erase all (!!) Data Centers of all my projects (also that project I wanted to modify) before it was possible to select another Data Center...
good luck!
