### ISSUE TITLE
Tuya integration - Pro Breeze 30l dehumidifier

### ISSUE THREAD

**Issue by ghost** [tuya/tuya-home-assistant#959]
Help is needed, please. I'm going to try to explain this clearly.

I've created the Tuya IoT platform project, and it's all linked up. Added the integration and the entity is showing. All seems fine. However, I can't control it.

The instructions that are in the Tuya IoT are in figure 1, and the HA entity is in figure 2.

As far as I can tell, with my limited knowledge, the state should be the power? If I update it from the Tuya IoT it does turn it off, but from HA it can't read the state, nor can I control it at all.

Can anyone help with a clue on how to make it work? Or is it just not supported?

Thanks!
fig 1 ![image](https://github.com/tuya/tuya-home-assistant/assets/110598669/0b7e07c2-b438-43ad-b38c-86eee95eddc4)
fig 2 ![image](https://github.com/tuya/tuya-home-assistant/assets/110598669/b3571565-74e9-4e70-b318-728ae5567200)

**Comment by ghost** [comment]
Sorted

**Comment by Testingfor101** [comment]
Could you explain what have you done?

**Comment by ghost** [comment]
On the Tuya IoT platform project, find the device ID of the dehumidifier.

Make a note of the device IDs for the device. Then, select "Cloud" on the sidebar and go to the API Explorer. Under "Devices Management," select the "Query Device Details in Bulk" function and enter your device ID. Here, you will find the device's local key.

Once you have the device ID and local key, you need to configure the local tuya integration. Select the device to integrate with its device ID/IP on your network, then click "Configure" and add a new device.

Name: dehumidifier (for example) Host: the device IP Local key: the local key previously found Protocol Version 3.3

At the bottom you can check add more entities Then click submit.

Configure the data points (DP) of the device as follows:

DP1/id: 1

platform/type: switch friendly_name: Power

DP2/id: 2

platform/type: select friendly_name: Mode Valid entries: 0;1 User Friendly options: Auto;Continuous

DP3/id: 3

platform/type: sensor friendly_name: Current Humidity Unit of Measurement: % Device Class: humidity

DP4/id: 4

platform/type: number friendly_name: Target Humidity Minimum Value: 30 Maximum Value: 80 Minimum increment between numbers: 5

DP6/id: 6

platform/type: select friendly_name: Wind Speed Valid entries: 1;0 User Friendly options: Slow;High

DP7/id: 7

platform/type: switch friendly_name: Child Lock (Lock)

DP8/id: 8

platform/type: select friendly_name: Swing (Shake) Valid entries: True;False User Friendly options: Active;Inactive

DP11/id: 11

platform/type: sensor friendly_name: Fault/Water tank is full

DP12/id: 12

platform/type: select friendly_name: Countdown Valid entries: 0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15;16;17;18;19;20;21;22;23;24 User Friendly options: Inactive;1 Hour;2 Hours;3 Hours;4 Hours;5 Hours;6 Hours;7 Hours;8 Hours;9 Hours;10 Hours;11 Hours;12 Hours;13 Hours;14 Hours;15 Hours;16 Hours;17 Hours;18 Hours;19 Hours;20 Hours;21 Hours;22 Hours;23 Hours;24 Hours

DP13/id: 13

platform/type: sensor friendly_name: Countdown Remaining (Countdown Left) Unit of Measurement: mins Device Class: duration

DP101/id: 101

platform/type: sensor
friendly_name: Inside Drying (Dry) Valid entries: False;True User Friendly options: Not Activated;Activated

You should now be able to manage and control the dehumidifier through Home Assistant.
