### ISSUE TITLE
Login Error QR code is not generated with "Invalid hex color" error

### ISSUE THREAD

**Issue by ghds514** [tuya/tuya-home-assistant#975]
Following installation of 2024.2.0, I was prompted to reconfigure Tuya integration as expected. After entering the user code supplied by the Tuya Smart app, no QR was generated, with the following error instead arising: "Invalid hex color: hsl(220, 5%, 90%)". Login was therefore prevented.

**Comment by cmgestevao** [comment]
I have the same problem, but the error message is "Invalid hex color: rgb(240, 240, 240)"


![image](https://github.com/tuya/tuya-home-assistant/assets/97468347/d2a7012a-f53d-4299-a474-9508666330f1)

**Comment by ghds514** [comment]
So, I just tried again out of curiosity and it worked this time. Perhaps their servers were overloaded.

**Comment by ghds514** [comment]
Marking the issue closed as it appears to be transient.

**Comment by uronito** [comment]
same error here

**Comment by ghds514** [comment]
I recommend re-trying at intervals as it eventually worked for me and remains logged in. The rush of registrations following 2024.2.0 may be the issue.

**Comment by ChaosExAnima** [comment]
I fixed it by switching back to my default theme for setup. Here's an open issue tracking it on the HASS side:

https://github.com/home-assistant/core/issues/110004#issuecomment-1934144098

**Comment by sanswit** [comment]
This is the way! Nice find.

> I fixed it by switching back to my default theme for setup. Here's an open issue tracking it on the HASS side:
> 
> [home-assistant/core#110004 (comment)](https://github.com/home-assistant/core/issues/110004#issuecomment-1934144098)
