### ISSUE TITLE
Login Error QR code is not generated with "Invalid hex color" error

### ISSUE THREAD

**Issue by uronito** [tuya/tuya-home-assistant#976]
when i try login, appears this error in homeassitant

**Comment by whyyouhateme** [comment]
![Снимок экрана 2024-02-08 105503](https://github.com/tuya/tuya-home-assistant/assets/154468298/24f91ed4-8552-4f1c-9ba3-e1a71979dde0)
Seconded, also got this error after upgrading to 2024.2.0

**Comment by whyyouhateme** [comment]
> when i try login, appears this error in homeassitant

Solved this problem by installing the default theme. Give it a try, it should help. 
https://community.home-assistant.io/t/problem-with-tuya-in-2024-2/686412/6

**Comment by uronito** [comment]
Works like a charm!!!!!!!!!

Thanks!!!!!
