### ISSUE TITLE
2024.4 Tuya integration: lights white/color mode not updated

### ISSUE THREAD

**Issue by bartplessers** [tuya/tuya-home-assistant#987]
**Describe the bug**

Since HA 2024.4.0 I noticed that HA does not show the color mode correctly of my Tuya bulbs.

So

- on/off is correctly displayed
- when I change color in HA: icon shows the selected color
- when I switch back to white modus in the Tuya app (I can’t switch to white modus in HA): the color of the icon in HA remains in color modus although the bulb works now in white modus
- on/off works in HA, but when I want to change the brightness in HA, the old color modus is sent to the bulb

This makes that all my Tuya bulbs become more or less useless in HA:
- I can’t switch to white modus in HA
- I can’t dimm my lights because than they switch to the previous color modus

REMARK:
If the bulb supports [white with CCT + color modus], the problem does NOT occur
This behaviour only occurs with bulbs that have [white + color modus].
With this, I mean

### TYPE 1
This bulb supports white with CCT and color:
![321383552-98e175f4-ff20-4c79-b5b7-ddb3e2ad6206](https://github.com/tuya/tuya-home-assistant/assets/10470708/1fb2de81-c5cb-4f0d-b331-9f9fd575564e)

You can see that you can select a warm white on the left side of the arc, and a cool white (more blue) on the right side of the arc. The light still remains in “white modus”, but you can modify the correlated color temperature (CCT)
Beside this, you can also choose the “color modus” (on the top, select “kleur”).
In that case, you can choose any RGB color that you want

### TYPE 2
This bulb only supports white and color:
![321383676-2b76cf61-b518-4b1f-ae5a-cbcc06911a96](https://github.com/tuya/tuya-home-assistant/assets/10470708/84aebd23-6aad-4361-88d4-11532aff99bd)

You can see that there is no difference in color temperature in the arc. The white modus supports only one temperature of white.
Beside this, you can also choose the “color modus” (on the top, select “kleur”).

The problem we are dealing with does only occur on bulbs of **TYPE 2**.

**Expected behavior**

HA should show correct modus of bulb. 

**Diagnostics for integrations and devices**

[config_entry-tuya-40b4813a92b0c0230ab7e16905d5861b.json](https://github.com/tuya/tuya-home-assistant/files/14971609/config_entry-tuya-40b4813a92b0c0230ab7e16905d5861b.json)

**Screenshots**
I have 2 instances running simultaniously on my network, both with tuya integration, connected with the same account.
![320789565-148078df-b550-42bc-8bed-c3485ac51c96](https://github.com/tuya/tuya-home-assistant/assets/10470708/d43a57b4-9412-4abf-8174-0dde19d31c89)

- left image: HA 2024.3.1
- right image: HA 2024.4.2

What I did:

- in HA changed color of the bulb to blue
- in TUYA-app, I changed back to white

Version 2024.3.1: shows the correct state of the bulb
Version 2024.4.2: state of bulb is NOT updated and remains blue

**Home Assistant Version**
- 2024.4.x 
- (no problem with 2024.3.3. Problem started at 2024.4.0)

**Device info:**

### HA 2024.3.3
![321386787-00033c84-93c4-4601-ad1d-3c8cd1ed204c](https://github.com/tuya/tuya-home-assistant/assets/10470708/922f73ba-9c51-4865-81bd-b91a670ec647)

### HA 2024.4.2
![321386887-c9660b91-c05e-4a96-a6ce-4eb9d2dca554](https://github.com/tuya/tuya-home-assistant/assets/10470708/26a2f8e3-4b68-428e-a9d9-15c03dc60c06)

So it seems that HA 2024.4.x does not recognize the "brightness" modus of this tuya bulb!

** additional info **
see also
https://github.com/home-assistant/core/issues/115056

**Comment by Kelso-Utah** [comment]
Many others in the community are also having this problem.

Changing brightness automatically places the Tuya light(s) into color mode.  Must use Tuya app to change back to white.

Here are links to related posts.

https://github.com/home-assistant/core/issues/115056
https://community.home-assistant.io/t/2024-4-tuya-integration-lights-white-color-mode-not-updated/713924

**Comment by bartplessers** [comment]
very similar to https://github.com/tuya/tuya-home-assistant/issues/958 
But here the problem seems to be present already in HA 2023.x...

**Comment by jacobgrillo** [comment]
should this be in the [tuya smart life](https://github.com/tuya/tuya-smart-life) repo, the version using qr code auth?

**Comment by spacelama** [comment]
> should this be in the [tuya smart life](https://github.com/tuya/tuya-smart-life) repo, the version using qr code auth?

I doubt it. Very first lines of README on that project:

> This project has now officially been integrated into the Home Assistant official project core repository, corresponding to version 2024.2. This project will no longer continue to iterate. Subsequent iterations and support will be carried out under the Home Assistant official project

Which also implies it doesn't belong here, since this repo hasn't had a commit in 6 months.

**Comment by bartplessers** [comment]
>Which also implies it doesn't belong here, since this repo hasn't had a commit in 6 months.

Ok, thanx. I was not sure were to post it, so I also made an issue in
https://github.com/home-assistant/core/issues/115056
but not much response there either :-(

I will close this here
