### ISSUE TITLE
Smartlife disconnects after restart of HA

### ISSUE THREAD

**Issue by MarcoEnd** [tuya/tuya-home-assistant#998]
**Describe the bug**

After HA update 2024.06 the access to smartlife gets lost and I have to reconfigure the integration. All entities are lost and have to reconfigure the hub using the app PW and then scan the QR code.
Error message:
Error calling entry remove callback abcde@abcde.xyz for smartlife

**Expected behavior**

Integration keeps working without reconfig; last working HA version 2024.05.x

**Diagnostics for integrations and devices**

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 858, in async_remove
    await component.async_remove_entry(hass, self)
  File "/config/custom_components/smartlife/__init__.py", line 197, in async_remove_entry
    await hass.async_add_executor_job(hass_data.manager.unload)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tuya_sharing/manager.py", line 218, in unload
    self.user_repository.unload(self.terminal_id)
  File "/usr/local/lib/python3.12/site-packages/tuya_sharing/user.py", line 40, in unload
    self.api.post("/v1.0/m/token/terminal/expire", None, {
  File "/usr/local/lib/python3.12/site-packages/tuya_sharing/customerapi.py", line 192, in post
    return self.__request("POST", path, params, body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tuya_sharing/customerapi.py", line 121, in __request
    raise Exception(f"network error:({ret['code']}) {ret['msg']}")
Exception: network error:(-9999999) sign invalid

**Screenshots**

n/a

**Home Assistant Version**
2024.06.3

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**

n/a

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**

n/a

**Additional context**

n/a

**Comment by miguelalonso** [comment]
Hello,
The same behaviour, after las HA update, ask for tuya authentication using QR continously.

**Comment by facuzestoa** [comment]
Same here happening with 2024.6 and now with 2024.7

**Comment by miguelalonso** [comment]
Now, for me, tuya is working for me in 2024.7.
I made also a reload of tuya integration.

**Comment by swanemar** [comment]
I'm still seeing the same issue on 2024.7.1

**Comment by NOELV70** [comment]
Experience same problem 2024.6 & 2024.7.
Reload integration does not help.
Rescan QR makes it work till next  (physical) reboot.

**Comment by MarcoEnd** [comment]
I switched to the Tuya Integration and this integration works fine now. It´s a bit anoying to change the integration because you will get new entities and have to change them in all automation, scripts, and so on. But if you do not have to manz entities it might be worth changing.

**Comment by MarcoEnd** [comment]
I switched to the Tuya Integration and this integration works fine now. It´s a bit anoying to change the integration because you will get new entities and have to change them in all automation, scripts, and so on. But if you do not have to manz entities it might be worth changing.

**Comment by swanemar** [comment]
I mean sure you can, but that’s not maintained and this (new) smart life app is the one being updated. I moved from Tuya with all of its cloud credential dependencies to this integration just to skip all that..

**Comment by MarcoEnd** [comment]
I also moved from Tuya to Smartlife some months ago. I moved to this Tuya integration: https://www.home-assistant.io/integrations/tuya/
Setup works via access code from the Smartlife App verz easy and no developer keys and other things needed from Tuya developer plattform.

**Comment by swanemar** [comment]
Huh, yeah you’re right. Moved my stuff to that and cross my fingers then

**Comment by Dickey01** [comment]
This must be the problem:

Logger: homeassistant.backports.enum Bron: helpers/deprecation.py:197  Eerst voorgekomen: 19:56:56 (2 gebeurtenissen)  Laatst gelogd: 20:01:03
StrEnum was used from smartlife, this is a deprecated alias which will be removed in HA Core 2025.5. Use enum.StrEnum instead, **please report it to the author of the 'smartlife' custom integration**

**Comment by jdekoven** [comment]
This just started happening to me yesterday.  Everytime there is a reboot I have to scan the QR code to get it working again.  I've deleted and re-added the Tuya intergration from Home Assistant and cleared cache, logged out and back in on the app, but still disconnects after reboot.  Has anyone found a solution to this issue?
